import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { ScreenContainer } from "@/components/screen-container";
import { recipes } from "@/lib/lezzet-data";

const collections = [{ title: "20 Dakikanın Altında", subtitle: "Yoğun günler için hızlı ve dengeli tarifler", ids: ["yesil-enerji-kasesi", "firin-domatesli-yumurta"], color: "#DDE8DA" }, { title: "Akdeniz Akşamları", subtitle: "Paylaşmalık, sebze ve iyi yağ odaklı sofralar", ids: ["akdeniz-mezze-tabagi", "akdeniz-somon-tabagi"], color: "#FCE6D2" }, { title: "Protein Ritmi", subtitle: "Haftalık hedefini koruyan pratik öğünler", ids: ["firin-domatesli-yumurta", "akdeniz-somon-tabagi"], color: "#E0ECE8" }];

export default function CollectionsScreen() { return <ScreenContainer className="flex-1" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.top}><Pressable onPress={() => router.back()} style={styles.back}><IconSymbol name="chevron.left" size={22} color="#1E4D3A" /></Pressable><View><Text style={styles.eyebrow}>KÜRATÖRLÜ TARİFLER</Text><Text style={styles.title}>Şef koleksiyonları</Text></View></View><Text style={styles.subtitle}>Tematik seri seç, ardından tarifleri planına tek tek ekle veya alternatif olarak kullan.</Text><View style={styles.list}>{collections.map((collection) => <View key={collection.title} style={[styles.card, { backgroundColor: collection.color }]}><View style={styles.cardTop}><View style={styles.badge}><IconSymbol name="sparkles" size={17} color="#1E4D3A" /></View><Text style={styles.count}>{collection.ids.length} TARİF</Text></View><Text style={styles.cardTitle}>{collection.title}</Text><Text style={styles.cardSubtitle}>{collection.subtitle}</Text><View style={styles.recipeLinks}>{collection.ids.map((id) => { const recipe = recipes.find((item) => item.id === id); return recipe ? <Pressable key={id} onPress={() => router.push(`/recipe/${id}` as never)} style={styles.link}><Text style={styles.linkText}>{recipe.title}</Text><IconSymbol name="chevron.right" size={16} color="#1E4D3A" /></Pressable> : null; })}</View></View>)}</View></ScrollView></ScreenContainer>; }

const styles = StyleSheet.create({ content: { padding: 20, gap: 17, paddingBottom: 34 }, top: { flexDirection: "row", alignItems: "center", gap: 11 }, back: { width: 41, height: 41, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: "#DDE8DA" }, eyebrow: { color: "#6B756F", fontSize: 10, fontWeight: "900", letterSpacing: 1 }, title: { color: "#1E2521", fontSize: 25, fontWeight: "800", marginTop: 2 }, subtitle: { color: "#6B756F", fontSize: 13, lineHeight: 19 }, list: { gap: 12 }, card: { padding: 16, borderRadius: 23, gap: 9 }, cardTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, badge: { width: 34, height: 34, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: "#FFFFFF" }, count: { color: "#52705E", fontSize: 10, fontWeight: "900", letterSpacing: 0.75 }, cardTitle: { color: "#1E2521", fontSize: 20, fontWeight: "800" }, cardSubtitle: { color: "#52705E", fontSize: 12, lineHeight: 17 }, recipeLinks: { gap: 7, marginTop: 3 }, link: { minHeight: 39, paddingHorizontal: 11, borderRadius: 12, backgroundColor: "rgba(255,255,255,0.72)", flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, linkText: { color: "#1E4D3A", fontSize: 12, fontWeight: "800" } });
