import { router } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { IconSymbol } from "@/components/ui/icon-symbol";
import { ScreenContainer } from "@/components/screen-container";
import { cuisineLocales, getCuisineProfile } from "@/lib/cuisine-locale";
import { useLezzet } from "@/lib/lezzet-context";

export default function CuisineRegionScreen() {
  const { profile, updateProfile } = useLezzet();
  const active = getCuisineProfile(profile.locale);
  return <ScreenContainer className="flex-1" containerClassName="bg-background" edges={["top", "bottom", "left", "right"]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><Text style={styles.backText}>‹</Text><Text style={styles.backLabel}>Profil</Text></Pressable>
    <View style={styles.hero}><View style={styles.heroBadge}><Text style={styles.heroBadgeText}>{active.flag}</Text></View><Text style={styles.kicker}>LEZZETAI LOCAL</Text><Text style={styles.title}>Dil ve mutfak bölgen</Text><Text style={styles.subtitle}>Seçimin, keşfettiğin tarifleri; kiler önceliklerini, haftalık planı ve AI Şef’in mutfak yaklaşımını değiştirir.</Text></View>
    <View style={styles.activeCard}><Text style={styles.activeLabel}>AKTİF PROFİL</Text><Text style={styles.activeTitle}>{active.language} · {active.region}</Text><Text style={styles.activeNote}>{active.planNote}</Text><View style={styles.chips}>{active.recommendedTools.slice(0, 4).map((tool) => <View key={tool} style={styles.toolChip}><Text style={styles.toolText}>{tool}</Text></View>)}</View></View>
    <View style={styles.list}>{cuisineLocales.map((item) => { const selected = item.code === profile.locale; return <Pressable key={item.code} onPress={() => updateProfile({ locale: item.code })} style={({ pressed }) => [styles.option, selected && styles.optionSelected, pressed && styles.pressed]}><View style={[styles.flag, selected && styles.flagSelected]}><Text style={[styles.flagText, selected && styles.flagTextSelected]}>{item.flag}</Text></View><View style={{ flex: 1 }}><Text style={[styles.optionTitle, selected && styles.optionTitleSelected]}>{item.language} · {item.region}</Text><Text style={[styles.optionText, selected && styles.optionTextSelected]} numberOfLines={2}>{item.planNote}</Text><Text style={[styles.optionPantry, selected && styles.optionPantrySelected]}>Kiler odağı: {item.pantryHighlights.join(" · ")}</Text></View>{selected ? <IconSymbol name="checkmark.circle.fill" size={22} color="#FFFFFF" /> : <IconSymbol name="chevron.right" size={19} color="#849087" />}</Pressable>; })}</View>
    <View style={styles.notice}><IconSymbol name="sparkles" size={18} color="#1E4D3A" /><Text style={styles.noticeText}>Bölgeyi değiştirmek mevcut planını silmez. Plan ekranındaki otomatik planlama eylemi, yeni bölgenle uyumlu 7 günlük menüyü oluşturur.</Text></View>
  </ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({
  content: { padding: 20, paddingBottom: 40, gap: 16 }, back: { alignSelf: "flex-start", flexDirection: "row", alignItems: "center", gap: 5, minHeight: 38, paddingHorizontal: 11, borderRadius: 13, backgroundColor: "#E8F0E5" }, backText: { color: "#1E4D3A", fontSize: 28, lineHeight: 28, fontWeight: "500" }, backLabel: { color: "#1E4D3A", fontSize: 12, fontWeight: "900" }, pressed: { opacity: 0.7 }, hero: { gap: 8, marginTop: 6 }, heroBadge: { width: 44, height: 44, borderRadius: 15, backgroundColor: "#173E2F", alignItems: "center", justifyContent: "center" }, heroBadgeText: { color: "#FFFFFF", fontSize: 12, fontWeight: "900" }, kicker: { color: "#6B756F", fontSize: 10, fontWeight: "900", letterSpacing: 1.2, marginTop: 3 }, title: { color: "#1E2521", fontSize: 30, lineHeight: 36, letterSpacing: -0.9, fontWeight: "900" }, subtitle: { color: "#5C6B61", fontSize: 13, lineHeight: 19, fontWeight: "600" }, activeCard: { gap: 7, padding: 16, borderRadius: 22, backgroundColor: "#173E2F" }, activeLabel: { color: "#A8CDB3", fontSize: 9, fontWeight: "900", letterSpacing: 1.1 }, activeTitle: { color: "#FFFFFF", fontSize: 18, fontWeight: "900" }, activeNote: { color: "#DDE8DA", fontSize: 12, lineHeight: 17, fontWeight: "600" }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginTop: 3 }, toolChip: { paddingHorizontal: 8, paddingVertical: 6, borderRadius: 10, backgroundColor: "#285C47" }, toolText: { color: "#E4F0E4", fontSize: 9, fontWeight: "800" }, list: { gap: 9 }, option: { minHeight: 86, flexDirection: "row", alignItems: "center", gap: 11, padding: 13, borderRadius: 20, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EAE7E0" }, optionSelected: { backgroundColor: "#1E4D3A", borderColor: "#1E4D3A" }, flag: { width: 38, height: 38, borderRadius: 13, backgroundColor: "#E8F0E5", alignItems: "center", justifyContent: "center" }, flagSelected: { backgroundColor: "#34684F" }, flagText: { color: "#1E4D3A", fontSize: 11, fontWeight: "900" }, flagTextSelected: { color: "#FFFFFF" }, optionTitle: { color: "#1E2521", fontSize: 14, fontWeight: "900" }, optionTitleSelected: { color: "#FFFFFF" }, optionText: { color: "#6B756F", fontSize: 10, lineHeight: 14, marginTop: 2, fontWeight: "600" }, optionTextSelected: { color: "#DDE8DA" }, optionPantry: { color: "#1E4D3A", fontSize: 9, marginTop: 5, fontWeight: "900" }, optionPantrySelected: { color: "#A8CDB3" }, notice: { flexDirection: "row", gap: 9, padding: 14, borderRadius: 18, backgroundColor: "#F5F8F3", borderWidth: 1, borderColor: "#D5E3D3" }, noticeText: { flex: 1, color: "#52705E", fontSize: 11, lineHeight: 16, fontWeight: "600" },
});
