import { router } from "expo-router";
import { Pressable, ScrollView, StyleSheet, View } from "react-native";
import { LocalizedText as Text } from "@/components/localized-text";

import { IconSymbol } from "@/components/ui/icon-symbol";
import { ScreenContainer } from "@/components/screen-container";
import { getCuisineProfile } from "@/lib/cuisine-locale";
import { useLezzet } from "@/lib/lezzet-context";
import { dietaryOptions, type DietaryPreference } from "@/lib/seasonal-market";

const copy = {
  "tr-TR": { back: "Profil", kicker: "KİŞİSEL FİLTRE", title: "Beslenme tercihin", subtitle: "Bu filtreler Keşfet, haftalık plan ve bölgesel önerilerde uygun tarifleri öne çıkarır.", selected: "SEÇİLİ", guidance: "Birden fazla filtre seçtiğinde LezzetAI tüm koşulları sağlayan tarifleri gösterir.", clear: "Filtreleri temizle", done: "Tercihleri kaydet" },
  "en-GB": { back: "Profile", kicker: "PERSONAL FILTER", title: "Your dietary preferences", subtitle: "These filters shape Discover, weekly plans and regional recommendations.", selected: "SELECTED", guidance: "When you choose more than one filter, LezzetAI shows recipes that meet every condition.", clear: "Clear filters", done: "Save preferences" },
  "de-DE": { back: "Profil", kicker: "PERSÖNLICHER FILTER", title: "Deine Ernährungspräferenzen", subtitle: "Diese Filter steuern Entdecken, Wochenplan und regionale Empfehlungen.", selected: "AUSGEWÄHLT", guidance: "Bei mehreren Filtern zeigt LezzetAI nur Rezepte, die alle Bedingungen erfüllen.", clear: "Filter löschen", done: "Präferenzen speichern" },
  "es-ES": { back: "Perfil", kicker: "FILTRO PERSONAL", title: "Tus preferencias alimentarias", subtitle: "Estos filtros ajustan Descubrir, el plan semanal y las recomendaciones regionales.", selected: "SELECCIONADO", guidance: "Con varios filtros, LezzetAI muestra recetas que cumplen todas las condiciones.", clear: "Borrar filtros", done: "Guardar preferencias" },
  "fr-FR": { back: "Profil", kicker: "FILTRE PERSONNEL", title: "Vos préférences alimentaires", subtitle: "Ces filtres ajustent Découvrir, le menu hebdomadaire et les recommandations régionales.", selected: "SÉLECTIONNÉ", guidance: "Avec plusieurs filtres, LezzetAI affiche les recettes qui respectent toutes les conditions.", clear: "Effacer les filtres", done: "Enregistrer les préférences" },
} as const;

export default function DietPreferencesScreen() {
  const { profile, updateProfile } = useLezzet();
  const cuisine = getCuisineProfile(profile.locale);
  const text = copy[profile.locale];
  const toggle = (diet: DietaryPreference) => updateProfile({ dietaryPreferences: profile.dietaryPreferences.includes(diet) ? profile.dietaryPreferences.filter((item) => item !== diet) : [...profile.dietaryPreferences, diet] });
  return <ScreenContainer className="flex-1" containerClassName="bg-background" edges={["top", "bottom", "left", "right"]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><Text style={styles.backChevron}>‹</Text><Text style={styles.backText}>{text.back}</Text></Pressable>
    <View style={styles.hero}><View style={styles.icon}><IconSymbol name="leaf.fill" size={21} color="#FFFFFF" /></View><Text style={styles.kicker}>{text.kicker}</Text><Text style={styles.title}>{text.title}</Text><Text style={styles.subtitle}>{text.subtitle}</Text></View>
    <View style={styles.options}>{dietaryOptions.map((item) => { const active = profile.dietaryPreferences.includes(item.id); return <Pressable key={item.id} onPress={() => toggle(item.id)} style={({ pressed }) => [styles.option, active && styles.optionActive, pressed && styles.pressed]}><View style={[styles.optionIcon, active && styles.optionIconActive]}><IconSymbol name={item.id === "gluten-free" ? "checkmark.circle.fill" : "leaf.fill"} size={18} color={active ? "#FFFFFF" : "#1E4D3A"} /></View><View style={{ flex: 1 }}><Text style={[styles.optionTitle, active && styles.optionTitleActive]}>{item.labels[profile.locale]}</Text><Text style={[styles.optionSub, active && styles.optionSubActive]}>{active ? text.selected : cuisine.region}</Text></View>{active ? <IconSymbol name="checkmark.circle.fill" size={21} color="#FFFFFF" /> : <View style={styles.radio} />}</Pressable>; })}</View>
    <View style={styles.guidance}><IconSymbol name="sparkles" size={17} color="#1E4D3A" /><Text style={styles.guidanceText}>{text.guidance}</Text></View>
    <Pressable onPress={() => updateProfile({ dietaryPreferences: [] })} style={({ pressed }) => [styles.clear, pressed && styles.pressed]}><Text style={styles.clearText}>{text.clear}</Text></Pressable>
    <Pressable onPress={() => router.back()} style={({ pressed }) => [styles.done, pressed && styles.pressed]}><Text style={styles.doneText}>{text.done}</Text><IconSymbol name="checkmark.circle.fill" size={18} color="#FFFFFF" /></Pressable>
  </ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 38, gap: 16 }, back: { alignSelf: "flex-start", minHeight: 38, flexDirection: "row", alignItems: "center", gap: 5, paddingHorizontal: 11, borderRadius: 13, backgroundColor: "#E8F0E5" }, backChevron: { color: "#1E4D3A", fontSize: 28, lineHeight: 28 }, backText: { color: "#1E4D3A", fontSize: 12, fontWeight: "900" }, hero: { gap: 7, marginTop: 8 }, icon: { width: 44, height: 44, borderRadius: 15, alignItems: "center", justifyContent: "center", backgroundColor: "#1E4D3A" }, kicker: { color: "#6B756F", fontSize: 10, letterSpacing: 1.1, fontWeight: "900", marginTop: 4 }, title: { color: "#1E2521", fontSize: 30, lineHeight: 36, letterSpacing: -0.9, fontWeight: "900" }, subtitle: { color: "#5C6B61", fontSize: 13, lineHeight: 19, fontWeight: "600" }, options: { gap: 10, marginTop: 4 }, option: { minHeight: 75, flexDirection: "row", alignItems: "center", gap: 11, padding: 14, borderRadius: 21, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EAE7E0" }, optionActive: { backgroundColor: "#1E4D3A", borderColor: "#1E4D3A" }, optionIcon: { width: 36, height: 36, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "#E8F0E5" }, optionIconActive: { backgroundColor: "#34684F" }, optionTitle: { color: "#1E2521", fontSize: 15, fontWeight: "900" }, optionTitleActive: { color: "#FFFFFF" }, optionSub: { color: "#6B756F", fontSize: 10, fontWeight: "800", marginTop: 3 }, optionSubActive: { color: "#B6D7C1" }, radio: { width: 20, height: 20, borderRadius: 10, borderWidth: 2, borderColor: "#B4C0B7" }, guidance: { flexDirection: "row", gap: 9, padding: 14, borderRadius: 18, backgroundColor: "#F5F8F3", borderWidth: 1, borderColor: "#D5E3D3" }, guidanceText: { flex: 1, color: "#52705E", fontSize: 11, lineHeight: 16, fontWeight: "600" }, clear: { minHeight: 40, alignItems: "center", justifyContent: "center" }, clearText: { color: "#6B756F", fontSize: 12, fontWeight: "900" }, done: { minHeight: 52, borderRadius: 17, backgroundColor: "#1E4D3A", flexDirection: "row", gap: 8, alignItems: "center", justifyContent: "center" }, doneText: { color: "#FFFFFF", fontSize: 14, fontWeight: "900" }, pressed: { opacity: 0.72, transform: [{ scale: 0.985 }] } });
