import { Image, Pressable, ScrollView, StyleSheet, View } from "react-native";
import { LocalizedText as Text } from "@/components/localized-text";
import { router } from "expo-router";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { ScreenContainer } from "@/components/screen-container";
import { getRecipe } from "@/lib/lezzet-data";
import { useLezzet } from "@/lib/lezzet-context";

export default function JournalScreen() {
  const { journalEntries } = useLezzet();
  return <ScreenContainer className="flex-1" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.top}><Pressable onPress={() => router.back()} style={styles.back}><IconSymbol name="chevron.left" size={22} color="#1E4D3A" /></Pressable><View><Text style={styles.eyebrow}>MUTFAK GÜNLÜĞÜ</Text><Text style={styles.title}>Pişirdiklerin</Text></View></View><View style={styles.coach}><IconSymbol name="sparkles" size={22} color="#1E4D3A" /><View style={{ flex: 1 }}><Text style={styles.coachTitle}>Bu hafta ritmini koru</Text><Text style={styles.coachText}>{journalEntries.length ? `${journalEntries.length} tarifi kaydettin. Beğendiklerin bir sonraki planında daha sık önerilecek.` : "Bir tarifi pişirdiğinde günlüğe ekle; önerilerin damak zevkini öğrenmeye başlasın."}</Text></View></View>{journalEntries.length ? <View style={styles.list}>{journalEntries.map((entry) => { const recipe = getRecipe(entry.recipeId); return <Pressable key={entry.id} onPress={() => router.push(`/recipe/${recipe.id}` as never)} style={styles.entry}>{entry.photoUri ? <Image source={{ uri: entry.photoUri }} style={styles.entryPhoto} /> : <View style={styles.entryIcon}><IconSymbol name="checkmark.circle.fill" size={20} color="#2D7A55" /></View>}<View style={{ flex: 1 }}><Text style={styles.entryTitle}>{recipe.title}</Text><Text style={styles.entryNote}>{entry.note}</Text><Text style={styles.entryDate}>{entry.createdAt}</Text></View><IconSymbol name="chevron.right" size={18} color="#1E4D3A" /></Pressable>; })}</View> : <View style={styles.empty}><IconSymbol name="calendar" size={30} color="#1E4D3A" /><Text style={styles.emptyTitle}>Henüz kayıt yok</Text><Text style={styles.emptyText}>Tarif ayrıntısından “Pişirdim, günlüğe ekle” seçeneğini kullanabilirsin.</Text></View>}</ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { padding: 20, gap: 18, paddingBottom: 34 }, top: { flexDirection: "row", alignItems: "center", gap: 11 }, back: { width: 41, height: 41, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: "#DDE8DA" }, eyebrow: { color: "#6B756F", fontSize: 10, fontWeight: "900", letterSpacing: 1 }, title: { color: "#1E2521", fontSize: 25, fontWeight: "800", marginTop: 2 }, coach: { flexDirection: "row", gap: 11, padding: 15, borderRadius: 20, backgroundColor: "#DDE8DA" }, coachTitle: { color: "#1E2521", fontSize: 14, fontWeight: "800" }, coachText: { color: "#52705E", fontSize: 12, lineHeight: 17, marginTop: 2 }, list: { gap: 10 }, entry: { flexDirection: "row", alignItems: "center", gap: 11, padding: 14, borderRadius: 19, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EAE7E0" }, entryIcon: { width: 37, height: 37, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: "#F5F8F3" }, entryPhoto: { width: 43, height: 43, borderRadius: 12 }, entryTitle: { color: "#1E2521", fontSize: 14, fontWeight: "800" }, entryNote: { color: "#6B756F", fontSize: 11, lineHeight: 16, marginTop: 2 }, entryDate: { color: "#1E4D3A", fontSize: 10, fontWeight: "800", marginTop: 4 }, empty: { alignItems: "center", gap: 9, padding: 32, borderRadius: 22, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EAE7E0" }, emptyTitle: { color: "#1E2521", fontSize: 16, fontWeight: "800" }, emptyText: { maxWidth: 260, color: "#6B756F", fontSize: 12, lineHeight: 18, textAlign: "center" } });
