import { Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { useState } from "react";
import * as ImagePicker from "expo-image-picker";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { ScreenContainer } from "@/components/screen-container";
import { getRecipe } from "@/lib/lezzet-data";
import { useLezzet } from "@/lib/lezzet-context";

export default function JournalEntryScreen() { const params = useLocalSearchParams<{ recipeId?: string }>(); const recipe = getRecipe(params.recipeId); const { addJournalEntry } = useLezzet(); const [note, setNote] = useState(""); const [photoUri, setPhotoUri] = useState<string | undefined>(); const selectPhoto = async () => { const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ImagePicker.MediaTypeOptions.Images, allowsEditing: true, aspect: [4, 3], quality: 0.6 }); if (!result.canceled) setPhotoUri(result.assets[0].uri); }; return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="flex-1" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><View style={styles.top}><Pressable onPress={() => router.back()} style={styles.back}><IconSymbol name="chevron.left" size={22} color="#1E4D3A" /></Pressable><View><Text style={styles.eyebrow}>MUTFAK GÜNLÜĞÜ</Text><Text style={styles.title}>Deneyimini kaydet</Text></View></View><View style={styles.recipe}><Text style={styles.recipeLabel}>PİŞİRDİĞİN TARİF</Text><Text style={styles.recipeName}>{recipe.title}</Text></View><Pressable onPress={selectPhoto} style={({ pressed }) => [styles.photoSlot, pressed && { opacity: 0.72 }]}>{photoUri ? <Image source={{ uri: photoUri }} style={styles.photo} /> : <><IconSymbol name="camera.fill" size={25} color="#1E4D3A" /><Text style={styles.photoTitle}>Fotoğraf ekle</Text><Text style={styles.photoText}>Sofranı veya sonucu hatırla.</Text></>}</Pressable><TextInput value={note} onChangeText={setNote} multiline textAlignVertical="top" placeholder="Nasıl oldu? Bir dahaki sefere neyi değiştirirsin?" placeholderTextColor="#87918B" style={styles.input} /><Pressable onPress={() => { addJournalEntry(recipe.id, note, photoUri); router.replace("/journal" as never); }} style={styles.save}><Text style={styles.saveText}>Günlüğe kaydet</Text><IconSymbol name="checkmark.circle.fill" size={18} color="#FFFFFF" /></Pressable></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { padding: 20, gap: 17 }, top: { flexDirection: "row", alignItems: "center", gap: 11 }, back: { width: 41, height: 41, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: "#DDE8DA" }, eyebrow: { color: "#6B756F", fontSize: 10, fontWeight: "900", letterSpacing: 1 }, title: { color: "#1E2521", fontSize: 24, fontWeight: "800", marginTop: 2 }, recipe: { padding: 14, borderRadius: 18, backgroundColor: "#F5F8F3" }, recipeLabel: { color: "#6B756F", fontSize: 10, fontWeight: "900", letterSpacing: 0.7 }, recipeName: { color: "#1E2521", fontSize: 16, fontWeight: "800", marginTop: 3 }, photoSlot: { minHeight: 180, borderRadius: 22, backgroundColor: "#DDE8DA", borderWidth: 1, borderColor: "#C9DCC4", alignItems: "center", justifyContent: "center", gap: 6, overflow: "hidden" }, photo: { width: "100%", height: "100%", position: "absolute" }, photoTitle: { color: "#1E4D3A", fontSize: 14, fontWeight: "800" }, photoText: { color: "#52705E", fontSize: 11 }, input: { minHeight: 130, borderRadius: 20, padding: 14, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EAE7E0", color: "#1E2521", fontSize: 14, lineHeight: 20 }, save: { minHeight: 51, borderRadius: 16, backgroundColor: "#1E4D3A", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 }, saveText: { color: "#FFFFFF", fontSize: 14, fontWeight: "800" } });
