import { Alert, Platform, Pressable, ScrollView, StyleSheet, TextInput, View } from "react-native";
import { LocalizedText as Text } from "@/components/localized-text";
import { router } from "expo-router";
import { useMemo, useState } from "react";

import { IconSymbol } from "@/components/ui/icon-symbol";
import { ScreenContainer } from "@/components/screen-container";
import { VoiceInputButton } from "@/components/voice-input-button";
import { getRecipesForPreferences } from "@/lib/lezzet-data";
import { useLezzet } from "@/lib/lezzet-context";
import { enableExpiryNotifications } from "@/lib/expiry-notifications";
import { getEffectiveExpiryDays, getExpiringPantryItems, getPantryOverview, getRecipePantryMatches, type StockUnit } from "@/lib/pantry-insights";

const units: StockUnit[] = ["adet", "g", "ml", "paket"];

export default function PantryScreen() {
  const { pantry, pantryMeta, profile, addPantryItem, removePantryItem, toggleFavoriteIngredient, setExpiryDate, setExpiryPriority, updatePantryStock } = useLezzet();
  const [name, setName] = useState("");
  const [quantity, setQuantity] = useState("1");
  const [unit, setUnit] = useState<StockUnit>("adet");
  const [expiryDate, setExpiryDateDraft] = useState("");
  const [notificationMessage, setNotificationMessage] = useState<string | null>(null);
  const localRecipes = useMemo(() => getRecipesForPreferences(profile.locale, profile.dietaryPreferences), [profile.dietaryPreferences, profile.locale]);
  const overview = useMemo(() => getPantryOverview(localRecipes, pantry, pantryMeta, profile.people), [localRecipes, pantry, pantryMeta, profile.people]);
  const expiringItems = useMemo(() => getExpiringPantryItems(pantry, pantryMeta, 3), [pantry, pantryMeta]);
  const ideas = useMemo(() => localRecipes.map((recipe) => { const matches = getRecipePantryMatches(recipe, pantry).matched; return { recipe, score: matches.length + matches.filter((item) => expiringItems.includes(item)).length * 4 }; }).filter((item) => item.score >= 2).sort((a, b) => b.score - a.score).slice(0, 3), [expiringItems, localRecipes, pantry]);

  const addItem = () => {
    const cleanName = name.trim();
    const parsedQuantity = Number(quantity.replace(",", "."));
    if (!cleanName) { Alert.alert("Malzeme ekle", "Kilerindeki malzemenin adını yaz."); return; }
    if (!Number.isFinite(parsedQuantity) || parsedQuantity <= 0) { Alert.alert("Miktarı kontrol et", "Sıfırdan büyük bir adet, gram, mililitre veya paket miktarı yaz."); return; }
    addPantryItem(cleanName);
    updatePantryStock(cleanName, { quantity: Math.round(parsedQuantity), unit });
    if (expiryDate) {
      if (!/^\d{4}-\d{2}-\d{2}$/.test(expiryDate)) { Alert.alert("Tarihi kontrol et", "Son kullanma tarihini YYYY-AA-GG biçiminde gir."); return; }
      setExpiryDate(cleanName, expiryDate);
    }
    setName(""); setQuantity("1"); setUnit("adet"); setExpiryDateDraft("");
  };

  const adjustStock = (item: string, direction: -1 | 1) => {
    const meta = pantryMeta[item];
    const step = meta?.unit === "g" || meta?.unit === "ml" ? 50 : 1;
    updatePantryStock(item, { quantity: Math.max(0, (meta?.quantity ?? 0) + direction * step) });
  };

  const enableNotifications = async () => {
    const result = await enableExpiryNotifications(
      pantry.map((item) => ({ name: item, expiresInDays: getEffectiveExpiryDays(pantryMeta[item]) })),
      overview.lowStock.map((item) => ({ name: item, quantity: pantryMeta[item]?.quantity ?? 0, unit: pantryMeta[item]?.unit ?? "adet", frequent: overview.frequentLowStock.includes(item) })),
    );
    if (result.status === "granted") setNotificationMessage(result.count ? `${result.count} kiler uyarısı planlandı.` : "Şu an için uyarı gerektiren kiler ürünü yok.");
    else if (result.status === "denied") setNotificationMessage("Bildirim izni verilmedi. Cihaz ayarlarından daha sonra açabilirsin.");
    else setNotificationMessage("Cihaz bildirimleri web önizlemesinde desteklenmez.");
  };

  return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="flex-1" containerClassName="bg-background"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
    <View style={styles.header}><View style={styles.headerMark}><IconSymbol name="cabinet.fill" size={22} color="#FFFFFF" /></View><View style={{ flex: 1 }}><Text style={styles.eyebrow}>MUTFAK ENVANTERİ</Text><Text style={styles.title}>Kilerim</Text><Text style={styles.subtitle}>Elindekileri takip et, israfı azalt, ne pişirebileceğini gör.</Text></View><View style={styles.count}><Text style={styles.countText}>{pantry.length}</Text><Text style={styles.countLabel}>ürün</Text></View></View>

    <View style={styles.insights}><Insight value={String(overview.cookableRecipeCount)} label="Yapılabilir tarif" icon="sparkles" /><Insight value={String(overview.estimatedMeals)} label="Tahmini öğün" icon="calendar" /><Insight value={`${overview.estimatedDays}`} label="Yaklaşık gün" icon="clock" /></View>
    <Text style={styles.insightHint}>Sayaçlar seçtiğin {profile.people} kişilik plan, kayıtlı miktarlar ve kiler eşleşmelerine göre yaklaşık hesaplanır.</Text>

    <View style={styles.addBox}><View style={styles.addHeader}><View><Text style={styles.addTitle}>Kilerine ekle</Text><Text style={styles.addHint}>Adını, miktarını ve istersen etiketteki tarihi ekle.</Text></View><View style={styles.scanActions}><Pressable onPress={() => router.push("/scan-ingredients" as never)} style={({ pressed }) => [styles.scanButton, pressed && { opacity: 0.7 }]}><IconSymbol name="camera.fill" size={18} color="#1E4D3A" /><Text style={styles.scanButtonText}>Ürün</Text></Pressable><Pressable onPress={() => router.push("/scan-receipt" as never)} style={({ pressed }) => [styles.scanButton, pressed && { opacity: 0.7 }]}><IconSymbol name="doc.text.viewfinder" size={18} color="#1E4D3A" /><Text style={styles.scanButtonText}>Fiş</Text></Pressable></View></View><View style={styles.nameRow}><TextInput value={name} onChangeText={setName} onSubmitEditing={addItem} placeholder="Örn. mercimek, yoğurt, domates" placeholderTextColor="#87918B" returnKeyType="done" style={styles.nameInput} /><VoiceInputButton onText={setName} label="Kiler ürününü sesle yaz" /></View><View style={styles.quantityRow}><TextInput value={quantity} onChangeText={setQuantity} keyboardType="decimal-pad" placeholder="Miktar" placeholderTextColor="#87918B" style={[styles.input, styles.quantityInput]} />{units.map((item) => <Pressable key={item} onPress={() => setUnit(item)} style={({ pressed }) => [styles.unit, unit === item && styles.unitActive, pressed && { opacity: 0.7 }]}><Text style={[styles.unitText, unit === item && styles.unitTextActive]}>{item}</Text></Pressable>)}<Pressable onPress={addItem} style={({ pressed }) => [styles.addButton, pressed && { opacity: 0.8 }]}><IconSymbol name="plus" size={21} color="#FFFFFF" /></Pressable></View><TextInput value={expiryDate} onChangeText={setExpiryDateDraft} placeholder="Son kullanma: YYYY-AA-GG (isteğe bağlı)" placeholderTextColor="#87918B" style={styles.dateInput} /></View>

    {overview.lowStock.length ? <View style={styles.alertCard}><View style={styles.alertIcon}><IconSymbol name="exclamationmark.triangle.fill" size={20} color="#B7652E" /></View><View style={{ flex: 1 }}><Text style={styles.alertTitle}>Düşük stokta ürünler</Text><Text style={styles.alertText}>{overview.lowStock.join(" · ")}{overview.frequentLowStock.length ? " · Sık kullandıkların için yenileme zamanı yaklaşıyor." : ""}</Text></View></View> : null}
    <Pressable onPress={() => router.push("/smart-shopping" as never)} style={({ pressed }) => [styles.smartShopping, pressed && { opacity: 0.75 }]}><View style={styles.smartShoppingIcon}><IconSymbol name="cart.fill" size={18} color="#1E4D3A" /></View><View style={{ flex: 1 }}><Text style={styles.smartShoppingTitle}>Akıllı alışveriş listesi</Text><Text style={styles.smartShoppingText}>Azalan ürünleri otomatik listele ve tek dokunuşla paylaş.</Text></View><IconSymbol name="chevron.right" size={18} color="#1E4D3A" /></Pressable>

    <View><View style={styles.sectionHead}><Text style={styles.sectionTitle}>Kilerindeki malzemeler</Text><Text style={styles.sectionCount}>{pantry.length} kayıt</Text></View><View style={styles.stockList}>{pantry.map((item) => { const meta = pantryMeta[item]; const low = (meta?.quantity ?? 0) <= (meta?.lowStockThreshold ?? 1); const frequent = (meta?.uses ?? 0) >= 3; return <View key={item} style={[styles.stockItem, low && styles.stockItemLow]}><View style={[styles.stockMark, low && styles.stockMarkLow]}><IconSymbol name={low ? "exclamationmark.triangle.fill" : "leaf.fill"} size={17} color={low ? "#B7652E" : "#1E4D3A"} /></View><View style={{ flex: 1 }}><View style={styles.stockNameRow}><Text style={styles.stockName}>{item}</Text>{frequent ? <Text style={styles.frequent}>sık kullanılıyor</Text> : null}</View><Text style={styles.stockMeta}>{meta?.quantity ?? 0} {meta?.unit ?? "adet"} · eşik {meta?.lowStockThreshold ?? 1} · {meta?.expiresInDays ?? 5} gün</Text></View><View style={styles.stockControls}><Pressable onPress={() => adjustStock(item, -1)} style={({ pressed }) => [styles.stockControl, pressed && { opacity: 0.6 }]}><Text style={styles.stockControlText}>−</Text></Pressable><Pressable onPress={() => adjustStock(item, 1)} style={({ pressed }) => [styles.stockControl, pressed && { opacity: 0.6 }]}><Text style={styles.stockControlText}>+</Text></Pressable><Pressable onPress={() => toggleFavoriteIngredient(item)} hitSlop={7}><IconSymbol name={meta?.favorite ? "heart.fill" : "heart"} size={18} color={meta?.favorite ? "#D4553E" : "#6B756F"} /></Pressable><Pressable onPress={() => removePantryItem(item)} hitSlop={7}><IconSymbol name="xmark" size={16} color="#6B756F" /></Pressable></View></View>; })}</View></View>

    <View style={styles.notificationCard}><View style={styles.notificationTop}><View style={styles.notificationIcon}><IconSymbol name="bell.fill" size={19} color="#1E4D3A" /></View><View style={{ flex: 1 }}><Text style={styles.notificationTitle}>Kiler uyarıları</Text><Text style={styles.notificationText}>Düşük stok, sık kullandığın ürün ve yaklaşan son kullanma için hatırlatma al.</Text></View></View><Pressable onPress={enableNotifications} style={({ pressed }) => [styles.notificationCta, pressed && { opacity: 0.8 }]}><Text style={styles.notificationCtaText}>{Platform.OS === "web" ? "Bildirim durumunu gör" : "Kiler uyarılarını aç"}</Text><IconSymbol name="chevron.right" size={17} color="#1E4D3A" /></Pressable>{notificationMessage ? <Text style={styles.notificationResult}>{notificationMessage}</Text> : null}</View>

    <View><View style={styles.sectionHead}><Text style={styles.sectionTitle}>Önce bunları değerlendir</Text><Pressable onPress={() => router.push({ pathname: "/(tabs)/chef", params: { prompt: `Son kullanma tarihi yaklaşan ${expiringItems.join(", ") || "kilerimdeki öncelikli ürünleri"} kullanarak israfı azaltan ayrıntılı bir tarif istiyorum.`, pantryOnly: "true" } } as never)}><Text style={styles.aiLink}>İsraf önleyici AI tarif</Text></Pressable></View><View style={styles.expiryList}>{expiringItems.slice(0, 4).map((item) => { const days = getEffectiveExpiryDays(pantryMeta[item]); return <View key={item} style={styles.expiryItem}><View style={styles.expiryDot}><IconSymbol name="clock" size={16} color="#B7652E" /></View><View style={{ flex: 1 }}><Text style={styles.expiryName}>{item}</Text><Text style={styles.expiryText}>{days <= 1 ? "Bugün değerlendirmek iyi olur" : `${days} gün içinde kullan`}{pantryMeta[item]?.expiresOn ? ` · ${pantryMeta[item].expiresOn}` : ""}</Text></View><Pressable onPress={() => setExpiryPriority(item, Math.max(1, days - 1))} style={({ pressed }) => [styles.priorityButton, pressed && { opacity: 0.7 }]}><Text style={styles.priorityText}>Öne al</Text></Pressable></View>; })}</View><Text style={styles.safetyHint}>Tarih etiketteki bilgidir; saklama koşulunu ve üründeki bozulma işaretlerini ayrıca kontrol et.</Text></View>

    <View><View style={styles.sectionHead}><Text style={styles.sectionTitle}>Kilerinden çıkan tarifler</Text><Pressable onPress={() => router.push({ pathname: "/(tabs)/chef", params: { prompt: "Yalnızca kilerimdeki malzemelerle ayrıntılı bir tarif istiyorum.", pantryOnly: "true" } } as never)}><Text style={styles.aiLink}>AI Şef’e sor</Text></Pressable></View><View style={styles.ideaList}>{ideas.map(({ recipe, score }) => <Pressable key={recipe.id} onPress={() => router.push(`/recipe/${recipe.id}` as never)} style={({ pressed }) => [styles.idea, pressed && { opacity: 0.7 }]}><View style={styles.ideaIcon}><IconSymbol name="sparkles" size={17} color="#1E4D3A" /></View><View style={{ flex: 1 }}><Text style={styles.ideaTitle}>{recipe.title}</Text><Text style={styles.ideaText}>{score} kiler malzemesi eşleşiyor · {recipe.minutes} dk</Text></View><IconSymbol name="chevron.right" size={18} color="#1E4D3A" /></Pressable>)}</View></View>
  </ScrollView></ScreenContainer>;
}

function Insight({ value, label, icon }: { value: string; label: string; icon: "sparkles" | "calendar" | "clock" }) { return <View style={styles.insight}><View style={styles.insightIcon}><IconSymbol name={icon} size={16} color="#1E4D3A" /></View><Text style={styles.insightValue}>{value}</Text><Text style={styles.insightLabel}>{label}</Text></View>; }

const styles = StyleSheet.create({
  content: { padding: 20, paddingBottom: 36, gap: 18 }, header: { flexDirection: "row", alignItems: "flex-start", gap: 11 }, headerMark: { width: 44, height: 44, borderRadius: 15, alignItems: "center", justifyContent: "center", backgroundColor: "#1E4D3A" }, eyebrow: { color: "#6B756F", fontSize: 10, fontWeight: "900", letterSpacing: 1 }, title: { color: "#1E2521", fontSize: 27, lineHeight: 32, fontWeight: "900", letterSpacing: -0.6, marginTop: 2 }, subtitle: { color: "#6B756F", fontSize: 11, lineHeight: 16, marginTop: 2 }, count: { alignItems: "center", padding: 8, minWidth: 42, borderRadius: 14, backgroundColor: "#DDE8DA" }, countText: { color: "#1E4D3A", fontSize: 15, fontWeight: "900" }, countLabel: { color: "#52705E", fontSize: 8, fontWeight: "800" },
  insights: { flexDirection: "row", gap: 8 }, insight: { flex: 1, minHeight: 96, padding: 11, borderRadius: 18, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EAE7E0", justifyContent: "space-between" }, insightIcon: { width: 28, height: 28, borderRadius: 10, alignItems: "center", justifyContent: "center", backgroundColor: "#DDE8DA" }, insightValue: { color: "#1E4D3A", fontSize: 20, fontWeight: "900", marginTop: 7 }, insightLabel: { color: "#6B756F", fontSize: 9, lineHeight: 12, fontWeight: "800" }, insightHint: { color: "#6B756F", fontSize: 10, lineHeight: 15, marginTop: -10 },
  addBox: { backgroundColor: "#FFFFFF", borderRadius: 22, borderWidth: 1, borderColor: "#EAE7E0", padding: 14, gap: 10 }, addHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 }, addTitle: { color: "#1E2521", fontSize: 15, fontWeight: "900" }, addHint: { color: "#6B756F", fontSize: 10, marginTop: 2 }, scanActions: { flexDirection: "row", gap: 5 }, scanButton: { minHeight: 34, flexDirection: "row", alignItems: "center", gap: 4, paddingHorizontal: 8, borderRadius: 11, backgroundColor: "#DDE8DA" }, scanButtonText: { color: "#1E4D3A", fontSize: 10, fontWeight: "900" }, nameRow: { flexDirection: "row", alignItems: "center", gap: 7 }, nameInput: { flex: 1, height: 44, borderRadius: 13, backgroundColor: "#F5F8F3", paddingHorizontal: 12, fontSize: 13, color: "#1E2521" }, input: { height: 44, borderRadius: 13, backgroundColor: "#F5F8F3", paddingHorizontal: 12, fontSize: 13, color: "#1E2521" }, dateInput: { height: 40, borderRadius: 13, backgroundColor: "#FFF8EF", paddingHorizontal: 12, fontSize: 12, color: "#1E2521", borderWidth: 1, borderColor: "#F2D4B9" }, quantityRow: { flexDirection: "row", alignItems: "center", gap: 6 }, quantityInput: { width: 72 }, unit: { minHeight: 38, paddingHorizontal: 8, justifyContent: "center", borderRadius: 11, backgroundColor: "#F5F8F3" }, unitActive: { backgroundColor: "#1E4D3A" }, unitText: { color: "#52705E", fontSize: 10, fontWeight: "800" }, unitTextActive: { color: "#FFFFFF" }, addButton: { width: 40, height: 40, borderRadius: 12, backgroundColor: "#B7652E", alignItems: "center", justifyContent: "center", marginLeft: "auto" },
  alertCard: { flexDirection: "row", gap: 10, padding: 14, borderRadius: 19, backgroundColor: "#FFF1E4", borderWidth: 1, borderColor: "#F2D4B9" }, alertIcon: { width: 34, height: 34, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: "#FFFFFF" }, alertTitle: { color: "#754626", fontSize: 13, fontWeight: "900" }, alertText: { color: "#9A6138", fontSize: 11, lineHeight: 16, marginTop: 2 },
  smartShopping: { minHeight: 66, flexDirection: "row", alignItems: "center", gap: 10, padding: 12, borderRadius: 19, backgroundColor: "#E8F1E7", borderWidth: 1, borderColor: "#C9DCC4" }, smartShoppingIcon: { width: 35, height: 35, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: "#FFFFFF" }, smartShoppingTitle: { color: "#1E4D3A", fontSize: 13, fontWeight: "900" }, smartShoppingText: { color: "#52705E", fontSize: 10, lineHeight: 15, marginTop: 2 },
  sectionHead: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 10 }, sectionTitle: { color: "#1E2521", fontSize: 17, fontWeight: "900" }, sectionCount: { color: "#6B756F", fontSize: 10, fontWeight: "800" }, stockList: { gap: 8 }, stockItem: { minHeight: 76, flexDirection: "row", alignItems: "center", gap: 10, padding: 10, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EAE7E0", borderRadius: 18 }, stockItemLow: { borderColor: "#F2D4B9", backgroundColor: "#FFFDFC" }, stockMark: { width: 34, height: 34, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: "#DDE8DA" }, stockMarkLow: { backgroundColor: "#FCE6D2" }, stockNameRow: { flexDirection: "row", alignItems: "center", gap: 6 }, stockName: { color: "#1E2521", fontSize: 13, fontWeight: "900", maxWidth: 120 }, frequent: { color: "#A45F33", fontSize: 8, fontWeight: "900", backgroundColor: "#FCE6D2", paddingHorizontal: 5, paddingVertical: 3, borderRadius: 6 }, stockMeta: { color: "#6B756F", fontSize: 10, marginTop: 3 }, stockControls: { flexDirection: "row", alignItems: "center", gap: 8 }, stockControl: { width: 24, height: 24, borderRadius: 8, alignItems: "center", justifyContent: "center", backgroundColor: "#E8F0E5" }, stockControlText: { color: "#1E4D3A", fontSize: 17, lineHeight: 20, fontWeight: "800" },
  notificationCard: { gap: 10, padding: 14, borderRadius: 20, backgroundColor: "#F5F8F3", borderWidth: 1, borderColor: "#C9DCC4" }, notificationTop: { flexDirection: "row", alignItems: "center", gap: 10 }, notificationIcon: { width: 38, height: 38, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "#DDE8DA" }, notificationTitle: { color: "#1E2521", fontSize: 14, fontWeight: "900" }, notificationText: { color: "#52705E", fontSize: 11, lineHeight: 16, marginTop: 2 }, notificationCta: { minHeight: 38, borderRadius: 12, paddingHorizontal: 11, flexDirection: "row", alignItems: "center", justifyContent: "space-between", backgroundColor: "#FFFFFF" }, notificationCtaText: { color: "#1E4D3A", fontSize: 12, fontWeight: "900" }, notificationResult: { color: "#52705E", fontSize: 11, lineHeight: 16 },
  expiryList: { gap: 8 }, expiryItem: { minHeight: 64, flexDirection: "row", alignItems: "center", gap: 10, padding: 11, borderRadius: 17, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EAE7E0" }, expiryDot: { width: 34, height: 34, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: "#FCE6D2" }, expiryName: { color: "#1E2521", fontSize: 13, fontWeight: "900" }, expiryText: { color: "#6B756F", fontSize: 10, marginTop: 2 }, priorityButton: { paddingHorizontal: 9, paddingVertical: 7, borderRadius: 10, backgroundColor: "#DDE8DA" }, priorityText: { color: "#1E4D3A", fontSize: 10, fontWeight: "900" }, safetyHint: { color: "#9A6138", fontSize: 10, lineHeight: 15, marginTop: 7 },
  aiLink: { color: "#1E4D3A", fontSize: 11, fontWeight: "900" }, ideaList: { gap: 9 }, idea: { minHeight: 68, flexDirection: "row", alignItems: "center", gap: 11, backgroundColor: "#FFFFFF", borderRadius: 18, borderWidth: 1, borderColor: "#EAE7E0", paddingHorizontal: 13 }, ideaIcon: { width: 36, height: 36, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: "#DDE8DA" }, ideaTitle: { color: "#1E2521", fontSize: 13, fontWeight: "900" }, ideaText: { color: "#6B756F", fontSize: 11, marginTop: 2 },
});
