import { Alert, Pressable, ScrollView, StyleSheet, TextInput, View } from "react-native";
import { router } from "expo-router";
import { useState } from "react";

import { IconSymbol } from "@/components/ui/icon-symbol";
import { LocalizedText as Text } from "@/components/localized-text";
import { ScreenContainer } from "@/components/screen-container";
import { useLezzet } from "@/lib/lezzet-context";

export default function PantryTemplatesScreen() {
  const { pantry, pantryTemplates, savePantryTemplate, loadPantryTemplate, removePantryTemplate } = useLezzet();
  const [name, setName] = useState("");
  const save = () => { if (!savePantryTemplate(name)) { Alert.alert("Şablon kaydedilemedi", "Kilerinde en az bir ürün olmalı ve şablona bir ad vermelisin."); return; } setName(""); Alert.alert("Şablon kaydedildi", "Kilerindeki ürünler ve miktarları daha sonra kullanman için kaydedildi."); };
  const load = (id: string, templateName: string) => Alert.alert("Şablonu yükle", `“${templateName}” mevcut kilerinin yerine geçer ve haftalık planını yeniler.`, [{ text: "Vazgeç", style: "cancel" }, { text: "Yükle", onPress: () => { if (loadPantryTemplate(id)) router.back(); } }]);
  const remove = (id: string, templateName: string) => Alert.alert("Şablonu kaldır", `“${templateName}” şablonunu silmek istediğine emin misin? Kilerindeki mevcut ürünler etkilenmez.`, [{ text: "Vazgeç", style: "cancel" }, { text: "Sil", style: "destructive", onPress: () => removePantryTemplate(id) }]);
  return <ScreenContainer className="flex-1" containerClassName="bg-background"><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}>
    <Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && { opacity: 0.7 }]}><IconSymbol name="chevron.left" size={18} color="#1E4D3A" /><Text style={styles.backText}>Profil</Text></Pressable>
    <View style={styles.heroIcon}><IconSymbol name="cabinet.fill" size={25} color="#F4A261" /></View><Text style={styles.title}>Kiler şablonların</Text><Text style={styles.subtitle}>Kendi ürünlerini ve miktarlarını adlandırarak sakla; sonra tek dokunuşla geri yükle.</Text>
    <View style={styles.saveCard}><Text style={styles.saveTitle}>Mevcut kilerini kaydet</Text><Text style={styles.saveText}>{pantry.length ? `${pantry.length} ürün, miktarlarıyla birlikte şablona eklenmeye hazır.` : "Önce kilerine en az bir ürün eklemelisin."}</Text><View style={styles.saveRow}><TextInput value={name} onChangeText={setName} placeholder="Örn. Hafta içi kilerim" placeholderTextColor="#87918B" style={styles.input} returnKeyType="done" onSubmitEditing={save} /><Pressable onPress={save} style={({ pressed }) => [styles.saveButton, pressed && { opacity: 0.75 }]}><Text style={styles.saveButtonText}>Kaydet</Text></Pressable></View></View>
    <View style={styles.templatesHead}><Text style={styles.sectionTitle}>Kaydedilen şablonlar</Text><Text style={styles.count}>{pantryTemplates.length}/12</Text></View>
    {pantryTemplates.length ? <View style={styles.list}>{pantryTemplates.map((template) => <View key={template.id} style={styles.template}><Pressable onPress={() => load(template.id, template.name)} style={({ pressed }) => [styles.templateOpen, pressed && { opacity: 0.72 }]}><View style={styles.templateIcon}><IconSymbol name="cabinet.fill" size={18} color="#1E4D3A" /></View><View style={{ flex: 1 }}><Text style={styles.templateName}>{template.name}</Text><Text style={styles.templateItems}>{template.items.map((item) => `${item.quantity}× ${item.name}`).join(" · ")}</Text></View><IconSymbol name="chevron.right" size={18} color="#1E4D3A" /></Pressable><Pressable onPress={() => remove(template.id, template.name)} style={({ pressed }) => [styles.delete, pressed && { opacity: 0.65 }]}><Text style={styles.deleteText}>Şablonu sil</Text></Pressable></View>)}</View> : <View style={styles.empty}><IconSymbol name="sparkles" size={21} color="#1E4D3A" /><Text style={styles.emptyTitle}>Henüz şablonun yok</Text><Text style={styles.emptyText}>Kilerin hazır olduğunda üstten bir ad vererek ilk şablonunu kaydedebilirsin.</Text></View>}
  </ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 34, gap: 15 }, back: { alignSelf: "flex-start", minHeight: 36, flexDirection: "row", alignItems: "center", gap: 4, paddingRight: 9 }, backText: { color: "#1E4D3A", fontSize: 13, fontWeight: "800" }, heroIcon: { width: 52, height: 52, borderRadius: 18, backgroundColor: "#1E4D3A", alignItems: "center", justifyContent: "center", marginTop: 6 }, title: { color: "#1E2521", fontSize: 27, lineHeight: 33, letterSpacing: -0.7, fontWeight: "900" }, subtitle: { color: "#6B756F", fontSize: 13, lineHeight: 19, marginTop: -6 }, saveCard: { gap: 8, padding: 15, borderRadius: 20, backgroundColor: "#F5F8F3", borderWidth: 1, borderColor: "#C9DCC4" }, saveTitle: { color: "#1E4D3A", fontSize: 14, fontWeight: "900" }, saveText: { color: "#52705E", fontSize: 11, lineHeight: 16 }, saveRow: { flexDirection: "row", gap: 8, marginTop: 2 }, input: { flex: 1, minWidth: 80, height: 42, borderRadius: 12, backgroundColor: "#FFFFFF", paddingHorizontal: 11, color: "#1E2521", fontSize: 12, fontWeight: "700" }, saveButton: { alignItems: "center", justifyContent: "center", paddingHorizontal: 14, borderRadius: 12, backgroundColor: "#1E4D3A" }, saveButtonText: { color: "#FFFFFF", fontSize: 12, fontWeight: "900" }, templatesHead: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 3 }, sectionTitle: { color: "#1E2521", fontSize: 16, fontWeight: "900" }, count: { color: "#52705E", fontSize: 11, fontWeight: "900", backgroundColor: "#DDE8DA", paddingHorizontal: 8, paddingVertical: 4, borderRadius: 9 }, list: { gap: 9 }, template: { gap: 8, padding: 11, borderRadius: 18, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EAE7E0" }, templateOpen: { flexDirection: "row", alignItems: "center", gap: 10 }, templateIcon: { width: 36, height: 36, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: "#DDE8DA" }, templateName: { color: "#1E2521", fontSize: 13, fontWeight: "900" }, templateItems: { color: "#6B756F", fontSize: 10, lineHeight: 15, marginTop: 2 }, delete: { alignSelf: "flex-end", paddingVertical: 2, paddingHorizontal: 4 }, deleteText: { color: "#B54C40", fontSize: 10, fontWeight: "800" }, empty: { alignItems: "center", gap: 7, padding: 22, borderRadius: 20, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EAE7E0" }, emptyTitle: { color: "#1E4D3A", fontSize: 14, fontWeight: "900" }, emptyText: { color: "#6B756F", fontSize: 11, lineHeight: 16, textAlign: "center" } });
