import { Alert, Platform, Pressable, ScrollView, StyleSheet, TextInput, View } from "react-native";
import { LocalizedText as Text } from "@/components/localized-text";
import { router } from "expo-router";
import { useState } from "react";

import { IconSymbol } from "@/components/ui/icon-symbol";
import { ScreenContainer } from "@/components/screen-container";
import { recipes } from "@/lib/lezzet-data";
import { useLezzet } from "@/lib/lezzet-context";
import { enableExpiryNotifications } from "@/lib/expiry-notifications";

export default function PantryScreen() {
  const { pantry, pantryMeta, addPantryItem, removePantryItem, toggleFavoriteIngredient, setExpiryPriority } = useLezzet();
  const [value, setValue] = useState("");
  const [notificationMessage, setNotificationMessage] = useState<string | null>(null);
  const addItem = () => { if (!value.trim()) { Alert.alert("Malzeme ekle", "Kilerindeki malzemenin adını yaz."); return; } addPantryItem(value); setValue(""); };
  const enableNotifications = async () => { const result = await enableExpiryNotifications(pantry.map((name) => ({ name, expiresInDays: pantryMeta[name]?.expiresInDays ?? 5 }))); if (result.status === "granted") setNotificationMessage(result.count ? `${result.count} ürün için tazelik uyarısı planlandı.` : "Şu anda yakın son kullanma tarihi bulunan ürün yok."); else if (result.status === "denied") setNotificationMessage("Bildirim izni verilmedi. Cihaz ayarlarından daha sonra açabilirsin."); else setNotificationMessage("Cihaz bildirimleri web önizlemesinde desteklenmez."); };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="flex-1" containerClassName="bg-background"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
    <View style={styles.header}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && { opacity: 0.55 }]}><IconSymbol name="chevron.left" size={23} color="#1E4D3A" /></Pressable><View style={{ flex: 1 }}><Text style={styles.eyebrow}>ELİNDEKİLER</Text><Text style={styles.title}>Kilerim</Text></View><View style={styles.count}><Text style={styles.countText}>{pantry.length}</Text></View></View>
    <View style={styles.addBox}><Text style={styles.addTitle}>Malzeme ekle</Text><View style={styles.addRow}><TextInput value={value} onChangeText={setValue} onSubmitEditing={addItem} placeholder="Örn. kabak, mercimek" placeholderTextColor="#87918B" returnKeyType="done" style={styles.input} /><Pressable onPress={addItem} style={({ pressed }) => [styles.addButton, pressed && { opacity: 0.8 }]}><IconSymbol name="plus" size={22} color="#FFFFFF" /></Pressable></View><Text style={styles.addHint}>Malzemelerini güncel tut; AI Şef önerilerini sana göre şekillendirsin.</Text></View>
    <View><Text style={styles.sectionTitle}>Kilerindeki malzemeler</Text><View style={styles.chips}>{pantry.map((item) => <View key={item} style={[styles.chip, pantryMeta[item]?.favorite && styles.chipFavorite]}><Pressable onPress={() => toggleFavoriteIngredient(item)} hitSlop={6}><IconSymbol name={pantryMeta[item]?.favorite ? "heart.fill" : "heart"} size={14} color={pantryMeta[item]?.favorite ? "#D4553E" : "#6B756F"} /></Pressable><Text style={styles.chipText}>{item}</Text><Pressable onPress={() => removePantryItem(item)} hitSlop={6}><IconSymbol name="xmark" size={14} color="#6B756F" /></Pressable></View>)}</View></View>
    <View style={styles.tip}><View style={styles.tipIcon}><IconSymbol name="leaf.fill" size={21} color="#1E4D3A" /></View><View style={{ flex: 1 }}><Text style={styles.tipTitle}>Önce bunları değerlendir</Text><Text style={styles.tipText}>{pantry.filter((item) => (pantryMeta[item]?.expiresInDays ?? 5) <= 2).map((item) => item).join(" ve ") || "Kilerindeki ürünleri son kullanma tarihine göre etiketle."}</Text></View></View>
    <View style={styles.notificationCard}><View style={styles.notificationTop}><View style={styles.notificationIcon}><IconSymbol name="bell.fill" size={19} color="#1E4D3A" /></View><View style={{ flex: 1 }}><Text style={styles.notificationTitle}>Tazelik uyarıları</Text><Text style={styles.notificationText}>Son kullanma yaklaşınca sana uygun tarifle birlikte hatırlatalım.</Text></View></View><Pressable onPress={enableNotifications} style={({ pressed }) => [styles.notificationCta, pressed && { opacity: 0.8 }]}><Text style={styles.notificationCtaText}>{Platform.OS === "web" ? "Bildirim durumunu gör" : "Tazelik uyarılarını aç"}</Text><IconSymbol name="chevron.right" size={17} color="#1E4D3A" /></Pressable>{notificationMessage ? <Text style={styles.notificationResult}>{notificationMessage}</Text> : null}</View>
    <View><Text style={styles.sectionTitle}>Tazelik önceliği</Text><View style={styles.expiryList}>{pantry.slice().sort((a, b) => (pantryMeta[a]?.expiresInDays ?? 5) - (pantryMeta[b]?.expiresInDays ?? 5)).slice(0, 4).map((item) => <View key={item} style={styles.expiryItem}><View style={styles.expiryDot}><IconSymbol name="clock" size={16} color="#B7652E" /></View><View style={{ flex: 1 }}><Text style={styles.expiryName}>{item}</Text><Text style={styles.expiryText}>{(pantryMeta[item]?.expiresInDays ?? 5) <= 1 ? "Bugün değerlendirmek iyi olur" : `${pantryMeta[item]?.expiresInDays ?? 5} gün içinde kullan`}</Text></View><Pressable onPress={() => setExpiryPriority(item, Math.max(1, (pantryMeta[item]?.expiresInDays ?? 5) - 1))} style={styles.priorityButton}><Text style={styles.priorityText}>Öne al</Text></Pressable></View>)}</View></View>
    <View><Text style={styles.sectionTitle}>Kilerinden çıkan fikirler</Text><View style={styles.ideaList}>{recipes.slice(0, 2).map((recipe) => <Pressable key={recipe.id} onPress={() => router.push(`/recipe/${recipe.id}` as never)} style={({ pressed }) => [styles.idea, pressed && { opacity: 0.7 }]}><View style={styles.ideaIcon}><IconSymbol name="sparkles" size={17} color="#1E4D3A" /></View><View style={{ flex: 1 }}><Text style={styles.ideaTitle}>{recipe.title}</Text><Text style={styles.ideaText}>{recipe.minutes} dk · Kilerinden 3 malzeme kullanıyor</Text></View><IconSymbol name="chevron.right" size={18} color="#1E4D3A" /></Pressable>)}</View></View>
  </ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({
  content: { padding: 20, gap: 22 }, header: { flexDirection: "row", alignItems: "center", gap: 12 }, back: { width: 42, height: 42, borderRadius: 14, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EAE7E0", justifyContent: "center", alignItems: "center" }, eyebrow: { color: "#6B756F", fontSize: 10, fontWeight: "800", letterSpacing: 1 }, title: { color: "#1E2521", fontSize: 25, lineHeight: 30, fontWeight: "800", letterSpacing: -0.55 }, count: { width: 38, height: 38, borderRadius: 19, alignItems: "center", justifyContent: "center", backgroundColor: "#DDE8DA" }, countText: { color: "#1E4D3A", fontSize: 15, fontWeight: "900" },
  addBox: { backgroundColor: "#FFFFFF", borderRadius: 22, borderWidth: 1, borderColor: "#EAE7E0", padding: 15, gap: 10 }, addTitle: { color: "#1E2521", fontSize: 15, fontWeight: "800" }, addRow: { flexDirection: "row", gap: 9, alignItems: "center" }, input: { flex: 1, height: 46, borderRadius: 14, backgroundColor: "#F5F8F3", paddingHorizontal: 12, fontSize: 14, color: "#1E2521" }, addButton: { width: 46, height: 46, borderRadius: 14, backgroundColor: "#1E4D3A", alignItems: "center", justifyContent: "center" }, addHint: { color: "#6B756F", fontSize: 11, lineHeight: 16 },
  sectionTitle: { color: "#1E2521", fontSize: 17, fontWeight: "800", marginBottom: 11 }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, chip: { flexDirection: "row", alignItems: "center", gap: 6, borderRadius: 16, backgroundColor: "#FFFFFF", paddingHorizontal: 12, paddingVertical: 9, borderWidth: 1, borderColor: "#EAE7E0" }, chipFavorite: { borderColor: "#F4A261", backgroundColor: "#FFF8F0" }, chipText: { color: "#1E4D3A", fontSize: 13, fontWeight: "700" },
  tip: { flexDirection: "row", alignItems: "center", gap: 12, padding: 15, backgroundColor: "#FCE6D2", borderRadius: 20 }, tipIcon: { width: 41, height: 41, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: "#FFFFFF" }, tipTitle: { color: "#754626", fontSize: 14, fontWeight: "800" }, tipText: { color: "#9A6138", fontSize: 12, lineHeight: 17, marginTop: 2 },
  notificationCard: { gap: 10, padding: 14, borderRadius: 20, backgroundColor: "#F5F8F3", borderWidth: 1, borderColor: "#C9DCC4" }, notificationTop: { flexDirection: "row", alignItems: "center", gap: 10 }, notificationIcon: { width: 38, height: 38, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "#DDE8DA" }, notificationTitle: { color: "#1E2521", fontSize: 14, fontWeight: "800" }, notificationText: { color: "#52705E", fontSize: 11, lineHeight: 16, marginTop: 2 }, notificationCta: { minHeight: 38, borderRadius: 12, paddingHorizontal: 11, flexDirection: "row", alignItems: "center", justifyContent: "space-between", backgroundColor: "#FFFFFF" }, notificationCtaText: { color: "#1E4D3A", fontSize: 12, fontWeight: "800" }, notificationResult: { color: "#52705E", fontSize: 11, lineHeight: 16 },
  expiryList: { gap: 8 }, expiryItem: { minHeight: 64, flexDirection: "row", alignItems: "center", gap: 10, padding: 11, borderRadius: 17, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EAE7E0" }, expiryDot: { width: 34, height: 34, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: "#FCE6D2" }, expiryName: { color: "#1E2521", fontSize: 13, fontWeight: "800" }, expiryText: { color: "#6B756F", fontSize: 10, marginTop: 2 }, priorityButton: { paddingHorizontal: 9, paddingVertical: 7, borderRadius: 10, backgroundColor: "#DDE8DA" }, priorityText: { color: "#1E4D3A", fontSize: 10, fontWeight: "800" },
  ideaList: { gap: 9 }, idea: { minHeight: 68, flexDirection: "row", alignItems: "center", gap: 11, backgroundColor: "#FFFFFF", borderRadius: 18, borderWidth: 1, borderColor: "#EAE7E0", paddingHorizontal: 13 }, ideaIcon: { width: 36, height: 36, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: "#DDE8DA" }, ideaTitle: { color: "#1E2521", fontSize: 13, fontWeight: "800" }, ideaText: { color: "#6B756F", fontSize: 11, marginTop: 2 },
});
