import { Pressable, ScrollView, StyleSheet, View } from "react-native";
import { LocalizedText as Text } from "@/components/localized-text";
import { router } from "expo-router";

import { IconSymbol } from "@/components/ui/icon-symbol";
import { ScreenContainer } from "@/components/screen-container";
import { useLezzet } from "@/lib/lezzet-context";

export default function ScanHistoryScreen() {
  const { scanHistory, removeScan } = useLezzet();
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="flex-1" containerClassName="bg-background"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <View style={styles.header}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && { opacity: 0.55 }]}><IconSymbol name="chevron.left" size={23} color="#1E4D3A" /></Pressable><View><Text style={styles.eyebrow}>AI GÖRSEL MUTFAK</Text><Text style={styles.title}>Tarama geçmişi</Text></View></View>
    {scanHistory.length ? <View style={styles.list}>{scanHistory.map((scan) => <View key={scan.id} style={styles.card}><View style={styles.cardHead}><View style={styles.scanIcon}><IconSymbol name="camera.fill" size={18} color="#1E4D3A" /></View><View style={{ flex: 1 }}><Text style={styles.cardTitle}>{scan.ingredients.slice(0, 3).join(", ")}</Text><Text style={styles.cardMeta}>{scan.createdAt} · {scan.ingredients.length} malzeme</Text></View><Pressable onPress={() => removeScan(scan.id)} hitSlop={8}><IconSymbol name="xmark" size={18} color="#6B756F" /></Pressable></View><View style={styles.chips}>{scan.ingredients.map((item) => <View key={item} style={styles.chip}><Text style={styles.chipText}>{item}</Text></View>)}</View><Pressable onPress={() => router.push({ pathname: "/(tabs)/chef", params: { prompt: scan.recipePrompt } } as never)} style={({ pressed }) => [styles.recipeButton, pressed && { opacity: 0.7 }]}><Text style={styles.recipeButtonText}>Bu taramadan tarif üret</Text><IconSymbol name="chevron.right" size={17} color="#1E4D3A" /></Pressable></View>)}</View> : <View style={styles.empty}><View style={styles.emptyIcon}><IconSymbol name="camera.fill" size={27} color="#1E4D3A" /></View><Text style={styles.emptyTitle}>Henüz tarama yapmadın.</Text><Text style={styles.emptyText}>Kilerindeki malzemeleri fotoğraflayarak hızlı tarif fikirleri oluşturabilirsin.</Text><Pressable onPress={() => router.replace("/scan-ingredients" as never)} style={styles.emptyCta}><Text style={styles.emptyCtaText}>İlk taramayı başlat</Text></Pressable></View>}
  </ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { padding: 20, gap: 20 }, header: { flexDirection: "row", alignItems: "center", gap: 12 }, back: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EAE7E0" }, eyebrow: { color: "#6B756F", fontSize: 10, fontWeight: "800", letterSpacing: 1 }, title: { color: "#1E2521", fontSize: 25, lineHeight: 30, fontWeight: "800", letterSpacing: -0.55 }, list: { gap: 12 }, card: { backgroundColor: "#FFFFFF", borderRadius: 21, borderWidth: 1, borderColor: "#EAE7E0", padding: 14, gap: 12 }, cardHead: { flexDirection: "row", alignItems: "center", gap: 10 }, scanIcon: { width: 36, height: 36, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: "#DDE8DA" }, cardTitle: { color: "#1E2521", fontSize: 14, fontWeight: "800" }, cardMeta: { color: "#6B756F", fontSize: 11, marginTop: 2 }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 6 }, chip: { paddingHorizontal: 9, paddingVertical: 6, borderRadius: 11, backgroundColor: "#F5F8F3" }, chipText: { color: "#1E4D3A", fontSize: 11, fontWeight: "700" }, recipeButton: { minHeight: 36, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, recipeButtonText: { color: "#1E4D3A", fontSize: 12, fontWeight: "800" }, empty: { marginTop: 50, alignItems: "center", padding: 28, backgroundColor: "#FFFFFF", borderRadius: 24, borderWidth: 1, borderColor: "#EAE7E0" }, emptyIcon: { width: 58, height: 58, borderRadius: 20, backgroundColor: "#DDE8DA", alignItems: "center", justifyContent: "center", marginBottom: 13 }, emptyTitle: { color: "#1E2521", fontSize: 16, fontWeight: "800" }, emptyText: { color: "#6B756F", fontSize: 12, lineHeight: 18, textAlign: "center", marginTop: 6 }, emptyCta: { backgroundColor: "#1E4D3A", borderRadius: 14, paddingHorizontal: 15, paddingVertical: 11, marginTop: 16 }, emptyCtaText: { color: "#FFFFFF", fontSize: 12, fontWeight: "800" } });
