import { Pressable, ScrollView, Share, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { useState } from "react";

import { IconSymbol } from "@/components/ui/icon-symbol";
import { ScreenContainer } from "@/components/screen-container";
import { useLezzet } from "@/lib/lezzet-context";
import { buildShoppingShareMessage } from "@/lib/meal-planning";

export default function ShoppingListScreen() {
  const { grocery, familyMembers, addFamilyMember, toggleGrocery } = useLezzet();
  const [shareTitle, setShareTitle] = useState("Aile alışveriş listesi");
  const [memberName, setMemberName] = useState("");
  const completed = grocery.filter((item) => item.checked).length;
  const shareList = async () => {
    await Share.share({ title: shareTitle.trim() || "Aile alışveriş listesi", message: buildShoppingShareMessage(shareTitle, grocery) });
  };
  const inviteMember = () => { if (!memberName.trim()) return; addFamilyMember(memberName); setMemberName(""); };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="flex-1" containerClassName="bg-background"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <View style={styles.header}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && { opacity: 0.55 }]}><IconSymbol name="chevron.left" size={23} color="#1E4D3A" /></Pressable><View style={{ flex: 1 }}><Text style={styles.eyebrow}>BU HAFTA</Text><Text style={styles.title}>Alışveriş listesi</Text></View><Pressable onPress={shareList} style={({ pressed }) => [styles.shareButton, pressed && { opacity: 0.65 }]}><IconSymbol name="paperplane.fill" size={19} color="#1E4D3A" /></Pressable></View>
    <View style={styles.progress}><View style={{ flex: 1 }}><Text style={styles.progressTitle}>Hazırlık durumu</Text><Text style={styles.progressText}>{completed}/{grocery.length} ürün işaretlendi</Text></View><View style={styles.progressBadge}><Text style={styles.progressNumber}>{grocery.length ? Math.round(completed / grocery.length * 100) : 0}%</Text></View></View>
    <View style={styles.familyCard}><View style={styles.familyTop}><View style={{ flex: 1 }}><Text style={styles.familyTitle}>Aile çalışma alanı</Text><Text style={styles.familyText}>Katılımcılar listeyi birlikte kontrol edebilir.</Text></View><View style={styles.memberStack}>{familyMembers.slice(0, 3).map((member, index) => <View key={member.id} style={[styles.memberAvatar, { backgroundColor: member.color, marginLeft: index ? -8 : 0 }]}><Text style={styles.memberInitial}>{member.name.slice(0, 1).toLocaleUpperCase("tr-TR")}</Text></View>)}</View></View><View style={styles.memberNames}>{familyMembers.map((member) => <Text key={member.id} style={styles.memberName}>{member.name}</Text>)}</View><View style={styles.inviteRow}><TextInput value={memberName} onChangeText={setMemberName} onSubmitEditing={inviteMember} placeholder="Aile üyesinin adı" placeholderTextColor="#87918B" returnKeyType="done" style={styles.inviteInput} /><Pressable onPress={inviteMember} style={({ pressed }) => [styles.inviteButton, pressed && { opacity: 0.75 }]}><IconSymbol name="plus" size={18} color="#1E4D3A" /></Pressable></View><Pressable onPress={shareList} style={({ pressed }) => [styles.inviteShare, pressed && { opacity: 0.65 }]}><Text style={styles.inviteShareText}>Aile grubuna davet bağlantısını paylaş</Text><IconSymbol name="paperplane.fill" size={16} color="#1E4D3A" /></Pressable></View>
    <View style={styles.shareCard}><View style={styles.shareTop}><View style={styles.shareIcon}><IconSymbol name="person.2.fill" size={19} color="#1E4D3A" /></View><View style={{ flex: 1 }}><Text style={styles.shareTitle}>Ailenle paylaş</Text><Text style={styles.shareText}>Listeni mesajlaşma uygulamalarına veya aile grubuna gönder.</Text></View></View><TextInput value={shareTitle} onChangeText={setShareTitle} maxLength={50} returnKeyType="done" style={styles.shareInput} placeholder="Liste başlığı" placeholderTextColor="#87918B" /><Pressable onPress={shareList} style={({ pressed }) => [styles.shareCta, pressed && { opacity: 0.85, transform: [{ scale: 0.985 }] }]}><IconSymbol name="paperplane.fill" size={18} color="#FFFFFF" /><Text style={styles.shareCtaText}>Mesajlaşma uygulamasında paylaş</Text></Pressable></View>
    <View style={styles.list}>{grocery.map((item) => <Pressable key={item.name} onPress={() => toggleGrocery(item.name)} style={({ pressed }) => [styles.item, item.checked && styles.itemChecked, pressed && { opacity: 0.7 }]}><View style={[styles.checkbox, item.checked && styles.checkboxChecked]}>{item.checked ? <IconSymbol name="checkmark.circle.fill" size={20} color="#FFFFFF" /> : null}</View><View style={{ flex: 1 }}><Text style={[styles.itemText, item.checked && styles.itemTextChecked]}>{item.name}</Text>{item.updatedBy ? <Text style={styles.updatedBy}>{item.updatedBy} · {item.updatedAt}</Text> : null}</View></Pressable>)}</View>
    <View style={styles.footer}><IconSymbol name="sparkles" size={18} color="#1E4D3A" /><Text style={styles.footerText}>Bu liste, haftalık planındaki tariflerden otomatik oluştu.</Text></View>
  </ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({
  content: { padding: 20, gap: 20 }, header: { flexDirection: "row", alignItems: "center", gap: 12 }, back: { width: 42, height: 42, borderRadius: 14, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EAE7E0", alignItems: "center", justifyContent: "center" }, shareButton: { width: 42, height: 42, borderRadius: 14, backgroundColor: "#DDE8DA", alignItems: "center", justifyContent: "center" }, eyebrow: { color: "#6B756F", fontSize: 10, fontWeight: "800", letterSpacing: 1 }, title: { color: "#1E2521", fontSize: 25, lineHeight: 30, fontWeight: "800", letterSpacing: -0.55 },
  progress: { minHeight: 88, flexDirection: "row", alignItems: "center", gap: 13, backgroundColor: "#1E4D3A", borderRadius: 22, paddingHorizontal: 17 }, progressTitle: { color: "#FFFFFF", fontSize: 16, fontWeight: "800" }, progressText: { color: "#DDE8DA", fontSize: 12, marginTop: 3 }, progressBadge: { width: 51, height: 51, borderRadius: 26, backgroundColor: "#34684F", alignItems: "center", justifyContent: "center", borderWidth: 3, borderColor: "#F4A261" }, progressNumber: { color: "#FFFFFF", fontSize: 11, fontWeight: "900" },
  familyCard: { gap: 10, padding: 14, borderRadius: 22, backgroundColor: "#F5F8F3", borderWidth: 1, borderColor: "#C9DCC4" }, familyTop: { flexDirection: "row", alignItems: "center", gap: 8 }, familyTitle: { color: "#1E2521", fontSize: 14, fontWeight: "800" }, familyText: { color: "#52705E", fontSize: 11, lineHeight: 16, marginTop: 2 }, memberStack: { flexDirection: "row", paddingRight: 5 }, memberAvatar: { width: 30, height: 30, borderRadius: 15, alignItems: "center", justifyContent: "center", borderWidth: 2, borderColor: "#F5F8F3" }, memberInitial: { color: "#FFFFFF", fontSize: 11, fontWeight: "900" }, memberNames: { flexDirection: "row", flexWrap: "wrap", gap: 6 }, memberName: { color: "#1E4D3A", fontSize: 11, fontWeight: "700" }, inviteRow: { flexDirection: "row", gap: 8 }, inviteInput: { flex: 1, height: 42, paddingHorizontal: 11, backgroundColor: "#FFFFFF", borderRadius: 12, fontSize: 12, color: "#1E2521" }, inviteButton: { width: 42, height: 42, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: "#DDE8DA" }, inviteShare: { minHeight: 32, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, inviteShareText: { color: "#1E4D3A", fontSize: 11, fontWeight: "800" },
  shareCard: { gap: 12, backgroundColor: "#FFFFFF", borderRadius: 22, borderWidth: 1, borderColor: "#C9DCC4", padding: 14 }, shareTop: { flexDirection: "row", gap: 11, alignItems: "center" }, shareIcon: { width: 40, height: 40, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "#DDE8DA" }, shareTitle: { color: "#1E2521", fontSize: 14, fontWeight: "800" }, shareText: { color: "#6B756F", fontSize: 11, lineHeight: 16, marginTop: 2 }, shareInput: { height: 44, borderRadius: 13, backgroundColor: "#F5F8F3", paddingHorizontal: 12, color: "#1E2521", fontSize: 13, fontWeight: "600" }, shareCta: { minHeight: 46, borderRadius: 14, backgroundColor: "#1E4D3A", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 }, shareCtaText: { color: "#FFFFFF", fontSize: 13, fontWeight: "800" },
  list: { backgroundColor: "#FFFFFF", overflow: "hidden", borderRadius: 20, borderWidth: 1, borderColor: "#EAE7E0" }, item: { minHeight: 58, flexDirection: "row", alignItems: "center", gap: 12, paddingHorizontal: 15, borderBottomWidth: 1, borderBottomColor: "#F0EEE9" }, itemChecked: { backgroundColor: "#F5F8F3" }, checkbox: { width: 22, height: 22, borderRadius: 7, borderWidth: 2, borderColor: "#B4C0B7", alignItems: "center", justifyContent: "center" }, checkboxChecked: { backgroundColor: "#2D7A55", borderColor: "#2D7A55" }, itemText: { color: "#1E2521", fontSize: 14, fontWeight: "700", flex: 1 }, itemTextChecked: { color: "#839088", textDecorationLine: "line-through" }, updatedBy: { color: "#6B756F", fontSize: 10, marginTop: 2 }, footer: { flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: "#DDE8DA", borderRadius: 16, padding: 13 }, footerText: { color: "#52705E", fontSize: 12, lineHeight: 17, flex: 1, fontWeight: "600" },
});
