import { Pressable, ScrollView, Share, StyleSheet, TextInput, View } from "react-native";
import { router } from "expo-router";
import { useEffect, useState } from "react";

import { IconSymbol } from "@/components/ui/icon-symbol";
import { LocalizedText as Text } from "@/components/localized-text";
import { ScreenContainer } from "@/components/screen-container";
import { useLezzet } from "@/lib/lezzet-context";
import { buildShoppingShareMessage } from "@/lib/meal-planning";
import { trpc } from "@/lib/trpc";
import { formatLocalCurrency, getMarketCategory, toLocalMarketEstimate } from "@/lib/seasonal-market";

export default function ShoppingListScreen() {
  const { grocery, familyMembers, addFamilyMember, toggleGrocery, sharedListInviteCode, setSharedListInviteCode, profile } = useLezzet();
  const [shareTitle, setShareTitle] = useState("Aile alışveriş listesi");
  const [memberName, setMemberName] = useState("");
  const [joinCode, setJoinCode] = useState("");
  const bootstrap = trpc.familyList.bootstrap.useMutation({ onSuccess: (data) => setSharedListInviteCode(data.list.inviteCode) });
  const sharedQuery = trpc.familyList.get.useQuery({ inviteCode: sharedListInviteCode ?? "" }, { enabled: Boolean(sharedListInviteCode), refetchInterval: 3000, refetchOnWindowFocus: true });
  const updateSharedItem = trpc.familyList.updateItem.useMutation({ onSuccess: () => sharedQuery.refetch() });
  useEffect(() => { if (!sharedListInviteCode && !bootstrap.isPending && !bootstrap.data) bootstrap.mutate({ title: shareTitle, ownerName: "Deniz", seedItems: grocery.map((item) => item.name) }); }, [bootstrap, grocery, shareTitle, sharedListInviteCode]);
  const displayItems = sharedQuery.data?.items ?? grocery;
  const completed = displayItems.filter((item) => item.checked).length;
  const marketSummary = displayItems.reduce<Record<string, { count: number; cost: number }>>((summary, item) => {
    const category = getMarketCategory(item.name, profile.locale);
    const cost = toLocalMarketEstimate(24, profile.locale);
    summary[category] = { count: (summary[category]?.count ?? 0) + 1, cost: (summary[category]?.cost ?? 0) + cost };
    return summary;
  }, {});
  const marketTotal = Object.values(marketSummary).reduce((sum, group) => sum + group.cost, 0);
  const shareList = async () => {
    const codeSuffix = sharedListInviteCode ? `\n\nAile listesi kodu: ${sharedListInviteCode}` : "";
    await Share.share({ title: shareTitle.trim() || "Aile alışveriş listesi", message: `${buildShoppingShareMessage(shareTitle, displayItems)}${codeSuffix}` });
  };
  const inviteMember = () => { if (!memberName.trim()) return; addFamilyMember(memberName); setMemberName(""); };
  const joinSharedList = () => { const code = joinCode.trim(); if (!code) return; setSharedListInviteCode(code); };
  const toggleItem = (item: { name: string; checked: boolean }) => { if (sharedListInviteCode) updateSharedItem.mutate({ inviteCode: sharedListInviteCode, name: item.name, checked: !item.checked, updatedBy: "Deniz" }); else toggleGrocery(item.name); };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="flex-1" containerClassName="bg-background"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <View style={styles.header}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && { opacity: 0.55 }]}><IconSymbol name="chevron.left" size={23} color="#1E4D3A" /></Pressable><View style={{ flex: 1 }}><Text style={styles.eyebrow}>BU HAFTA</Text><Text style={styles.title}>Alışveriş listesi</Text></View><Pressable onPress={shareList} style={({ pressed }) => [styles.shareButton, pressed && { opacity: 0.65 }]}><IconSymbol name="paperplane.fill" size={19} color="#1E4D3A" /></Pressable></View>
    <View style={styles.progress}><View style={{ flex: 1 }}><Text style={styles.progressTitle}>Hazırlık durumu</Text><Text style={styles.progressText}>{completed}/{displayItems.length} ürün işaretlendi</Text></View><View style={styles.progressBadge}><Text style={styles.progressNumber}>{displayItems.length ? Math.round(completed / displayItems.length * 100) : 0}%</Text></View></View>
    <View style={styles.marketCard}><View style={styles.marketHead}><View><Text style={styles.marketLabel}>MARKET ÖZETİ</Text><Text style={styles.marketValue}>≈ {formatLocalCurrency(marketTotal, profile.locale)}</Text></View><Text style={styles.marketNote}>Plan tahmini</Text></View><View style={styles.marketGroups}>{Object.entries(marketSummary).map(([category, group]) => <View key={category} style={styles.marketGroup}><Text style={styles.marketGroupName}>{category}</Text><Text style={styles.marketGroupValue}>{group.count} ürün · ≈ {formatLocalCurrency(group.cost, profile.locale)}</Text></View>)}</View><Text style={styles.marketHint}>Listeyi yerel market reyonlarına göre sıraya koyduk; taze ürünleri önce alarak gereksiz harcamayı azaltabilirsin.</Text></View>
    <View style={styles.syncCard}><View style={styles.syncTop}><View style={[styles.syncDot, sharedQuery.isError && styles.syncDotError]} /><View style={{ flex: 1 }}><Text style={styles.syncTitle}>{sharedListInviteCode ? "Aile listesi eşitleniyor" : "Aile listesi hazırlanıyor"}</Text><Text style={styles.syncText}>{sharedListInviteCode ? "Değişiklikler en fazla 3 saniye içinde yenilenir." : "Bulut listesi oluşturuluyor."}</Text></View><Pressable onPress={() => sharedQuery.refetch()} hitSlop={8}><IconSymbol name="arrow.clockwise" size={18} color="#1E4D3A" /></Pressable></View>{sharedListInviteCode ? <Text style={styles.codeText}>DAVET KODU · {sharedListInviteCode}</Text> : null}<View style={styles.joinRow}><TextInput value={joinCode} onChangeText={setJoinCode} placeholder="Davet koduyla katıl" placeholderTextColor="#87918B" autoCapitalize="none" style={styles.joinInput} /><Pressable onPress={joinSharedList} style={({ pressed }) => [styles.joinButton, pressed && { opacity: 0.7 }]}><Text style={styles.joinButtonText}>Katıl</Text></Pressable></View>{sharedQuery.isError ? <Text style={styles.syncError}>Davet kodu bulunamadı veya bağlantı kurulamadı. Kodu kontrol edip tekrar deneyin.</Text> : null}</View>
    <View style={styles.familyCard}><View style={styles.familyTop}><View style={{ flex: 1 }}><Text style={styles.familyTitle}>Aile çalışma alanı</Text><Text style={styles.familyText}>Katılımcılar listeyi birlikte kontrol edebilir.</Text></View><View style={styles.memberStack}>{familyMembers.slice(0, 3).map((member, index) => <View key={member.id} style={[styles.memberAvatar, { backgroundColor: member.color, marginLeft: index ? -8 : 0 }]}><Text style={styles.memberInitial}>{member.name.slice(0, 1).toLocaleUpperCase(profile.locale)}</Text></View>)}</View></View><View style={styles.memberNames}>{familyMembers.map((member) => <Text key={member.id} style={styles.memberName}>{member.name}</Text>)}</View><View style={styles.inviteRow}><TextInput value={memberName} onChangeText={setMemberName} onSubmitEditing={inviteMember} placeholder="Aile üyesinin adı" placeholderTextColor="#87918B" returnKeyType="done" style={styles.inviteInput} /><Pressable onPress={inviteMember} style={({ pressed }) => [styles.inviteButton, pressed && { opacity: 0.75 }]}><IconSymbol name="plus" size={18} color="#1E4D3A" /></Pressable></View><Pressable onPress={shareList} style={({ pressed }) => [styles.inviteShare, pressed && { opacity: 0.65 }]}><Text style={styles.inviteShareText}>Aile grubuna davet bağlantısını paylaş</Text><IconSymbol name="paperplane.fill" size={16} color="#1E4D3A" /></Pressable></View>
    <View style={styles.shareCard}><View style={styles.shareTop}><View style={styles.shareIcon}><IconSymbol name="person.2.fill" size={19} color="#1E4D3A" /></View><View style={{ flex: 1 }}><Text style={styles.shareTitle}>Ailenle paylaş</Text><Text style={styles.shareText}>Listeni mesajlaşma uygulamalarına veya aile grubuna gönder.</Text></View></View><TextInput value={shareTitle} onChangeText={setShareTitle} maxLength={50} returnKeyType="done" style={styles.shareInput} placeholder="Liste başlığı" placeholderTextColor="#87918B" /><Pressable onPress={shareList} style={({ pressed }) => [styles.shareCta, pressed && { opacity: 0.85, transform: [{ scale: 0.985 }] }]}><IconSymbol name="paperplane.fill" size={18} color="#FFFFFF" /><Text style={styles.shareCtaText}>Mesajlaşma uygulamasında paylaş</Text></Pressable></View>
    <View style={styles.list}>{displayItems.map((item) => <Pressable key={item.name} onPress={() => toggleItem(item)} style={({ pressed }) => [styles.item, item.checked && styles.itemChecked, pressed && { opacity: 0.7 }]}><View style={[styles.checkbox, item.checked && styles.checkboxChecked]}>{item.checked ? <IconSymbol name="checkmark.circle.fill" size={20} color="#FFFFFF" /> : null}</View><View style={{ flex: 1 }}><Text style={[styles.itemText, item.checked && styles.itemTextChecked]}>{item.name}</Text>{item.updatedBy ? <Text style={styles.updatedBy}>{item.updatedBy} · {item.updatedAt ? new Date(item.updatedAt).toLocaleTimeString(profile.locale, { hour: "2-digit", minute: "2-digit" }) : "az önce"}</Text> : null}</View></Pressable>)}</View>
    <View style={styles.footer}><IconSymbol name="sparkles" size={18} color="#1E4D3A" /><Text style={styles.footerText}>Bu liste, haftalık planındaki tariflerden otomatik oluştu.</Text></View>
  </ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({
  content: { padding: 20, gap: 20 }, header: { flexDirection: "row", alignItems: "center", gap: 12 }, back: { width: 42, height: 42, borderRadius: 14, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EAE7E0", alignItems: "center", justifyContent: "center" }, shareButton: { width: 42, height: 42, borderRadius: 14, backgroundColor: "#DDE8DA", alignItems: "center", justifyContent: "center" }, eyebrow: { color: "#6B756F", fontSize: 10, fontWeight: "800", letterSpacing: 1 }, title: { color: "#1E2521", fontSize: 25, lineHeight: 30, fontWeight: "800", letterSpacing: -0.55 },
  progress: { minHeight: 88, flexDirection: "row", alignItems: "center", gap: 13, backgroundColor: "#1E4D3A", borderRadius: 22, paddingHorizontal: 17 }, progressTitle: { color: "#FFFFFF", fontSize: 16, fontWeight: "800" }, progressText: { color: "#DDE8DA", fontSize: 12, marginTop: 3 }, progressBadge: { width: 51, height: 51, borderRadius: 26, backgroundColor: "#34684F", alignItems: "center", justifyContent: "center", borderWidth: 3, borderColor: "#F4A261" }, progressNumber: { color: "#FFFFFF", fontSize: 11, fontWeight: "900" },
  marketCard: { gap: 10, padding: 14, borderRadius: 20, backgroundColor: "#F5F8F3", borderWidth: 1, borderColor: "#C9DCC4" }, marketHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, marketLabel: { color: "#6B756F", fontSize: 10, fontWeight: "900", letterSpacing: 0.75 }, marketValue: { color: "#1E2521", fontSize: 19, fontWeight: "900", marginTop: 3 }, marketNote: { color: "#52705E", fontSize: 10, fontWeight: "800", backgroundColor: "#DDE8DA", paddingHorizontal: 8, paddingVertical: 5, borderRadius: 9 }, marketGroups: { gap: 6 }, marketGroup: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 7, borderBottomWidth: 1, borderBottomColor: "#E0E9DE" }, marketGroupName: { color: "#1E4D3A", fontSize: 11, fontWeight: "800" }, marketGroupValue: { color: "#6B756F", fontSize: 11, fontWeight: "700" }, marketHint: { color: "#52705E", fontSize: 10, lineHeight: 15 },
  syncCard: { gap: 10, backgroundColor: "#FFFFFF", borderRadius: 20, borderWidth: 1, borderColor: "#C9DCC4", padding: 13 }, syncTop: { flexDirection: "row", alignItems: "center", gap: 9 }, syncDot: { width: 9, height: 9, borderRadius: 5, backgroundColor: "#2D7A55" }, syncDotError: { backgroundColor: "#C84D40" }, syncTitle: { color: "#1E2521", fontSize: 13, fontWeight: "800" }, syncText: { color: "#6B756F", fontSize: 10, lineHeight: 15, marginTop: 2 }, codeText: { color: "#1E4D3A", fontSize: 10, fontWeight: "900", letterSpacing: 0.55, paddingHorizontal: 1 }, joinRow: { flexDirection: "row", gap: 8 }, joinInput: { flex: 1, height: 39, borderRadius: 11, backgroundColor: "#F5F8F3", paddingHorizontal: 10, fontSize: 11, color: "#1E2521" }, joinButton: { alignItems: "center", justifyContent: "center", paddingHorizontal: 13, borderRadius: 11, backgroundColor: "#DDE8DA" }, joinButtonText: { color: "#1E4D3A", fontSize: 11, fontWeight: "800" }, syncError: { color: "#B54C40", fontSize: 10, lineHeight: 15 },
  familyCard: { gap: 10, padding: 14, borderRadius: 22, backgroundColor: "#F5F8F3", borderWidth: 1, borderColor: "#C9DCC4" }, familyTop: { flexDirection: "row", alignItems: "center", gap: 8 }, familyTitle: { color: "#1E2521", fontSize: 14, fontWeight: "800" }, familyText: { color: "#52705E", fontSize: 11, lineHeight: 16, marginTop: 2 }, memberStack: { flexDirection: "row", paddingRight: 5 }, memberAvatar: { width: 30, height: 30, borderRadius: 15, alignItems: "center", justifyContent: "center", borderWidth: 2, borderColor: "#F5F8F3" }, memberInitial: { color: "#FFFFFF", fontSize: 11, fontWeight: "900" }, memberNames: { flexDirection: "row", flexWrap: "wrap", gap: 6 }, memberName: { color: "#1E4D3A", fontSize: 11, fontWeight: "700" }, inviteRow: { flexDirection: "row", gap: 8 }, inviteInput: { flex: 1, height: 42, paddingHorizontal: 11, backgroundColor: "#FFFFFF", borderRadius: 12, fontSize: 12, color: "#1E2521" }, inviteButton: { width: 42, height: 42, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: "#DDE8DA" }, inviteShare: { minHeight: 32, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, inviteShareText: { color: "#1E4D3A", fontSize: 11, fontWeight: "800" },
  shareCard: { gap: 12, backgroundColor: "#FFFFFF", borderRadius: 22, borderWidth: 1, borderColor: "#C9DCC4", padding: 14 }, shareTop: { flexDirection: "row", gap: 11, alignItems: "center" }, shareIcon: { width: 40, height: 40, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "#DDE8DA" }, shareTitle: { color: "#1E2521", fontSize: 14, fontWeight: "800" }, shareText: { color: "#6B756F", fontSize: 11, lineHeight: 16, marginTop: 2 }, shareInput: { height: 44, borderRadius: 13, backgroundColor: "#F5F8F3", paddingHorizontal: 12, color: "#1E2521", fontSize: 13, fontWeight: "600" }, shareCta: { minHeight: 46, borderRadius: 14, backgroundColor: "#1E4D3A", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 }, shareCtaText: { color: "#FFFFFF", fontSize: 13, fontWeight: "800" },
  list: { backgroundColor: "#FFFFFF", overflow: "hidden", borderRadius: 20, borderWidth: 1, borderColor: "#EAE7E0" }, item: { minHeight: 58, flexDirection: "row", alignItems: "center", gap: 12, paddingHorizontal: 15, borderBottomWidth: 1, borderBottomColor: "#F0EEE9" }, itemChecked: { backgroundColor: "#F5F8F3" }, checkbox: { width: 22, height: 22, borderRadius: 7, borderWidth: 2, borderColor: "#B4C0B7", alignItems: "center", justifyContent: "center" }, checkboxChecked: { backgroundColor: "#2D7A55", borderColor: "#2D7A55" }, itemText: { color: "#1E2521", fontSize: 14, fontWeight: "700", flex: 1 }, itemTextChecked: { color: "#839088", textDecorationLine: "line-through" }, updatedBy: { color: "#6B756F", fontSize: 10, marginTop: 2 }, footer: { flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: "#DDE8DA", borderRadius: 16, padding: 13 }, footerText: { color: "#52705E", fontSize: 12, lineHeight: 17, flex: 1, fontWeight: "600" },
});
