import { Animated, Easing, Pressable, ScrollView, StyleSheet, View } from "react-native";
import { router } from "expo-router";
import { useEffect, useRef } from "react";

import { IconSymbol } from "@/components/ui/icon-symbol";
import { LocalizedText as Text } from "@/components/localized-text";
import { ScreenContainer } from "@/components/screen-container";

const cards = [
  { icon: "cabinet.fill" as const, title: "Kilerin, kararlarının önünde", text: "Elindekileri ve yaklaşan tarihleri bir bakışta gör. Ne kullanacağını düşünmek yerine, önce neyi değerlendireceğini bil.", tint: "#DDE8DA", accent: "#1E4D3A" },
  { icon: "sparkles" as const, title: "Fikir aramak yerine pişir", text: "Tercihlerine, malzemelerine ve seçtiğin mutfak kültürüne göre haftayı daha az zihinsel yükle planla.", tint: "#FFF1E8", accent: "#B7652E" },
  { icon: "cart.fill" as const, title: "Alışveriş, ailece daha sakin", text: "Eksikleri yakala, fişlerini anlamlandır ve davet koduyla listenin aynı sürümünde kal.", tint: "#E8EEF6", accent: "#456A93" },
];

export default function SubscriptionShowcaseScreen() {
  const glow = useRef(new Animated.Value(0.55)).current;
  useEffect(() => { const animation = Animated.loop(Animated.sequence([Animated.timing(glow, { toValue: 1, duration: 1700, easing: Easing.inOut(Easing.quad), useNativeDriver: true }), Animated.timing(glow, { toValue: 0.55, duration: 1700, easing: Easing.inOut(Easing.quad), useNativeDriver: true })])); animation.start(); return () => animation.stop(); }, [glow]);
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="flex-1" containerClassName="bg-background"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <View style={styles.brandRow}><View style={styles.logo}><IconSymbol name="sparkles" size={22} color="#F4A261" /></View><Text style={styles.brand}>LEZZETAI PREMIUM</Text></View>
    <View style={styles.hero}><Animated.View style={[styles.heroGlow, { opacity: glow }]} /><Text style={styles.eyebrow}>MUTFAĞININ YENİ RİTMİ</Text><Text style={styles.title}>Yemek planı, günün en zor kararı olmak zorunda değil.</Text><Text style={styles.subtitle}>LezzetAI; kilerini, haftanı ve alışverişini tek, sakin bir akışta birleştirir.</Text><View style={styles.visual}><View style={styles.visualTop}><Text style={styles.visualLabel}>BUGÜNÜN MUTFAĞI</Text><View style={styles.liveDot} /></View><View style={styles.visualLine}><View style={[styles.bar, { width: "72%" }]} /><View style={[styles.bar, styles.barSoft, { width: "48%" }]} /><View style={[styles.bar, styles.barWarm, { width: "60%" }]} /></View><View style={styles.visualFoot}><Text style={styles.visualFootText}>Kiler → fikir → plan → liste</Text><IconSymbol name="chevron.right" size={16} color="#DDE8DA" /></View></View></View>
    <View style={styles.cardList}>{cards.map((card) => <View key={card.title} style={styles.card}><View style={[styles.cardIcon, { backgroundColor: card.tint }]}><IconSymbol name={card.icon} size={23} color={card.accent} /></View><View style={{ flex: 1 }}><Text style={styles.cardTitle}>{card.title}</Text><Text style={styles.cardText}>{card.text}</Text></View></View>)}</View>
    <View style={styles.trust}><IconSymbol name="checkmark.circle.fill" size={18} color="#1E4D3A" /><Text style={styles.trustText}>Önce uygulamanın nasıl yardımcı olduğunu gör. Sonra seçtiğin planla 7 gün ücretsiz dene.</Text></View>
    <Pressable onPress={() => router.push("/subscription-paywall" as never)} style={({ pressed }) => [styles.cta, pressed && { opacity: 0.88, transform: [{ scale: 0.985 }] }]}><Text style={styles.ctaText}>7 gün ücretsiz denemeyi incele</Text><IconSymbol name="chevron.right" size={20} color="#FFFFFF" /></Pressable><Text style={styles.bottomNote}>Deneme koşulları ve yenileme fiyatı, satın alma öncesinde açıkça gösterilir.</Text>
  </ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 30, gap: 15 }, brandRow: { flexDirection: "row", alignItems: "center", gap: 9 }, logo: { width: 38, height: 38, borderRadius: 13, backgroundColor: "#1E4D3A", alignItems: "center", justifyContent: "center" }, brand: { color: "#1E4D3A", fontSize: 10, letterSpacing: 1.3, fontWeight: "900" }, hero: { overflow: "hidden", gap: 10, padding: 20, borderRadius: 28, backgroundColor: "#1E4D3A" }, heroGlow: { position: "absolute", width: 230, height: 230, borderRadius: 115, right: -80, top: -120, backgroundColor: "#5E9367" }, eyebrow: { color: "#DDE8DA", fontSize: 10, fontWeight: "900", letterSpacing: 1.1 }, title: { color: "#FFFFFF", fontSize: 27, lineHeight: 33, letterSpacing: -0.8, fontWeight: "900" }, subtitle: { color: "#DDE8DA", fontSize: 13, lineHeight: 19, maxWidth: 290 }, visual: { gap: 10, marginTop: 8, padding: 14, borderRadius: 18, backgroundColor: "rgba(255,255,255,0.1)", borderWidth: 1, borderColor: "rgba(255,255,255,0.15)" }, visualTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, visualLabel: { color: "#FFFFFF", fontSize: 9, letterSpacing: 0.8, fontWeight: "900" }, liveDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: "#F4A261" }, visualLine: { gap: 7 }, bar: { height: 7, borderRadius: 4, backgroundColor: "#E2F0DD" }, barSoft: { backgroundColor: "#B9D5BD" }, barWarm: { backgroundColor: "#F4A261" }, visualFoot: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, visualFootText: { color: "#DDE8DA", fontSize: 10, fontWeight: "800" }, cardList: { gap: 9 }, card: { flexDirection: "row", gap: 12, alignItems: "flex-start", padding: 14, borderRadius: 20, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EAE7E0" }, cardIcon: { width: 44, height: 44, borderRadius: 15, alignItems: "center", justifyContent: "center" }, cardTitle: { color: "#1E2521", fontSize: 14, fontWeight: "900" }, cardText: { color: "#6B756F", fontSize: 11, lineHeight: 16, marginTop: 3 }, trust: { flexDirection: "row", alignItems: "flex-start", gap: 8, padding: 12, borderRadius: 15, backgroundColor: "#F5F8F3" }, trustText: { flex: 1, color: "#52705E", fontSize: 11, lineHeight: 16, fontWeight: "700" }, cta: { height: 54, borderRadius: 18, backgroundColor: "#1E4D3A", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7 }, ctaText: { color: "#FFFFFF", fontSize: 14, fontWeight: "900" }, bottomNote: { color: "#6B756F", textAlign: "center", fontSize: 10, lineHeight: 15 } });
