import { Pressable, ScrollView, StyleSheet, View } from "react-native";
import { router } from "expo-router";

import { IconSymbol } from "@/components/ui/icon-symbol";
import { LocalizedText as Text } from "@/components/localized-text";
import { ScreenContainer } from "@/components/screen-container";

export default function TermsScreen() { return <ScreenContainer className="flex-1" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && { opacity: 0.7 }]}><IconSymbol name="chevron.left" size={18} color="#1E4D3A" /><Text style={styles.backText}>Geri</Text></Pressable><Text style={styles.title}>Kullanım koşulları</Text><Text style={styles.updated}>Son güncelleme: yayından önce güncellenecek</Text><View style={styles.card}><Text style={styles.heading}>Premium abonelik</Text><Text style={styles.body}>Premium abonelik; kiler, planlama ve aile çalışma alanları gibi uygulama içi dijital özelliklere erişim sağlar. Bir deneme yalnızca mağaza tarafından uygun görülen kullanıcılar için kullanılabilir.</Text><Text style={styles.body}>Aylık veya yıllık planı kullanıcı seçer. Ücretsiz deneme sonrasında seçilen plan, satın alma ekranında gösterilen yerel fiyat ve dönemle otomatik yenilenir; kullanıcı istediği zaman App Store veya Google Play abonelik ayarlarından iptal edebilir.</Text><Text style={styles.heading}>Kullanım sınırları</Text><Text style={styles.body}>Tarif, alerjen ve son kullanma önerileri bilgi amaçlıdır; tıbbi, beslenme uzmanlığı veya gıda güvenliği kararı yerine geçmez. Paket etiketi, gıda güvenliği talimatı ve gerekirse uzman görüşü esas alınmalıdır.</Text><Text style={styles.heading}>Destek ve geri bildirim</Text><Text style={styles.body}>Yayın öncesinde, destek iletişim adresi ve geçerli şirket bilgileri bu sayfada herkese açık biçimde güncellenecektir.</Text></View></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 34, gap: 13 }, back: { alignSelf: "flex-start", minHeight: 36, flexDirection: "row", alignItems: "center", gap: 4, paddingRight: 9 }, backText: { color: "#1E4D3A", fontSize: 13, fontWeight: "800" }, title: { color: "#1E2521", fontSize: 27, fontWeight: "900", letterSpacing: -0.6 }, updated: { color: "#6B756F", fontSize: 10, marginTop: -7 }, card: { gap: 11, padding: 16, borderRadius: 21, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EAE7E0" }, heading: { color: "#1E4D3A", fontSize: 14, fontWeight: "900", marginTop: 4 }, body: { color: "#526057", fontSize: 12, lineHeight: 19 } });
