import { Alert, Pressable, ScrollView, StyleSheet, View } from "react-native";
import { LocalizedText as Text } from "@/components/localized-text";
import { router } from "expo-router";
import { useState } from "react";

import { IconSymbol } from "@/components/ui/icon-symbol";
import { ScreenContainer } from "@/components/screen-container";
import { useLezzet } from "@/lib/lezzet-context";
import { syncWearableActivity } from "@/lib/wearable-sync";
import { getAdaptiveTargets } from "@/lib/wearable-utils";

export default function WearablesScreen() {
  const { profile, wearableActivity, setWearableActivity } = useLezzet();
  const [syncing, setSyncing] = useState(false);
  const targets = getAdaptiveTargets(profile.calories, wearableActivity?.activeCalories ?? 0);
  const sync = async () => { try { setSyncing(true); const activity = await syncWearableActivity(); setWearableActivity(activity); } catch (error) { Alert.alert("Senkronizasyon başlatılamadı", error instanceof Error ? error.message : "Cihaz verisine erişmek için izin verip tekrar dene."); } finally { setSyncing(false); } };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="flex-1" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.top}><Pressable onPress={() => router.back()} style={styles.back}><IconSymbol name="chevron.left" size={22} color="#1E4D3A" /></Pressable><View><Text style={styles.eyebrow}>AKTİVİTE SENKRONİZASYONU</Text><Text style={styles.title}>Hareketinle uyumlu plan</Text></View></View>
    <View style={styles.hero}><View style={styles.orbit}><View style={styles.orbitInner}><IconSymbol name="sparkles" size={30} color="#F4A261" /></View></View><Text style={styles.heroTitle}>{wearableActivity ? `${wearableActivity.source} bağlı` : "Cihazını bağla"}</Text><Text style={styles.heroText}>{wearableActivity ? `${wearableActivity.syncedAt} senkronize edildi. Günlük hedeflerin aktivite özetiyle güncellendi.` : "Apple Health veya Android Health Connect’te izin verdiğin günlük hareket verisini yalnızca hedeflerini uyarlamak için okuruz."}</Text></View>
    <View style={styles.permission}><IconSymbol name="leaf.fill" size={18} color="#1E4D3A" /><Text style={styles.permissionText}>Yalnızca adım ve aktif enerji verisi okunur. Sağlık kayıtların yazılmaz veya paylaşılmaz.</Text></View>
    {wearableActivity ? <View style={styles.activityCard}><Text style={styles.cardLabel}>BUGÜNÜN AKTİVİTESİ</Text><View style={styles.activityGrid}><Stat value={wearableActivity.steps.toLocaleString("tr-TR")} label="adım" /><Stat value={`${wearableActivity.activeCalories}`} label="aktif kcal" /><Stat value={`${wearableActivity.workoutMinutes}`} label="egzersiz dk" /></View></View> : null}
    <View style={styles.targets}><View style={styles.targetsHead}><View><Text style={styles.cardLabel}>UYARLANAN GÜNLÜK HEDEF</Text><Text style={styles.targetCalories}>{targets.calories} <Text style={styles.targetUnit}>kcal</Text></Text></View>{targets.adjustment ? <Text style={styles.adjustment}>+{targets.adjustment} kcal hareket uyarlaması</Text> : <Text style={styles.adjustment}>Temel hedefin</Text>}</View><View style={styles.macroRow}><Macro label="Protein" value={`${targets.protein} g`} color="#1E4D3A" /><Macro label="Karbonhidrat" value={`${targets.carbs} g`} color="#F4A261" /><Macro label="Yağ" value={`${targets.fat} g`} color="#B7652E" /></View></View>
    <Pressable onPress={sync} disabled={syncing} style={({ pressed }) => [styles.syncButton, syncing && { opacity: 0.55 }, pressed && { transform: [{ scale: 0.985 }], opacity: 0.88 }]}><IconSymbol name="arrow.clockwise" size={19} color="#FFFFFF" /><Text style={styles.syncText}>{syncing ? "Cihaz okunuyor..." : wearableActivity ? "Şimdi yeniden senkronize et" : "Apple Health / Health Connect’i bağla"}</Text></Pressable>
    <Text style={styles.note}>Bu özellik, Expo Go yerine iOS veya Android için oluşturulan özel geliştirme yapısında çalışır.</Text>
  </ScrollView></ScreenContainer>;
}

function Stat({ value, label }: { value: string; label: string }) { return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }
function Macro({ label, value, color }: { label: string; value: string; color: string }) { return <View style={styles.macro}><View style={[styles.macroDot, { backgroundColor: color }]} /><Text style={styles.macroLabel}>{label}</Text><Text style={styles.macroValue}>{value}</Text></View>; }
const styles = StyleSheet.create({ content: { padding: 20, gap: 17, paddingBottom: 34 }, top: { flexDirection: "row", alignItems: "center", gap: 11 }, back: { width: 41, height: 41, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: "#DDE8DA" }, eyebrow: { color: "#6B756F", fontSize: 10, fontWeight: "900", letterSpacing: 1.1 }, title: { color: "#1E2521", fontSize: 24, lineHeight: 30, fontWeight: "800", marginTop: 2, letterSpacing: -0.6 }, hero: { alignItems: "center", gap: 9, padding: 22, borderRadius: 26, backgroundColor: "#1E4D3A" }, orbit: { width: 90, height: 90, borderRadius: 45, borderWidth: 1, borderColor: "#5A8B73", alignItems: "center", justifyContent: "center" }, orbitInner: { width: 62, height: 62, borderRadius: 31, alignItems: "center", justifyContent: "center", backgroundColor: "#34684F" }, heroTitle: { color: "#FFFFFF", fontSize: 20, fontWeight: "800", marginTop: 3 }, heroText: { color: "#DDE8DA", fontSize: 12, lineHeight: 18, textAlign: "center", maxWidth: 290 }, permission: { flexDirection: "row", gap: 9, padding: 13, borderRadius: 18, backgroundColor: "#DDE8DA" }, permissionText: { flex: 1, color: "#52705E", fontSize: 11, lineHeight: 16, fontWeight: "600" }, activityCard: { padding: 15, borderRadius: 22, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EAE7E0", gap: 12 }, cardLabel: { color: "#6B756F", fontSize: 10, fontWeight: "900", letterSpacing: 0.8 }, activityGrid: { flexDirection: "row", justifyContent: "space-between" }, stat: { flex: 1, gap: 3 }, statValue: { color: "#1E2521", fontSize: 18, fontWeight: "900" }, statLabel: { color: "#6B756F", fontSize: 10, fontWeight: "700" }, targets: { padding: 16, gap: 14, borderRadius: 23, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#C9DCC4", shadowColor: "#1E4D3A", shadowOpacity: 0.06, shadowRadius: 12, shadowOffset: { width: 0, height: 6 }, elevation: 2 }, targetsHead: { flexDirection: "row", justifyContent: "space-between", gap: 10 }, targetCalories: { color: "#1E2521", fontSize: 29, fontWeight: "900", marginTop: 3, letterSpacing: -0.75 }, targetUnit: { color: "#6B756F", fontSize: 13 }, adjustment: { alignSelf: "center", color: "#1E4D3A", fontSize: 10, fontWeight: "800", backgroundColor: "#DDE8DA", paddingHorizontal: 8, paddingVertical: 6, borderRadius: 10 }, macroRow: { flexDirection: "row", gap: 8 }, macro: { flex: 1, gap: 3, padding: 9, borderRadius: 12, backgroundColor: "#F5F8F3" }, macroDot: { width: 7, height: 7, borderRadius: 4 }, macroLabel: { color: "#6B756F", fontSize: 9, fontWeight: "700" }, macroValue: { color: "#1E2521", fontSize: 13, fontWeight: "900" }, syncButton: { minHeight: 52, borderRadius: 16, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, backgroundColor: "#1E4D3A" }, syncText: { color: "#FFFFFF", fontSize: 13, fontWeight: "800" }, note: { color: "#6B756F", fontSize: 10, lineHeight: 15, textAlign: "center", paddingHorizontal: 14 } });
