export const cuisineLocales = [
  { code: "tr-TR", language: "Türkçe", region: "Türkiye", flag: "TR", pantryHighlights: ["Bulgur", "Mercimek", "Yoğurt", "Domates"], recommendedTools: ["Tencere", "Düdüklü tencere", "Tava", "Fırın", "Blender"], planNote: "Bakliyat, zeytinyağlı ve ev yemeği dengesiyle planlandı.", days: ["Pzt", "Sal", "Çar", "Per", "Cum", "Cmt", "Paz"], meals: ["Akşam", "Öğle", "Akşam", "Akşam", "Öğle", "Akşam", "Öğle"], quickPrompts: ["20 dakikada dengeli akşam", "Kilerimdekileri değerlendir", "Protein odaklı hafif öğle"], ui: { today: "Bugün", discover: "Keşfet", chef: "AI Şef", plan: "Plan", profile: "Profil", all: "Tümü", exploreEyebrow: "İLHAM AL", search: "Tarif, malzeme ya da mutfak ara", recipesFound: "tarif bulundu", filter: "Filtrele", planEyebrow: "HAFTANIN RİTMİ", planTitle: "Yemek planın", autoPlan: "Haftamı otomatik planla", autoPlanText: "Seçtiğin mutfak bölgesi, kilerin ve hedeflerinle 7 günlük menü oluştur.", regionalPlan: "Bölgesel plan", switchRegion: "Bölgeyi değiştir", languageRegion: "Dil ve mutfak bölgesi", privacy: "Gizlilik ve veriler" } },
  { code: "en-GB", language: "English", region: "United Kingdom", flag: "GB", pantryHighlights: ["Potatoes", "Leeks", "Peas", "Oats"], recommendedTools: ["Oven", "Baking dish", "Large pot", "Potato masher"], planNote: "Built around hearty vegetables, tray bakes and simple home cooking.", days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"], meals: ["Dinner", "Lunch", "Dinner", "Dinner", "Lunch", "Dinner", "Lunch"], quickPrompts: ["A balanced 20-minute dinner", "Cook from my pantry", "A lighter high-protein lunch"], ui: { today: "Today", discover: "Discover", chef: "AI Chef", plan: "Plan", profile: "Profile", all: "All", exploreEyebrow: "FIND INSPIRATION", search: "Search recipes, ingredients or kitchen tools", recipesFound: "recipes found", filter: "Filter", planEyebrow: "THE WEEK AHEAD", planTitle: "Your meal plan", autoPlan: "Plan my week", autoPlanText: "Create a 7-day menu around your cuisine, pantry and goals.", regionalPlan: "Regional plan", switchRegion: "Change region", languageRegion: "Language & cuisine region", privacy: "Privacy & data" } },
  { code: "de-DE", language: "Deutsch", region: "Deutschland", flag: "DE", pantryHighlights: ["Kartoffeln", "Linsen", "Pilze", "Kohl"], recommendedTools: ["Großer Topf", "Ofen", "Pfanne", "Reibe"], planNote: "Mit saisonalem Gemüse, Kartoffeln und herzhaften Alltagsgerichten geplant.", days: ["Mo", "Di", "Mi", "Do", "Fr", "Sa", "So"], meals: ["Abendessen", "Mittagessen", "Abendessen", "Abendessen", "Mittagessen", "Abendessen", "Mittagessen"], quickPrompts: ["Ein ausgewogenes Abendessen in 20 Minuten", "Koche mit meinem Vorrat", "Ein leichtes proteinreiches Mittagessen"], ui: { today: "Heute", discover: "Entdecken", chef: "KI-Chef", plan: "Plan", profile: "Profil", all: "Alle", exploreEyebrow: "INSPIRATION", search: "Rezepte, Zutaten oder Küchenhelfer suchen", recipesFound: "Rezepte gefunden", filter: "Filtern", planEyebrow: "DEINE WOCHE", planTitle: "Dein Speiseplan", autoPlan: "Woche automatisch planen", autoPlanText: "Erstelle einen 7-Tage-Plan mit Region, Vorrat und Zielen.", regionalPlan: "Regionaler Plan", switchRegion: "Region ändern", languageRegion: "Sprache & Küchenregion", privacy: "Datenschutz & Daten" } },
  { code: "es-ES", language: "Español", region: "España", flag: "ES", pantryHighlights: ["Aceite de oliva", "Tomate", "Garbanzos", "Arroz"], recommendedTools: ["Sartén amplia", "Olla", "Bandeja de horno", "Batidora"], planNote: "Plan mediterráneo con legumbres, verduras y platos de cuchara ligeros.", days: ["Lun", "Mar", "Mié", "Jue", "Vie", "Sáb", "Dom"], meals: ["Cena", "Almuerzo", "Cena", "Cena", "Almuerzo", "Cena", "Almuerzo"], quickPrompts: ["Cena equilibrada en 20 minutos", "Aprovecha mi despensa", "Almuerzo ligero y proteico"], ui: { today: "Hoy", discover: "Descubrir", chef: "Chef IA", plan: "Plan", profile: "Perfil", all: "Todo", exploreEyebrow: "INSPÍRATE", search: "Busca recetas, ingredientes o utensilios", recipesFound: "recetas encontradas", filter: "Filtrar", planEyebrow: "EL RITMO DE LA SEMANA", planTitle: "Tu plan de comidas", autoPlan: "Planificar mi semana", autoPlanText: "Crea un menú de 7 días con tu región, despensa y objetivos.", regionalPlan: "Plan regional", switchRegion: "Cambiar región", languageRegion: "Idioma y región culinaria", privacy: "Privacidad y datos" } },
  { code: "fr-FR", language: "Français", region: "France", flag: "FR", pantryHighlights: ["Lentilles", "Poireaux", "Courgettes", "Champignons"], recommendedTools: ["Four", "Plat à gratin", "Casserole", "Poêle"], planNote: "Planifié avec des légumes de saison et des plats familiaux simples.", days: ["Lun", "Mar", "Mer", "Jeu", "Ven", "Sam", "Dim"], meals: ["Dîner", "Déjeuner", "Dîner", "Dîner", "Déjeuner", "Dîner", "Déjeuner"], quickPrompts: ["Un dîner équilibré en 20 minutes", "Cuisine avec mon garde-manger", "Un déjeuner léger riche en protéines"], ui: { today: "Aujourd’hui", discover: "Découvrir", chef: "Chef IA", plan: "Plan", profile: "Profil", all: "Tout", exploreEyebrow: "TROUVEZ L’INSPIRATION", search: "Rechercher recettes, ingrédients ou ustensiles", recipesFound: "recettes trouvées", filter: "Filtrer", planEyebrow: "LE RYTHME DE LA SEMAINE", planTitle: "Votre menu", autoPlan: "Planifier ma semaine", autoPlanText: "Créez un menu de 7 jours selon votre région, vos réserves et vos objectifs.", regionalPlan: "Plan régional", switchRegion: "Changer de région", languageRegion: "Langue et région culinaire", privacy: "Confidentialité et données" } },
] as const;

export type CuisineLocale = (typeof cuisineLocales)[number]["code"];
export type CuisineProfile = (typeof cuisineLocales)[number];
export const defaultCuisineLocale: CuisineLocale = "tr-TR";
export function getCuisineProfile(locale?: string): CuisineProfile { return cuisineLocales.find((item) => item.code === locale) ?? cuisineLocales[0]; }
export function isCuisineLocale(value: unknown): value is CuisineLocale { return typeof value === "string" && cuisineLocales.some((item) => item.code === value); }
export function getPantryLabel(locale?: CuisineLocale) { return ({ "tr-TR": "Kiler", "en-GB": "Pantry", "de-DE": "Vorrat", "es-ES": "Despensa", "fr-FR": "Garde-manger" } as Record<CuisineLocale, string>)[locale ?? defaultCuisineLocale]; }
