import type { ImageSourcePropType } from "react-native";

import { getCuisineProfile, type CuisineLocale } from "@/lib/cuisine-locale";
import { getEquipmentAdvice as getAdvice } from "@/lib/equipment-advice";
import { uniqueShoppingItems } from "@/lib/meal-planning";
import { buildPersonalWeekPlan, findPersonalMenuAlternative } from "@/lib/personal-menu";
import { getCurrentSeason, recipeMatchesDiet, type DietaryPreference, type DietaryTag, type Season } from "@/lib/seasonal-market";
import { regionalRecipeExpansion } from "@/lib/regional-recipe-expansion";

export type Recipe = {
  id: string; cuisine: CuisineLocale; title: string; subtitle: string; category: string; minutes: number; calories: number; protein: number; carbs: number; fat: number; estimatedCost: number; difficulty: "Kolay" | "Orta"; tools: string[]; toolTimes: Record<string, number>; fallbackMethod: string; image: ImageSourcePropType; accent: string; ingredients: string[]; steps: string[]; tags: string[]; dietaryTags: DietaryTag[]; seasons: Season[];
};

const images = [
  require("../assets/images/food/enerji-kasesi.jpg"),
  require("../assets/images/food/firin-domates.jpg"),
  require("../assets/images/food/mezze.jpg"),
  require("../assets/images/food/akdeniz-tabagi.jpg"),
];

const recipeMeta: Record<string, { dietaryTags: DietaryTag[]; seasons: Season[] }> = {
  "tr-mercimek": { dietaryTags: ["vegan", "gluten-free"], seasons: ["winter", "autumn"] }, "tr-fasulye": { dietaryTags: ["vegan", "gluten-free"], seasons: ["summer"] }, "tr-bulgur": { dietaryTags: ["vegetarian"], seasons: ["summer", "autumn"] }, "tr-kofte": { dietaryTags: ["gluten-free"], seasons: ["summer", "autumn"] },
  "en-shepherds-pie": { dietaryTags: ["vegetarian", "gluten-free"], seasons: ["autumn", "winter"] }, "en-leek-soup": { dietaryTags: ["vegetarian", "gluten-free"], seasons: ["winter", "spring"] }, "en-traybake": { dietaryTags: ["vegan", "gluten-free"], seasons: ["summer", "autumn"] }, "en-cod-peas": { dietaryTags: ["gluten-free"], seasons: ["spring", "summer"] },
  "de-linseneintopf": { dietaryTags: ["vegan", "gluten-free"], seasons: ["autumn", "winter"] }, "de-pilz-spaetzle": { dietaryTags: ["vegetarian"], seasons: ["spring", "autumn"] }, "de-ofengemuese": { dietaryTags: ["vegetarian", "gluten-free"], seasons: ["summer", "autumn"] }, "de-spargel-risotto": { dietaryTags: ["vegetarian", "gluten-free"], seasons: ["spring"] },
  "es-garbanzos": { dietaryTags: ["vegan", "gluten-free"], seasons: ["spring", "winter"] }, "es-tortilla": { dietaryTags: ["vegetarian", "gluten-free"], seasons: ["spring", "summer"] }, "es-paella": { dietaryTags: ["vegan", "gluten-free"], seasons: ["summer", "autumn"] }, "es-gazpacho": { dietaryTags: ["vegan"], seasons: ["summer"] },
  "fr-ratatouille": { dietaryTags: ["vegan", "gluten-free"], seasons: ["summer"] }, "fr-potage": { dietaryTags: ["vegetarian", "gluten-free"], seasons: ["winter", "spring"] }, "fr-quiche": { dietaryTags: ["vegetarian"], seasons: ["spring", "autumn"] }, "fr-lentilles": { dietaryTags: ["vegan", "gluten-free"], seasons: ["autumn", "winter"] },
  "tr-enginar": { dietaryTags: ["vegan", "gluten-free"], seasons: ["spring"] }, "tr-imam": { dietaryTags: ["vegan", "gluten-free"], seasons: ["summer"] }, "tr-kabak": { dietaryTags: ["vegan", "gluten-free"], seasons: ["autumn"] }, "tr-pirasa": { dietaryTags: ["vegan", "gluten-free"], seasons: ["winter"] },
  "en-asparagus": { dietaryTags: ["vegetarian"], seasons: ["spring"] }, "en-summer-salad": { dietaryTags: ["vegan", "gluten-free"], seasons: ["summer"] }, "en-squash": { dietaryTags: ["vegan", "gluten-free"], seasons: ["autumn"] }, "en-cabbage": { dietaryTags: ["vegan", "gluten-free"], seasons: ["winter"] },
  "de-spargel": { dietaryTags: ["vegan", "gluten-free"], seasons: ["spring"] }, "de-zucchini": { dietaryTags: ["vegan", "gluten-free"], seasons: ["summer"] }, "de-kuerbis": { dietaryTags: ["vegan", "gluten-free"], seasons: ["autumn"] }, "de-kohl": { dietaryTags: ["vegan", "gluten-free"], seasons: ["winter"] },
  "es-habas": { dietaryTags: ["vegan", "gluten-free"], seasons: ["spring"] }, "es-pisto": { dietaryTags: ["vegan", "gluten-free"], seasons: ["summer"] }, "es-calabaza": { dietaryTags: ["vegan", "gluten-free"], seasons: ["autumn"] }, "es-judias": { dietaryTags: ["vegan", "gluten-free"], seasons: ["winter"] },
  "fr-asperges": { dietaryTags: ["vegan", "gluten-free"], seasons: ["spring"] }, "fr-tian": { dietaryTags: ["vegan", "gluten-free"], seasons: ["summer"] }, "fr-potimarron": { dietaryTags: ["vegan", "gluten-free"], seasons: ["autumn"] }, "fr-chou": { dietaryTags: ["vegan", "gluten-free"], seasons: ["winter"] },
};

function makeRecipe(cuisine: CuisineLocale, id: string, title: string, subtitle: string, category: string, minutes: number, calories: number, protein: number, tools: string[], ingredients: string[], steps: string[], imageIndex: number, explicitMeta?: { dietaryTags: DietaryTag[]; seasons: Season[] }): Recipe {
  const meta = explicitMeta ?? recipeMeta[id] ?? { dietaryTags: [] as DietaryTag[], seasons: ["spring", "summer", "autumn", "winter"] as Season[] };
  return { id, cuisine, title, subtitle, category, minutes, calories, protein, carbs: Math.max(20, Math.round(calories * 0.11)), fat: Math.max(8, Math.round(calories * 0.035)), estimatedCost: Math.round(75 + calories * 0.28), difficulty: minutes > 34 ? "Orta" : "Kolay", tools, toolTimes: Object.fromEntries(tools.map((tool) => [tool, minutes])), fallbackMethod: "Use a covered pan over a gentle heat as a simple alternative.", image: images[imageIndex % images.length], accent: ["#DDE8DA", "#FCE6D2", "#F9E2DB", "#E0ECE8"][imageIndex % 4], ingredients, steps, tags: [cuisine, category, `${minutes} dk`], dietaryTags: meta.dietaryTags, seasons: meta.seasons };
}

export const recipes: Recipe[] = [
  makeRecipe("tr-TR", "tr-mercimek", "Mercimek Çorbası", "Kimyonlu, limonlu ev çorbası", "Çorba", 32, 330, 17, ["Tencere", "Blender"], ["Kırmızı mercimek", "Soğan", "Havuç", "Kimyon", "Limon"], ["Soğan ve havucu yumuşat.", "Mercimeği ekleyip pişir.", "Blenderdan geçirip limonla servis et."], 0),
  makeRecipe("tr-TR", "tr-fasulye", "Zeytinyağlı Taze Fasulye", "Domatesli ve hafif", "Zeytinyağlı", 40, 290, 9, ["Tencere"], ["Taze fasulye", "Domates", "Soğan", "Zeytinyağı"], ["Soğanı zeytinyağında çevir.", "Fasulye ve domatesi ekle.", "Kısık ateşte yumuşat."], 2),
  makeRecipe("tr-TR", "tr-bulgur", "Sebzeli Bulgur Pilavı", "Biber, domates ve yoğurtla", "Hızlı", 26, 410, 13, ["Tencere", "Tava"], ["Bulgur", "Domates", "Yeşil biber", "Yoğurt"], ["Sebzeleri sotele.", "Bulgur ve suyu ekle.", "Demlendirip yoğurtla sun."], 1),
  makeRecipe("tr-TR", "tr-kofte", "Fırın Köfte ve Sebze", "Patates, kabak ve domatesle", "Akşam", 38, 540, 34, ["Fırın", "Air Fryer"], ["Köfte", "Patates", "Kabak", "Domates"], ["Sebzeleri tepsiye yay.", "Köfteleri baharatla.", "Kızarana kadar fırınla."], 3),
  makeRecipe("en-GB", "en-shepherds-pie", "Vegetable Shepherd’s Pie", "Lentils, peas and a golden potato topping", "Comfort dinner", 42, 520, 23, ["Oven", "Large pot", "Potato masher"], ["Green lentils", "Potatoes", "Peas", "Carrots", "Cheddar"], ["Cook lentils with carrots and peas.", "Mash the potatoes until smooth.", "Layer and bake until golden."], 3),
  makeRecipe("en-GB", "en-leek-soup", "Leek & Potato Soup", "A creamy weekday soup with oats", "Soup", 30, 345, 13, ["Large pot", "Blender"], ["Leeks", "Potatoes", "Oats", "Vegetable stock"], ["Soften leeks in a pot.", "Simmer with potato and stock.", "Blend until smooth."], 0),
  makeRecipe("en-GB", "en-traybake", "Roasted Veg Tray Bake", "Root vegetables, beans and herbs", "Tray bake", 35, 430, 18, ["Oven", "Tray"], ["Carrots", "Parsnips", "Potatoes", "White beans"], ["Season vegetables with herbs.", "Roast until caramelised.", "Fold in warm beans."], 2),
  makeRecipe("en-GB", "en-cod-peas", "Baked Cod with Peas", "Lemon potatoes and garden peas", "Dinner", 28, 505, 37, ["Oven", "Tray"], ["Cod", "Potatoes", "Peas", "Lemon"], ["Roast lemon potatoes.", "Add cod and peas.", "Bake until the fish flakes."], 1),
  makeRecipe("de-DE", "de-linseneintopf", "Linseneintopf", "Herzhafter Linsentopf mit Wurzelgemüse", "Eintopf", 38, 445, 24, ["Großer Topf"], ["Linsen", "Kartoffeln", "Karotten", "Sellerie"], ["Gemüse klein schneiden.", "Linsen und Brühe zugeben.", "Sanft köcheln lassen."], 0),
  makeRecipe("de-DE", "de-pilz-spaetzle", "Pilz-Spätzle", "Mit Kräutern und einer leichten Rahmsauce", "Pfannengericht", 25, 530, 20, ["Pfanne", "Großer Topf"], ["Spätzle", "Champignons", "Zwiebel", "Schnittlauch"], ["Spätzle kurz kochen.", "Pilze goldbraun braten.", "Mit Kräutern verbinden."], 1),
  makeRecipe("de-DE", "de-ofengemuese", "Ofengemüse mit Kräuterquark", "Kartoffeln, Rote Bete und saisonales Gemüse", "Ofengericht", 36, 425, 19, ["Ofen", "Backblech"], ["Kartoffeln", "Rote Bete", "Karotten", "Quark"], ["Gemüse würzen.", "Auf dem Blech rösten.", "Mit Kräuterquark servieren."], 2),
  makeRecipe("de-DE", "de-spargel-risotto", "Spargel-Risotto", "Cremiger Reis mit grünem Spargel", "Saisonal", 33, 485, 16, ["Großer Topf", "Pfanne"], ["Risottoreis", "Grüner Spargel", "Parmesan", "Zitrone"], ["Reis glasig dünsten.", "Brühe nach und nach einrühren.", "Spargel und Parmesan unterheben."], 3),
  makeRecipe("es-ES", "es-garbanzos", "Espinacas con Garbanzos", "Garbanzos y espinacas con ajo y pimentón", "Legumbres", 24, 410, 19, ["Sartén amplia", "Olla"], ["Garbanzos", "Espinacas", "Ajo", "Pimentón"], ["Dora el ajo.", "Añade garbanzos y pimentón.", "Incorpora las espinacas."], 0),
  makeRecipe("es-ES", "es-tortilla", "Tortilla de Patatas y Verduras", "Patata, calabacín y huevo en una sartén", "Sartén", 30, 470, 22, ["Sartén amplia"], ["Patatas", "Calabacín", "Huevos", "Cebolla"], ["Cocina patata y calabacín.", "Mezcla con huevo.", "Cuaja por ambos lados."], 1),
  makeRecipe("es-ES", "es-paella", "Paella de Verduras", "Arroz con judías, pimiento y azafrán", "Arroz", 36, 465, 15, ["Sartén amplia"], ["Arroz", "Judías verdes", "Pimiento", "Azafrán"], ["Prepara un sofrito.", "Añade arroz y caldo.", "Cocina sin remover."], 3),
  makeRecipe("es-ES", "es-gazpacho", "Gazpacho con Tostada", "Sopa fría de tomate con garbanzos crujientes", "Ligero", 18, 350, 14, ["Batidora", "Sartén"], ["Tomates", "Pepino", "Pimiento", "Garbanzos"], ["Tritura las verduras.", "Tuesta los garbanzos.", "Sirve frío."], 2),
  makeRecipe("fr-FR", "fr-ratatouille", "Ratatouille Provençale", "Légumes mijotés à l’huile d’olive et aux herbes", "Légumes", 38, 360, 12, ["Casserole", "Poêle"], ["Aubergine", "Courgette", "Tomates", "Poivron"], ["Faire revenir les légumes.", "Ajouter tomates et herbes.", "Laisser mijoter."], 2),
  makeRecipe("fr-FR", "fr-potage", "Potage Poireaux-Pommes de Terre", "Velouté simple et réconfortant", "Soupe", 30, 335, 13, ["Casserole", "Blender"], ["Poireaux", "Pommes de terre", "Bouillon", "Ciboulette"], ["Faire fondre les poireaux.", "Ajouter pommes de terre et bouillon.", "Mixer doucement."], 0),
  makeRecipe("fr-FR", "fr-quiche", "Quiche aux Légumes", "Courgette, champignons et fromage", "Four", 40, 515, 25, ["Four", "Plat à gratin"], ["Pâte brisée", "Courgette", "Champignons", "Œufs"], ["Garnir la pâte.", "Ajouter les œufs et le fromage.", "Cuire jusqu’à dorure."], 1),
  makeRecipe("fr-FR", "fr-lentilles", "Salade de Lentilles", "Carottes rôties et vinaigrette moutardée", "Léger", 27, 430, 22, ["Casserole", "Four"], ["Lentilles", "Carottes", "Moutarde", "Persil"], ["Cuire les lentilles.", "Rôtir les carottes.", "Mélanger avec la vinaigrette."], 3),
  makeRecipe("tr-TR", "tr-enginar", "Zeytinyağlı Enginar", "Bakla ve dereotuyla Ege usulü", "İlkbahar", 35, 315, 10, ["Tencere"], ["Enginar", "Bakla", "Bezelye", "Dereotu", "Limon"], ["Enginarları limonlu suya al.", "Bakla ve bezelyeyi ekle.", "Zeytinyağıyla kısık ateşte pişir."], 0),
  makeRecipe("tr-TR", "tr-imam", "İmam Bayıldı", "Domatesli soğanlı yaz patlıcanı", "Yaz", 48, 370, 8, ["Fırın", "Tava"], ["Patlıcan", "Soğan", "Domates", "Sarımsak", "Zeytinyağı"], ["Patlıcanları yumuşat.", "Soğanlı harcı hazırla.", "Fırında dinlendirerek pişir."], 2),
  makeRecipe("tr-TR", "tr-kabak", "Balkabaklı Nohut Güveç", "Baharatlı, tok tutan sonbahar tabağı", "Sonbahar", 42, 455, 16, ["Fırın", "Tencere"], ["Balkabağı", "Nohut", "Soğan", "Kimyon", "Ispanak"], ["Soğanı baharatlarla çevir.", "Kabak ve nohutu ekle.", "Fırında yumuşayana dek pişir."], 3),
  makeRecipe("tr-TR", "tr-pirasa", "Portakallı Pırasa", "Havuçlu, hafif kış tenceresi", "Kış", 32, 295, 9, ["Tencere"], ["Pırasa", "Havuç", "Pirinç", "Portakal", "Zeytinyağı"], ["Pırasayı halka halka doğra.", "Havuç ve pirinci ekle.", "Portakal suyuyla yavaşça pişir."], 1),
  makeRecipe("en-GB", "en-asparagus", "Asparagus & Pea Tart", "A spring tart with herbs and a crisp base", "Spring", 38, 440, 17, ["Oven", "Tray"], ["Asparagus", "Peas", "Eggs", "Cheddar", "Herbs"], ["Blanch the asparagus.", "Fill the pastry with peas and egg.", "Bake until set and golden."], 1),
  makeRecipe("en-GB", "en-summer-salad", "Summer Bean Salad", "Runner beans, tomatoes and lemon dressing", "Summer", 20, 325, 14, ["Large pot", "Bowl"], ["Runner beans", "Tomatoes", "New potatoes", "Lemon", "Parsley"], ["Boil the beans and potatoes.", "Chop tomatoes and herbs.", "Toss with lemon dressing."], 2),
  makeRecipe("en-GB", "en-squash", "Autumn Squash Stew", "Squash, lentils and warming herbs", "Autumn", 38, 435, 19, ["Large pot"], ["Squash", "Red lentils", "Carrots", "Kale", "Thyme"], ["Soften the vegetables.", "Add lentils and stock.", "Simmer until the squash is tender."], 0),
  makeRecipe("en-GB", "en-cabbage", "Winter Cabbage Pot", "Cabbage, leeks and buttery beans", "Winter", 34, 410, 18, ["Large pot"], ["Cabbage", "Leeks", "White beans", "Carrots", "Mustard"], ["Sweat leeks and carrots.", "Add cabbage and beans.", "Cook gently until soft."], 3),
  makeRecipe("de-DE", "de-spargel", "Spargel mit Kartoffeln", "Grüner Spargel, neue Kartoffeln und Zitronenkräuter", "Frühling", 28, 390, 13, ["Pfanne", "Großer Topf"], ["Spargel", "Kartoffeln", "Erbsen", "Zitrone", "Schnittlauch"], ["Kartoffeln kochen.", "Spargel in der Pfanne braten.", "Mit Erbsen und Zitrone servieren."], 1),
  makeRecipe("de-DE", "de-zucchini", "Zucchini-Bohnen-Pfanne", "Leichte Sommerpfanne mit Kräutern", "Sommer", 24, 360, 15, ["Pfanne"], ["Zucchini", "Bohnen", "Tomaten", "Zwiebel", "Basilikum"], ["Zwiebel anbraten.", "Zucchini und Bohnen zugeben.", "Tomaten kurz mitgaren."], 2),
  makeRecipe("de-DE", "de-kuerbis", "Kürbis-Linsen-Eintopf", "Wärmender Topf mit Wurzelgemüse", "Herbst", 40, 450, 20, ["Großer Topf"], ["Kürbis", "Linsen", "Karotten", "Sellerie", "Thymian"], ["Gemüse würfeln.", "Linsen und Brühe zugeben.", "Sanft köcheln lassen."], 0),
  makeRecipe("de-DE", "de-kohl", "Kohl-Kartoffel-Topf", "Deftiger Wintertopf mit weißen Bohnen", "Winter", 36, 420, 18, ["Großer Topf"], ["Kohl", "Kartoffeln", "Lauch", "Weiße Bohnen", "Karotten"], ["Lauch und Karotten anschwitzen.", "Kartoffeln und Kohl zugeben.", "Mit Bohnen fertig garen."], 3),
  makeRecipe("es-ES", "es-habas", "Habas con Alcachofas", "Habitas tiernas, alcachofas y limón", "Primavera", 28, 385, 16, ["Sartén amplia"], ["Habas", "Alcachofas", "Ajo", "Limón", "Perejil"], ["Saltea el ajo.", "Añade habas y alcachofas.", "Termina con limón y perejil."], 1),
  makeRecipe("es-ES", "es-pisto", "Pisto Manchego", "Verduras de verano con tomate y pimiento", "Verano", 32, 340, 11, ["Sartén amplia"], ["Tomates", "Calabacín", "Pimientos", "Berenjenas", "Cebolla"], ["Sofríe la cebolla.", "Añade las verduras en dados.", "Cocina hasta que estén suaves."], 2),
  makeRecipe("es-ES", "es-calabaza", "Calabaza con Garbanzos", "Guiso otoñal con espinacas y pimentón", "Otoño", 35, 440, 18, ["Olla"], ["Calabaza", "Garbanzos", "Espinacas", "Ajo", "Pimentón"], ["Dora el ajo y pimentón.", "Añade calabaza y garbanzos.", "Incorpora espinacas al final."], 0),
  makeRecipe("es-ES", "es-judias", "Judías Blancas de Invierno", "Alubias, acelgas y verduras de cuchara", "Invierno", 38, 430, 19, ["Olla"], ["Judías blancas", "Acelga", "Zanahoria", "Apio", "Tomate"], ["Prepara un sofrito suave.", "Añade verduras y alubias.", "Cuece hasta que espese."], 3),
  makeRecipe("fr-FR", "fr-asperges", "Poêlée d’Asperges et Petits Pois", "Herbes fraîches et citron pour le printemps", "Printemps", 25, 320, 13, ["Poêle"], ["Asperges", "Petits pois", "Poireaux", "Citron", "Estragon"], ["Faire fondre les poireaux.", "Ajouter asperges et petits pois.", "Finir avec citron et estragon."], 1),
  makeRecipe("fr-FR", "fr-tian", "Tian de Légumes", "Courgette, tomate et aubergine au four", "Été", 42, 355, 10, ["Four", "Plat à gratin"], ["Courgettes", "Tomates", "Aubergine", "Ail", "Herbes"], ["Trancher les légumes.", "Les disposer dans le plat.", "Cuire doucement au four."], 2),
  makeRecipe("fr-FR", "fr-potimarron", "Potimarron aux Lentilles", "Plat d’automne aux carottes rôties", "Automne", 38, 445, 20, ["Casserole", "Four"], ["Potimarron", "Lentilles", "Carottes", "Oignon", "Thym"], ["Rôtir le potimarron.", "Cuire les lentilles.", "Assembler avec thym et oignon."], 0),
  makeRecipe("fr-FR", "fr-chou", "Mijoté de Chou et Haricots", "Un plat d’hiver aux légumes doux", "Hiver", 36, 410, 18, ["Casserole"], ["Chou", "Haricots blancs", "Carottes", "Poireaux", "Moutarde"], ["Faire revenir les poireaux.", "Ajouter chou et carottes.", "Mijoter avec les haricots."], 3),
  ...regionalRecipeExpansion.map((item) => makeRecipe(item.cuisine, item.id, item.title, item.subtitle, item.category, item.minutes, item.calories, item.protein, item.tools, item.ingredients, item.steps, item.imageIndex, { dietaryTags: item.dietaryTags, seasons: item.seasons })),
];

export function getRecipesForLocale(locale?: CuisineLocale) { return recipes.filter((item) => item.cuisine === (locale ?? "tr-TR")); }
export function getRecipesForPreferences(locale: CuisineLocale, dietaryPreferences: DietaryPreference[] = [], season: Season = getCurrentSeason()) { const local = getRecipesForLocale(locale); const dietMatched = local.filter((recipe) => recipeMatchesDiet(recipe.dietaryTags, dietaryPreferences)); const seasonal = dietMatched.filter((recipe) => recipe.seasons.includes(season)); return seasonal.length ? seasonal : dietMatched; }
export function getCategoriesForLocale(locale?: CuisineLocale) { const profile = getCuisineProfile(locale); return [profile.ui.all, ...Array.from(new Set(getRecipesForLocale(profile.code).map((item) => item.category)))]; }
export const categories = getCategoriesForLocale("tr-TR");
export const initialPantry = ["Nohut", "Yumurta", "Roka", "Yoğurt", "Limon", "Domates"];
export const initialWeeklyPlan = [{ day: "Pzt", meal: "Akşam", recipeId: "tr-mercimek" }, { day: "Sal", meal: "Öğle", recipeId: "tr-fasulye" }, { day: "Çar", meal: "Akşam", recipeId: "tr-bulgur" }, { day: "Per", meal: "Akşam", recipeId: "tr-kofte" }];
export function buildPersonalWeeklyPlan(input: { pantry: string[]; favoriteIngredients: string[]; goal: string; allergies: string[]; kitchenTools: string[]; locale?: CuisineLocale; dietaryPreferences?: DietaryPreference[]; season?: Season }) { const profile = getCuisineProfile(input.locale); return buildPersonalWeekPlan(getRecipesForPreferences(profile.code, input.dietaryPreferences, input.season), input, { days: profile.days, meals: profile.meals }); }
export function getPersonalRecipeAlternative(input: { pantry: string[]; favoriteIngredients: string[]; goal: string; allergies: string[]; kitchenTools: string[]; locale?: CuisineLocale; dietaryPreferences?: DietaryPreference[]; season?: Season }, currentRecipeId: string, occupiedRecipeIds: string[]) { return findPersonalMenuAlternative(getRecipesForPreferences(getCuisineProfile(input.locale).code, input.dietaryPreferences, input.season), input, currentRecipeId, occupiedRecipeIds); }
export function getEquipmentAdvice(recipe: Recipe, kitchenTools: string[]) { return getAdvice(recipe, kitchenTools); }
export function buildGroceryList(recipeIds: string[]) { return uniqueShoppingItems(recipeIds.map((id) => recipes.find((item) => item.id === id)).filter((item): item is Recipe => Boolean(item))).map((name) => ({ name, checked: false })); }
export function getRecipe(id?: string) { return recipes.find((item) => item.id === id) ?? getRecipesForLocale("tr-TR")[0]; }
