import type { CuisineLocale } from "./cuisine-locale";

type SampleCopy = { title: string; text: string; addTitle: string; addText: string; emptyTitle: string; emptyText: string; editTitle: string; editText: string; addItem: string; itemPlaceholder: string; remove: string; apply: string };

const copy: Record<CuisineLocale, SampleCopy> = {
  "tr-TR": { title: "Kilerini birlikte başlatalım.", text: "İstersen seçtiğin bölgenin mutfağına uygun örnek ürünleri ekleyerek uygulamayı hemen deneyebilirsin.", addTitle: "Örnek kilerle başla", addText: "Bölgesel malzemeleri ekle", emptyTitle: "Boş kilerle devam et", emptyText: "Ürünlerimi kendim ekleyeceğim", editTitle: "Örnek kilerini düzenle.", editText: "Yüklemeden önce ürünleri kaldırabilir, adlarını ve miktarlarını değiştirebilirsin.", addItem: "Ürün ekle", itemPlaceholder: "Yeni ürün adı", remove: "Kaldır", apply: "Bu kileri yükle" },
  "en-GB": { title: "Let’s start your pantry together.", text: "If you like, add sample products suited to your selected cuisine region and try the app straight away.", addTitle: "Start with a sample pantry", addText: "Add regional ingredients", emptyTitle: "Continue with an empty pantry", emptyText: "I’ll add my own products", editTitle: "Edit your sample pantry.", editText: "Before loading, remove products or change their names and quantities.", addItem: "Add product", itemPlaceholder: "New product name", remove: "Remove", apply: "Load this pantry" },
  "de-DE": { title: "Starten wir deinen Vorrat gemeinsam.", text: "Wenn du möchtest, fügen wir Beispielprodukte passend zu deiner Küchenregion hinzu, damit du die App sofort ausprobieren kannst.", addTitle: "Mit Beispielvorrat starten", addText: "Regionale Zutaten hinzufügen", emptyTitle: "Mit leerem Vorrat fortfahren", emptyText: "Ich füge eigene Produkte hinzu", editTitle: "Beispielvorrat bearbeiten.", editText: "Vor dem Laden kannst du Produkte entfernen sowie Namen und Mengen ändern.", addItem: "Produkt hinzufügen", itemPlaceholder: "Neuer Produktname", remove: "Entfernen", apply: "Diesen Vorrat laden" },
  "es-ES": { title: "Empecemos tu despensa juntos.", text: "Si quieres, añade productos de ejemplo para tu región culinaria y prueba la aplicación enseguida.", addTitle: "Empezar con una despensa de ejemplo", addText: "Añadir ingredientes regionales", emptyTitle: "Continuar con la despensa vacía", emptyText: "Añadiré mis propios productos", editTitle: "Edita tu despensa de ejemplo.", editText: "Antes de cargarla, puedes quitar productos o cambiar sus nombres y cantidades.", addItem: "Añadir producto", itemPlaceholder: "Nombre del producto", remove: "Quitar", apply: "Cargar esta despensa" },
  "fr-FR": { title: "Commençons votre garde-manger ensemble.", text: "Si vous le souhaitez, ajoutez des produits d’exemple adaptés à votre région culinaire pour essayer l’application immédiatement.", addTitle: "Commencer avec un garde-manger d’exemple", addText: "Ajouter des ingrédients régionaux", emptyTitle: "Continuer avec un garde-manger vide", emptyText: "J’ajouterai mes propres produits", editTitle: "Modifiez votre garde-manger d’exemple.", editText: "Avant de le charger, vous pouvez retirer des produits ou modifier leurs noms et quantités.", addItem: "Ajouter un produit", itemPlaceholder: "Nom du nouveau produit", remove: "Retirer", apply: "Charger ce garde-manger" },
};

export function getOnboardingSampleCopy(locale: CuisineLocale) { return copy[locale]; }
