import type { CuisineLocale } from "./cuisine-locale";

export type OnboardingCopy = {
  welcome: string;
  headings: readonly string[];
  subheadings: readonly string[];
  guides: readonly { title: string; text: string }[];
  goals: readonly string[];
  allergies: readonly string[];
  energyLabel: string;
  peopleLabel: string;
  peopleHint: string;
  continue: string;
  start: string;
  back: string;
  privacy: string;
};

const copy: Record<CuisineLocale, OnboardingCopy> = {
  "tr-TR": { welcome: "LEZZETAI’YE HOŞ GELDİN", headings: ["Mutfağının dilini seç.", "Kilerini kolayca düzenle.", "AI Şef’le fikir üret.", "Haftanı daha akıllı planla.", "Yemeklerin sana uyum sağlasın.", "Nelerden uzak duralım?", "Ritmini birlikte belirleyelim."], subheadings: ["Bu seçim; tarifleri, haftalık planı, kiler odaklarını ve önerilen araçları bölgesine göre şekillendirir.", "Yazarak, fotoğrafla, fişten veya barkodla ürün ekle. Düşük stok ve yaklaşan son kullanma tarihlerini tek yerde takip et.", "Elindeki malzemeleri, süreni ve mutfak araçlarını söyle; AI Şef bölgesel bağlamı da dikkate alan tarif seçenekleri hazırlasın.", "Kilerindeki malzemelere göre yedi günlük fikir al, eksikleri gör ve planını ailenle paylaş.", "Hedefini bilerek her gün daha isabetli öneriler hazırlayalım.", "Alerjenlerini hatırlayalım; AI Şef bunları tariflerinde dikkate alsın.", "Bu ayarları dilediğin zaman Profil’den değiştirebilirsin."], guides: [{ title: "Kiler", text: "Stoklarını takip et; israfı azaltmaya yardımcı olan önerileri ve alışveriş hatırlatmalarını gör." }, { title: "AI Şef", text: "Bir yemek fikrini ayrıntılı tarife dönüştür; istersen yalnızca kilerindeki ürünleri kullansın." }, { title: "Haftalık plan", text: "Bölgesel tarifleri, diyet tercihlerini ve kiler eşleşmelerini bir haftalık menüde birleştir." }], goals: ["Dengeli beslenme", "Kilo kontrolü", "Protein odağı", "Daha çok sebze"], allergies: ["Fıstık", "Gluten", "Süt ürünleri", "Yumurta", "Kabuklu deniz ürünü", "Yok"], energyLabel: "Günlük enerji hedefi", peopleLabel: "Kaç kişilik plan yapalım?", peopleHint: "1–12 kişi için menü ve alışveriş miktarı ayarlanır.", continue: "Devam et", start: "LezzetAI’yi keşfet", back: "Geri", privacy: "Tercihlerin cihazında saklanır." },
  "en-GB": { welcome: "WELCOME TO LEZZETAI", headings: ["Choose your kitchen language.", "Organise your pantry with ease.", "Create ideas with AI Chef.", "Plan your week more intelligently.", "Make meals work for you.", "What should we avoid?", "Set your rhythm together."], subheadings: ["This choice shapes recipes, weekly plans, pantry priorities and suggested tools for your region.", "Add products by typing, photo, receipt or barcode. Track low stock and approaching use-by dates in one place.", "Tell AI Chef your ingredients, time and kitchen tools; it prepares recipe ideas with your regional context in mind.", "Get seven-day ideas from your pantry, see what may be missing and share your plan with your family.", "Knowing your goal helps us prepare more relevant suggestions each day.", "Remember your allergens so AI Chef can consider them in recipe suggestions.", "You can change these settings at any time in Profile."], guides: [{ title: "Pantry", text: "Track your stock, waste-reducing ideas and shopping reminders." }, { title: "AI Chef", text: "Turn a meal idea into a detailed recipe, optionally using only your pantry ingredients." }, { title: "Weekly plan", text: "Bring regional recipes, dietary preferences and pantry matches together in a weekly menu." }], goals: ["Balanced eating", "Weight management", "Protein focus", "More vegetables"], allergies: ["Peanuts", "Gluten", "Dairy", "Eggs", "Shellfish", "None"], energyLabel: "Daily energy target", peopleLabel: "How many people are you planning for?", peopleHint: "Menu and shopping quantities adjust for 1–12 people.", continue: "Continue", start: "Explore LezzetAI", back: "Back", privacy: "Your preferences are stored on this device." },
  "de-DE": { welcome: "WILLKOMMEN BEI LEZZETAI", headings: ["Wähle deine Küchensprache.", "Organisiere deinen Vorrat einfach.", "Finde Ideen mit dem KI-Chef.", "Plane deine Woche klüger.", "Passe Mahlzeiten an dich an.", "Was sollen wir vermeiden?", "Finde gemeinsam deinen Rhythmus."], subheadings: ["Diese Auswahl gestaltet Rezepte, Wochenpläne, Vorratsprioritäten und empfohlene Geräte für deine Region.", "Füge Produkte per Text, Foto, Kassenbon oder Barcode hinzu. Behalte niedrige Bestände und Verbrauchsdaten im Blick.", "Nenne dem KI-Chef Zutaten, Zeit und Küchengeräte; er erstellt Rezeptideen mit regionalem Kontext.", "Erhalte Sieben-Tage-Ideen aus deinem Vorrat, sieh mögliche fehlende Zutaten und teile deinen Plan mit der Familie.", "Wenn wir dein Ziel kennen, können wir passendere tägliche Vorschläge machen.", "Merke dir Allergene, damit der KI-Chef sie in Rezeptvorschlägen berücksichtigen kann.", "Diese Einstellungen kannst du jederzeit im Profil ändern."], guides: [{ title: "Vorrat", text: "Behalte Bestände, Vorschläge gegen Verschwendung und Einkaufs-Erinnerungen im Blick." }, { title: "KI-Chef", text: "Verwandle eine Idee in ein detailliertes Rezept – auf Wunsch nur mit Vorratszutaten." }, { title: "Wochenplan", text: "Verbinde regionale Rezepte, Ernährungspräferenzen und Vorrats-Treffer zu einem Wochenmenü." }], goals: ["Ausgewogene Ernährung", "Gewichtsmanagement", "Protein-Fokus", "Mehr Gemüse"], allergies: ["Erdnüsse", "Gluten", "Milchprodukte", "Eier", "Schalentiere", "Keine"], energyLabel: "Tägliches Energieziel", peopleLabel: "Für wie viele Personen planst du?", peopleHint: "Menü und Einkaufsmenge passen sich 1–12 Personen an.", continue: "Weiter", start: "LezzetAI entdecken", back: "Zurück", privacy: "Deine Präferenzen werden auf diesem Gerät gespeichert." },
  "es-ES": { welcome: "BIENVENIDO A LEZZETAI", headings: ["Elige el idioma de tu cocina.", "Organiza tu despensa fácilmente.", "Crea ideas con el Chef IA.", "Planifica tu semana mejor.", "Haz que las comidas se adapten a ti.", "¿Qué debemos evitar?", "Definamos juntos tu ritmo."], subheadings: ["Esta elección adapta las recetas, planes semanales, prioridades de despensa y utensilios sugeridos a tu región.", "Añade productos escribiendo, con foto, ticket o código de barras. Sigue el stock bajo y las fechas de caducidad.", "Dile al Chef IA tus ingredientes, tiempo y utensilios; prepara ideas de receta teniendo en cuenta tu región.", "Obtén ideas de siete días desde tu despensa, ve qué puede faltar y comparte tu plan con tu familia.", "Conocer tu objetivo nos ayuda a ofrecer sugerencias más relevantes cada día.", "Guarda tus alérgenos para que el Chef IA pueda considerarlos en las recetas.", "Puedes cambiar estos ajustes en cualquier momento desde Perfil."], guides: [{ title: "Despensa", text: "Controla tus existencias, ideas para reducir desperdicios y recordatorios de compra." }, { title: "Chef IA", text: "Convierte una idea de comida en una receta detallada, incluso solo con productos de tu despensa." }, { title: "Plan semanal", text: "Combina recetas regionales, preferencias dietéticas y coincidencias de despensa en un menú semanal." }], goals: ["Alimentación equilibrada", "Control de peso", "Enfoque en proteína", "Más verduras"], allergies: ["Cacahuetes", "Gluten", "Lácteos", "Huevos", "Mariscos", "Ninguno"], energyLabel: "Objetivo diario de energía", peopleLabel: "¿Para cuántas personas planificamos?", peopleHint: "El menú y la compra se ajustan para 1–12 personas.", continue: "Continuar", start: "Explorar LezzetAI", back: "Atrás", privacy: "Tus preferencias se guardan en este dispositivo." },
  "fr-FR": { welcome: "BIENVENUE DANS LEZZETAI", headings: ["Choisissez la langue de votre cuisine.", "Organisez facilement votre garde-manger.", "Créez des idées avec Chef IA.", "Planifiez votre semaine plus intelligemment.", "Adaptez les repas à vos besoins.", "Que devons-nous éviter ?", "Définissons votre rythme ensemble."], subheadings: ["Ce choix adapte les recettes, menus hebdomadaires, priorités du garde-manger et ustensiles suggérés à votre région.", "Ajoutez des produits par saisie, photo, ticket ou code-barres. Suivez les stocks bas et les dates limites.", "Indiquez vos ingrédients, votre temps et vos ustensiles à Chef IA ; il prépare des idées tenant compte de votre région.", "Obtenez des idées sur sept jours depuis votre garde-manger, voyez les manques possibles et partagez le menu avec votre famille.", "Connaître votre objectif nous aide à proposer des suggestions plus pertinentes chaque jour.", "Enregistrez vos allergènes afin que Chef IA puisse en tenir compte dans les recettes.", "Vous pouvez modifier ces réglages à tout moment dans Profil."], guides: [{ title: "Garde-manger", text: "Suivez les stocks, les idées anti-gaspillage et les rappels de courses." }, { title: "Chef IA", text: "Transformez une idée de repas en recette détaillée, au besoin uniquement avec le garde-manger." }, { title: "Menu hebdomadaire", text: "Réunissez recettes régionales, préférences alimentaires et correspondances du garde-manger." }], goals: ["Alimentation équilibrée", "Gestion du poids", "Priorité protéines", "Plus de légumes"], allergies: ["Arachides", "Gluten", "Produits laitiers", "Œufs", "Fruits de mer", "Aucun"], energyLabel: "Objectif énergétique quotidien", peopleLabel: "Pour combien de personnes planifiez-vous ?", peopleHint: "Le menu et les quantités de courses s’ajustent pour 1 à 12 personnes.", continue: "Continuer", start: "Découvrir LezzetAI", back: "Retour", privacy: "Vos préférences sont enregistrées sur cet appareil." },
};

export function getOnboardingCopy(locale: CuisineLocale) { return copy[locale]; }
