import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useState } from "react";

import { IconSymbol } from "@/components/ui/icon-symbol";
import { ScreenContainer } from "@/components/screen-container";
import { useLezzet } from "@/lib/lezzet-context";
import { trpc } from "@/lib/trpc";

const quickPrompts = ["20 dakikada akşam yemeği", "Kilerimdekilerle fikir ver", "Protein odaklı öğle yemeği"];

export default function ChefScreen() {
  const { pantry, profile } = useLezzet();
  const [request, setRequest] = useState("");
  const [result, setResult] = useState<{ title: string; description: string; prepMinutes: number; calories: number; protein: number; ingredients: string[]; steps: string[]; chefNote: string } | null>(null);
  const suggestion = trpc.chef.suggest.useMutation({ onSuccess: setResult });

  const askChef = async (preset?: string) => {
    const prompt = (preset ?? request).trim();
    if (!prompt) { Alert.alert("Bir isteğini yaz", "Örneğin: ‘Nohut ve roka ile 20 dakikada akşam yemeği’."); return; }
    await suggestion.mutateAsync({ request: prompt, pantry, goal: profile.goal, allergies: profile.allergies, people: profile.people });
  };

  return <ScreenContainer className="flex-1" containerClassName="bg-background"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
    <View style={styles.hero}><View style={styles.sparkWrap}><IconSymbol name="sparkles" size={28} color="#F4A261" /></View><Text style={styles.eyebrow}>LEZZETAI AI ŞEF</Text><Text style={styles.title}>Bir fikrini yaz, mutfağını çözelim.</Text><Text style={styles.subtitle}>Elindeki malzemeleri ve hedefini hesaba katarak sana özel tarif önereyeyim.</Text></View>
    <View style={styles.promptBox}><TextInput value={request} onChangeText={setRequest} multiline placeholder="Örn. Evde nohut, roka ve yoğurt var; hafif bir akşam yemeği istiyorum." placeholderTextColor="#839088" style={styles.input} textAlignVertical="top" /><View style={styles.promptFooter}><Text style={styles.helper}>{pantry.length} kiler malzemesi bağlama eklendi</Text><Pressable onPress={() => askChef()} disabled={suggestion.isPending} style={({ pressed }) => [styles.send, suggestion.isPending && { opacity: 0.55 }, pressed && { transform: [{ scale: 0.95 }] }]}><IconSymbol name="paperplane.fill" size={19} color="#FFFFFF" /></Pressable></View></View>
    <View style={styles.quickWrap}><Text style={styles.quickTitle}>Hızlı başlat</Text><View style={styles.quickList}>{quickPrompts.map((prompt) => <Pressable key={prompt} onPress={() => { setRequest(prompt); askChef(prompt); }} style={({ pressed }) => [styles.quick, pressed && { opacity: 0.65 }]}><Text style={styles.quickText}>{prompt}</Text><IconSymbol name="chevron.right" size={17} color="#1E4D3A" /></Pressable>)}</View></View>
    {suggestion.isPending ? <View style={styles.loading}><View style={styles.loadingIcon}><IconSymbol name="sparkles" size={23} color="#1E4D3A" /></View><View><Text style={styles.loadingTitle}>Şef düşünüyor</Text><Text style={styles.loadingText}>Tercihlerine uygun, uygulanabilir bir tarif hazırlanıyor.</Text></View></View> : null}
    {suggestion.isError ? <View style={styles.error}><Text style={styles.errorTitle}>Tarif şu an hazırlanamadı.</Text><Text style={styles.errorText}>Bağlantını kontrol edip tekrar deneyebilirsin.</Text></View> : null}
    {result ? <View style={styles.result}><View style={styles.resultTop}><View style={{ flex: 1 }}><Text style={styles.resultLabel}>SANA ÖZEL ÖNERİ</Text><Text style={styles.resultTitle}>{result.title}</Text><Text style={styles.resultDesc}>{result.description}</Text></View><View style={styles.resultSpark}><IconSymbol name="sparkles" size={19} color="#1E4D3A" /></View></View><View style={styles.nutrition}><Nutrition icon="clock" value={`${result.prepMinutes} dk`} label="Hazırlık" /><Nutrition icon="flame.fill" value={`${result.calories}`} label="kcal" /><Nutrition icon="leaf.fill" value={`${result.protein} g`} label="protein" /></View><Text style={styles.subheading}>Malzemeler</Text><View style={styles.ingredientList}>{result.ingredients.map((item) => <View style={styles.ingredient} key={item}><IconSymbol name="checkmark.circle.fill" size={16} color="#2D7A55" /><Text style={styles.ingredientText}>{item}</Text></View>)}</View><Text style={styles.subheading}>Nasıl yapılır?</Text><View style={styles.steps}>{result.steps.map((step, index) => <View style={styles.step} key={step}><Text style={styles.stepNumber}>{index + 1}</Text><Text style={styles.stepText}>{step}</Text></View>)}</View><View style={styles.note}><IconSymbol name="sparkles" size={16} color="#B7652E" /><Text style={styles.noteText}>{result.chefNote}</Text></View><Pressable onPress={() => Alert.alert("Planına eklendi", "Bu öneri Cumartesi akşamı için hatırlatmalarına eklendi.")} style={({ pressed }) => [styles.saveCta, pressed && { opacity: 0.85 }]}><Text style={styles.saveText}>Planıma ekle</Text><IconSymbol name="calendar" size={18} color="#FFFFFF" /></Pressable></View> : null}
    <Text style={styles.disclaimer}>Alerji, tıbbi durum veya özel diyet gereksinimlerinde, öneriyi profesyonel tavsiyenin yerine kullanma.</Text>
  </ScrollView></ScreenContainer>;
}

function Nutrition({ icon, value, label }: { icon: "clock" | "flame.fill" | "leaf.fill"; value: string; label: string }) { return <View style={styles.nutritionItem}><IconSymbol name={icon} size={16} color="#1E4D3A" /><Text style={styles.nutritionValue}>{value}</Text><Text style={styles.nutritionLabel}>{label}</Text></View>; }

const styles = StyleSheet.create({
  content: { padding: 20, paddingBottom: 34, gap: 20 }, hero: { alignItems: "center", paddingTop: 4 }, sparkWrap: { width: 56, height: 56, borderRadius: 20, alignItems: "center", justifyContent: "center", backgroundColor: "#1E4D3A", marginBottom: 13 }, eyebrow: { color: "#6B756F", fontSize: 11, fontWeight: "800", letterSpacing: 1.05 }, title: { color: "#1E2521", fontSize: 27, lineHeight: 33, fontWeight: "800", letterSpacing: -0.65, textAlign: "center", marginTop: 4 }, subtitle: { color: "#6B756F", fontSize: 13, lineHeight: 19, textAlign: "center", marginTop: 7, maxWidth: 315 },
  promptBox: { backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#D5E3D3", borderRadius: 22, padding: 15, shadowColor: "#1E4D3A", shadowOpacity: 0.06, shadowOffset: { width: 0, height: 5 }, shadowRadius: 12, elevation: 2 }, input: { color: "#1E2521", fontSize: 15, lineHeight: 21, minHeight: 90, padding: 0 }, promptFooter: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 9 }, helper: { color: "#6B756F", fontSize: 10, fontWeight: "600", flex: 1, paddingRight: 8 }, send: { width: 42, height: 42, borderRadius: 14, backgroundColor: "#1E4D3A", alignItems: "center", justifyContent: "center" },
  quickWrap: { gap: 9 }, quickTitle: { color: "#1E2521", fontWeight: "800", fontSize: 15 }, quickList: { gap: 8 }, quick: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", minHeight: 47, backgroundColor: "#FFFFFF", borderRadius: 16, borderWidth: 1, borderColor: "#EAE7E0", paddingHorizontal: 14 }, quickText: { color: "#1E4D3A", fontSize: 13, fontWeight: "700" },
  loading: { flexDirection: "row", gap: 12, alignItems: "center", backgroundColor: "#DDE8DA", borderRadius: 20, padding: 15 }, loadingIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: "#FBF8F2", alignItems: "center", justifyContent: "center" }, loadingTitle: { color: "#1E2521", fontWeight: "800", fontSize: 14 }, loadingText: { color: "#52705E", fontSize: 12, lineHeight: 17, marginTop: 2, flexShrink: 1 },
  error: { borderRadius: 18, padding: 15, backgroundColor: "#FDE7E4" }, errorTitle: { color: "#9D332A", fontSize: 14, fontWeight: "800" }, errorText: { color: "#B54C40", fontSize: 12, lineHeight: 17, marginTop: 2 },
  result: { gap: 15, backgroundColor: "#FFFFFF", borderRadius: 25, borderWidth: 1, borderColor: "#D5E3D3", padding: 17 }, resultTop: { flexDirection: "row", gap: 12 }, resultLabel: { color: "#1E4D3A", fontSize: 10, fontWeight: "900", letterSpacing: 0.85 }, resultTitle: { color: "#1E2521", fontSize: 22, lineHeight: 27, fontWeight: "800", letterSpacing: -0.4, marginTop: 4 }, resultDesc: { color: "#6B756F", fontSize: 13, lineHeight: 18, marginTop: 5 }, resultSpark: { width: 35, height: 35, borderRadius: 12, backgroundColor: "#DDE8DA", alignItems: "center", justifyContent: "center" },
  nutrition: { flexDirection: "row", justifyContent: "space-between", backgroundColor: "#F5F8F3", borderRadius: 16, paddingVertical: 11 }, nutritionItem: { flex: 1, alignItems: "center", gap: 2 }, nutritionValue: { color: "#1E2521", fontSize: 13, fontWeight: "900" }, nutritionLabel: { color: "#6B756F", fontSize: 10, fontWeight: "700" }, subheading: { color: "#1E2521", fontSize: 15, fontWeight: "800", marginTop: 2 }, ingredientList: { gap: 8 }, ingredient: { flexDirection: "row", gap: 8, alignItems: "center" }, ingredientText: { color: "#49554D", fontSize: 13, lineHeight: 18, flex: 1 }, steps: { gap: 10 }, step: { flexDirection: "row", gap: 10 }, stepNumber: { width: 22, height: 22, borderRadius: 11, overflow: "hidden", textAlign: "center", lineHeight: 22, color: "#FFFFFF", backgroundColor: "#1E4D3A", fontSize: 11, fontWeight: "800" }, stepText: { flex: 1, color: "#49554D", fontSize: 13, lineHeight: 19 }, note: { flexDirection: "row", gap: 8, backgroundColor: "#FCE6D2", borderRadius: 14, padding: 11 }, noteText: { flex: 1, color: "#89502B", fontSize: 12, lineHeight: 17, fontWeight: "600" }, saveCta: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, minHeight: 48, backgroundColor: "#1E4D3A", borderRadius: 15 }, saveText: { color: "#FFFFFF", fontWeight: "800", fontSize: 14 }, disclaimer: { color: "#6B756F", fontSize: 10, lineHeight: 15, textAlign: "center", paddingHorizontal: 12 },
});
