import { Alert, Pressable, ScrollView, StyleSheet, TextInput, View } from "react-native";
import { useEffect, useState } from "react";
import { useLocalSearchParams } from "expo-router";

import { IconSymbol } from "@/components/ui/icon-symbol";
import { LocalizedText as Text } from "@/components/localized-text";
import { MotionReveal } from "@/components/motion-reveal";
import { ScreenContainer } from "@/components/screen-container";
import { useLezzet } from "@/lib/lezzet-context";
import { trpc } from "@/lib/trpc";
import { generateAppleChefRecipe, getAppleChefAvailability, type AppleChefAvailability } from "@/lib/apple-foundation-chef";
import { getCuisineProfile } from "@/lib/cuisine-locale";

export default function ChefScreen() {
  const { pantry, profile, kitchenTools } = useLezzet();
  const cuisine = getCuisineProfile(profile.locale);
  const params = useLocalSearchParams<{ prompt?: string }>();
  const [request, setRequest] = useState("");
  const [appleAvailability, setAppleAvailability] = useState<AppleChefAvailability>("unavailable");
  const [result, setResult] = useState<{ title: string; description: string; prepMinutes: number; calories: number; protein: number; ingredients: string[]; steps: string[]; chefNote: string } | null>(null);
  const suggestion = trpc.chef.suggest.useMutation({ onSuccess: setResult });
  useEffect(() => { if (params.prompt) setRequest(params.prompt); }, [params.prompt]);
  useEffect(() => { getAppleChefAvailability().then(setAppleAvailability).catch(() => setAppleAvailability("unavailable")); }, []);
  const askChef = async (preset?: string) => { const prompt = (preset ?? request).trim(); if (!prompt) { Alert.alert("Bir fikir yaz", "Örneğin: ‘Nohut ve roka ile 20 dakikada akşam yemeği’. "); return; } const input = { request: prompt, pantry, goal: profile.goal, allergies: profile.allergies, people: profile.people, kitchenTools, locale: profile.locale }; if (appleAvailability === "available") { try { setResult(await generateAppleChefRecipe(input)); return; } catch { /* Güvenilir çapraz platform hizmetine geri dön. */ } } await suggestion.mutateAsync(input); };

  return <ScreenContainer className="flex-1" containerClassName="bg-background"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
    <MotionReveal><View style={styles.hero}><View style={styles.heroTop}><View style={styles.brandMark}><IconSymbol name="sparkles" size={21} color="#F4A261" /></View><Text style={styles.mode}>AI MUTFAK STÜDYOSU</Text>{appleAvailability === "available" ? <View style={styles.nativePill}><View style={styles.nativeDot} /><Text style={styles.nativePillText}>CİHAZDA</Text></View> : null}</View><Text style={styles.title}>Bir malzeme, bir ruh hali,{`\n`}sonsuz ihtimal.</Text><Text style={styles.subtitle}>Şef; kilerini, hedefini, ekipmanlarını ve seçtiğin {cuisine.region} mutfak bağlamını aynı anda düşünür.</Text><View style={styles.contextRow}><ContextPill label={cuisine.region} /><ContextPill label={kitchenTools.length ? `${kitchenTools.length} ekipman` : "ekipman seç"} /><ContextPill label={profile.goal} /></View></View></MotionReveal>
    <MotionReveal delay={65}><View style={styles.promptStudio}><View style={styles.studioHead}><Text style={styles.studioLabel}>BUGÜN NE PİŞİRELİM?</Text><View style={styles.studioLive}><View style={styles.studioDot} /><Text style={styles.studioLiveText}>KİŞİSELLEŞTİRİLDİ</Text></View></View><TextInput value={request} onChangeText={setRequest} multiline placeholder="Elimdeki malzemelerle, istediğim sürede ve ruh halimde bir tarif iste..." placeholderTextColor="#839088" style={styles.input} textAlignVertical="top" /><View style={styles.studioFooter}><Text style={styles.hint}>Ne kadar detay verirsen, şef o kadar iyi planlar.</Text><Pressable onPress={() => askChef()} disabled={suggestion.isPending} style={({ pressed }) => [styles.generate, suggestion.isPending && { opacity: 0.55 }, pressed && { transform: [{ scale: 0.96 }] }]}><Text style={styles.generateText}>{suggestion.isPending ? "Düşünüyor" : "Üret"}</Text><IconSymbol name="paperplane.fill" size={16} color="#FFFFFF" /></Pressable></View></View></MotionReveal>
    <MotionReveal delay={115}><View style={styles.inspire}><Text style={styles.inspireTitle}>Hızlı bir yön seç</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.promptRail}>{cuisine.quickPrompts.map((prompt, index) => <Pressable key={prompt} onPress={() => { setRequest(prompt); askChef(prompt); }} style={({ pressed }) => [styles.promptChip, index === 0 && styles.promptChipAccent, pressed && { opacity: 0.7, transform: [{ scale: 0.98 }] }]}><Text style={[styles.promptText, index === 0 && styles.promptTextAccent]}>{prompt}</Text><IconSymbol name="chevron.right" size={15} color={index === 0 ? "#FFFFFF" : "#1E4D3A"} /></Pressable>)}</ScrollView></View></MotionReveal>
    {suggestion.isPending ? <View style={styles.loading}><View style={styles.loadingOrb}><IconSymbol name="sparkles" size={23} color="#F4A261" /></View><View><Text style={styles.loadingTitle}>Tarif planı kuruluyor</Text><Text style={styles.loadingText}>Kiler, hedef ve süre dengeleniyor.</Text></View></View> : null}
    {suggestion.isError ? <View style={styles.error}><Text style={styles.errorTitle}>Tarif planı şu an kurulamadı.</Text><Text style={styles.errorText}>Bağlantıyı kontrol edip tekrar deneyebilirsin.</Text></View> : null}
    {result ? <MotionReveal delay={40}><View style={styles.blueprint}><View style={styles.blueprintHead}><View><Text style={styles.blueprintTag}>ŞEFİN TARİF PLANI</Text><Text style={styles.blueprintTitle}>{result.title}</Text><Text style={styles.blueprintDesc}>{result.description}</Text></View><View style={styles.blueprintIcon}><IconSymbol name="sparkles" size={19} color="#1E4D3A" /></View></View><View style={styles.metricBar}><Metric label="Süre" value={`${result.prepMinutes} dk`} /><Metric label="Enerji" value={`${result.calories} kcal`} /><Metric label="Protein" value={`${result.protein} g`} /></View><View style={styles.blueprintSection}><Text style={styles.sectionLabel}>MALZEME PALETİ</Text>{result.ingredients.map((item) => <View style={styles.ingredient} key={item}><View style={styles.ingredientDot} /><Text style={styles.ingredientText}>{item}</Text></View>)}</View><View style={styles.blueprintSection}><Text style={styles.sectionLabel}>PİŞİRME AKIŞI</Text>{result.steps.map((step, index) => <View style={styles.step} key={step}><Text style={styles.stepNumber}>{String(index + 1).padStart(2, "0")}</Text><Text style={styles.stepText}>{step}</Text></View>)}</View><View style={styles.note}><IconSymbol name="sparkles" size={16} color="#A45F33" /><Text style={styles.noteText}>{result.chefNote}</Text></View><Pressable onPress={() => Alert.alert("Planına eklendi", "Bu öneri haftalık menüne eklendi.")} style={({ pressed }) => [styles.planCta, pressed && { opacity: 0.86, transform: [{ scale: 0.985 }] }]}><Text style={styles.planCtaText}>Bu tarifi planıma ekle</Text><IconSymbol name="calendar" size={18} color="#FFFFFF" /></Pressable></View></MotionReveal> : null}
    <Text style={styles.disclaimer}>Özel sağlık, alerji veya beslenme durumlarında tarifleri profesyonel tavsiyenin yerine kullanma.</Text>
  </ScrollView></ScreenContainer>;
}

function ContextPill({ label }: { label: string }) { return <View style={styles.contextPill}><Text style={styles.contextText} numberOfLines={1}>{label}</Text></View>; }
function Metric({ label, value }: { label: string; value: string }) { return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({
  content: { padding: 20, paddingBottom: 36, gap: 20 }, hero: { padding: 19, gap: 10, borderRadius: 29, backgroundColor: "#173E2F" }, heroTop: { flexDirection: "row", alignItems: "center", gap: 9 }, brandMark: { width: 37, height: 37, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "#285C47" }, mode: { flex: 1, color: "#A8CDB3", fontSize: 10, fontWeight: "900", letterSpacing: 1.25 }, nativePill: { flexDirection: "row", alignItems: "center", gap: 4, paddingHorizontal: 7, paddingVertical: 5, borderRadius: 8, backgroundColor: "#285C47" }, nativeDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: "#F4A261" }, nativePillText: { color: "#DDE8DA", fontSize: 8, fontWeight: "900", letterSpacing: 0.5 }, title: { color: "#FFFFFF", fontSize: 29, lineHeight: 34, fontWeight: "800", letterSpacing: -1, marginTop: 5 }, subtitle: { color: "#B7D5C0", fontSize: 12, lineHeight: 18, maxWidth: 290 }, contextRow: { flexDirection: "row", gap: 6, marginTop: 5 }, contextPill: { maxWidth: "43%", paddingHorizontal: 8, paddingVertical: 6, borderRadius: 10, backgroundColor: "#285C47" }, contextText: { color: "#DDE8DA", fontSize: 9, fontWeight: "800" },
  promptStudio: { padding: 15, gap: 11, borderRadius: 25, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#D6E4D5", shadowColor: "#1E4D3A", shadowOpacity: 0.08, shadowRadius: 16, shadowOffset: { width: 0, height: 7 }, elevation: 2 }, studioHead: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, studioLabel: { color: "#6B756F", fontSize: 9, fontWeight: "900", letterSpacing: 1.04 }, studioLive: { flexDirection: "row", alignItems: "center", gap: 4 }, studioDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: "#2D7A55" }, studioLiveText: { color: "#2D7A55", fontSize: 8, fontWeight: "900" }, input: { minHeight: 94, color: "#1E2521", fontSize: 16, lineHeight: 22, padding: 0, fontWeight: "600" }, studioFooter: { flexDirection: "row", alignItems: "center", gap: 10 }, hint: { flex: 1, color: "#6B756F", fontSize: 10, lineHeight: 14 }, generate: { minHeight: 38, paddingHorizontal: 12, borderRadius: 13, backgroundColor: "#1E4D3A", flexDirection: "row", gap: 6, alignItems: "center", justifyContent: "center" }, generateText: { color: "#FFFFFF", fontSize: 11, fontWeight: "900" },
  inspire: { gap: 9 }, inspireTitle: { color: "#1E2521", fontSize: 15, fontWeight: "900", letterSpacing: -0.2 }, promptRail: { gap: 8, paddingRight: 20 }, promptChip: { minHeight: 43, flexDirection: "row", alignItems: "center", gap: 7, paddingHorizontal: 12, borderRadius: 14, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EAE7E0" }, promptChipAccent: { backgroundColor: "#1E4D3A", borderColor: "#1E4D3A" }, promptText: { color: "#1E4D3A", fontSize: 11, fontWeight: "800" }, promptTextAccent: { color: "#FFFFFF" },
  loading: { flexDirection: "row", alignItems: "center", gap: 12, padding: 15, borderRadius: 20, backgroundColor: "#DDE8DA" }, loadingOrb: { width: 42, height: 42, borderRadius: 16, alignItems: "center", justifyContent: "center", backgroundColor: "#1E4D3A" }, loadingTitle: { color: "#1E2521", fontSize: 14, fontWeight: "900" }, loadingText: { color: "#52705E", fontSize: 11, marginTop: 2 }, error: { padding: 15, borderRadius: 19, backgroundColor: "#FDE7E4" }, errorTitle: { color: "#9D332A", fontSize: 14, fontWeight: "900" }, errorText: { color: "#B54C40", fontSize: 11, marginTop: 3 },
  blueprint: { gap: 15, padding: 17, borderRadius: 27, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#D6E4D5" }, blueprintHead: { flexDirection: "row", gap: 12 }, blueprintTag: { color: "#1E4D3A", fontSize: 9, fontWeight: "900", letterSpacing: 1.1 }, blueprintTitle: { color: "#1E2521", fontSize: 25, lineHeight: 30, fontWeight: "800", letterSpacing: -0.7, marginTop: 4 }, blueprintDesc: { color: "#6B756F", fontSize: 12, lineHeight: 18, marginTop: 5 }, blueprintIcon: { width: 37, height: 37, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "#DDE8DA" }, metricBar: { flexDirection: "row", gap: 7 }, metric: { flex: 1, paddingVertical: 10, borderRadius: 13, alignItems: "center", backgroundColor: "#F5F8F3" }, metricValue: { color: "#1E2521", fontSize: 12, fontWeight: "900" }, metricLabel: { color: "#6B756F", fontSize: 9, fontWeight: "800", marginTop: 2 }, blueprintSection: { gap: 8 }, sectionLabel: { color: "#6B756F", fontSize: 9, fontWeight: "900", letterSpacing: 1.03 }, ingredient: { flexDirection: "row", alignItems: "center", gap: 8 }, ingredientDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: "#F4A261" }, ingredientText: { color: "#45534A", fontSize: 12, lineHeight: 17 }, step: { flexDirection: "row", gap: 10 }, stepNumber: { color: "#1E4D3A", fontSize: 10, fontWeight: "900", width: 20 }, stepText: { flex: 1, color: "#45534A", fontSize: 12, lineHeight: 18 }, note: { flexDirection: "row", gap: 8, padding: 11, borderRadius: 14, backgroundColor: "#FCE6D2" }, noteText: { flex: 1, color: "#89502B", fontSize: 11, lineHeight: 16, fontWeight: "700" }, planCta: { minHeight: 50, borderRadius: 16, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 8, backgroundColor: "#1E4D3A" }, planCtaText: { color: "#FFFFFF", fontSize: 13, fontWeight: "900" }, disclaimer: { color: "#6B756F", fontSize: 10, lineHeight: 15, textAlign: "center", paddingHorizontal: 16 },
});
