import { Image, Pressable, ScrollView, StyleSheet, View } from "react-native";
import { router } from "expo-router";

import { IconSymbol } from "@/components/ui/icon-symbol";
import { LocalizedText as Text } from "@/components/localized-text";
import { MotionReveal } from "@/components/motion-reveal";
import { RecipeCard } from "@/components/recipe-card";
import { SectionTitle } from "@/components/section-title";
import { ScreenContainer } from "@/components/screen-container";
import { getRecipesForLocale } from "@/lib/lezzet-data";
import { useLezzet } from "@/lib/lezzet-context";
import { getAdaptiveTargets } from "@/lib/wearable-utils";
import { getCuisineProfile } from "@/lib/cuisine-locale";

export default function TodayScreen() {
  const { favorites, pantry, pantryMeta, profile, wearableActivity, journalEntries, recipeFeedback, toggleFavorite } = useLezzet();
  const cuisine = getCuisineProfile(profile.locale);
  const localRecipes = getRecipesForLocale(profile.locale);
  const heroRecipe = localRecipes[0];
  const targets = getAdaptiveTargets(profile.calories, wearableActivity?.activeCalories ?? 0);
  const urgentItems = pantry.filter((item) => (pantryMeta[item]?.expiresInDays ?? 7) <= 2);
  const coachCopy = journalEntries.length ? `${journalEntries.length} tarif deneyimin, sonraki önerileri şekillendiriyor.` : Object.keys(recipeFeedback).length ? "Geri bildirimlerinle daha doğru tarifler seçiyoruz." : "Bir tarif pişir; tempo ve zorluk tercihlerini öğrenelim.";

  return <ScreenContainer className="flex-1" containerClassName="bg-background"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <MotionReveal><View style={styles.header}><View><Text style={styles.eyebrow}>MUTFAK PUSULASI · {cuisine.flag} {cuisine.region.toUpperCase()}</Text><Text style={styles.greeting}>Günün akışını<br />sen belirle.</Text></View><Pressable onPress={() => router.push("/(tabs)/profile" as never)} style={({ pressed }) => [styles.avatar, pressed && { opacity: 0.7, transform: [{ scale: 0.96 }] }]}><Text style={styles.avatarText}>D</Text><View style={styles.avatarDot} /></Pressable></View></MotionReveal>

    <MotionReveal delay={55}><Pressable onPress={() => router.push(`/recipe/${heroRecipe.id}` as never)} style={({ pressed }) => [styles.hero, pressed && styles.pressed]}><Image source={heroRecipe.image} style={styles.heroImage} resizeMode="cover" /><View style={styles.heroTopShade} /><View style={styles.heroBottomShade} /><View style={styles.heroTop}><View style={styles.livePill}><View style={styles.liveDot} /><Text style={styles.liveText}>{cuisine.region.toUpperCase()} · BUGÜNÜN ÖNERİSİ</Text></View><View style={styles.heroSave}><IconSymbol name="sparkles" size={16} color="#1E4D3A" /></View></View><View style={styles.heroCopy}><Text style={styles.heroOverline}>KİLER ODAKLI · {heroRecipe.minutes} DK</Text><Text style={styles.heroTitle}>{heroRecipe.title}</Text><View style={styles.heroFooter}><Text style={styles.heroMeta}>{heroRecipe.calories} kcal</Text><View style={styles.heroAction}><Text style={styles.heroActionText}>Tarifi aç</Text><IconSymbol name="chevron.right" size={16} color="#FFFFFF" /></View></View></View></Pressable></MotionReveal>

    <MotionReveal delay={110}><View style={styles.fuelDeck}><View style={styles.fuelHead}><View><Text style={styles.deckLabel}>GÜNLÜK YAKIT</Text><Text style={styles.deckTitle}>{targets.calories} <Text style={styles.deckUnit}>kcal hedef</Text></Text></View><View style={styles.progressBadge}><Text style={styles.progressValue}>39%</Text><Text style={styles.progressLabel}>tamam</Text></View></View><View style={styles.macroGrid}><Macro label="Protein" value={`${targets.protein}g`} color="#DDE8DA" /><Macro label="Karbonhidrat" value={`${targets.carbs}g`} color="#FCE6D2" /><Macro label="Yağ" value={`${targets.fat}g`} color="#ECE4D7" /></View>{wearableActivity ? <View style={styles.activityLine}><IconSymbol name="sparkles" size={14} color="#1E4D3A" /><Text style={styles.activityText}>{wearableActivity.steps.toLocaleString("tr-TR")} adım senkronize edildi · +{targets.adjustment} kcal uyarlama</Text></View> : <Pressable onPress={() => router.push("/wearables" as never)} style={styles.activityLine}><IconSymbol name="sparkles" size={14} color="#1E4D3A" /><Text style={styles.activityText}>Hareket verini bağla, hedefini otomatik uyarla</Text><IconSymbol name="chevron.right" size={15} color="#1E4D3A" /></Pressable>}</View></MotionReveal>

    <MotionReveal delay={165}><View style={styles.actionGrid}><Pressable onPress={() => router.push("/(tabs)/chef" as never)} style={({ pressed }) => [styles.aiAction, pressed && styles.pressed]}><View style={styles.actionTop}><View style={styles.aiIcon}><IconSymbol name="sparkles" size={19} color="#FFFFFF" /></View><Text style={styles.actionTag}>AI ŞEF</Text></View><Text style={styles.aiActionTitle}>Bir fikri{`\n`}sofraya dönüştür.</Text><Text style={styles.aiActionText}>Malzeme, hedef ve süreye göre konuşalım.</Text><View style={styles.actionArrow}><IconSymbol name="chevron.right" size={18} color="#FFFFFF" /></View></Pressable><View style={styles.sideActions}><Pressable onPress={() => router.push("/scan-ingredients" as never)} style={({ pressed }) => [styles.sideAction, pressed && styles.pressed]}><View style={[styles.sideIcon, { backgroundColor: "#FCE6D2" }]}><IconSymbol name="camera.fill" size={19} color="#B7652E" /></View><View style={{ flex: 1 }}><Text style={styles.sideTitle}>Tara & pişir</Text><Text style={styles.sideText}>Fotoğraftan malzeme tanı</Text></View></Pressable><Pressable onPress={() => router.push("/pantry" as never)} style={({ pressed }) => [styles.sideAction, pressed && styles.pressed]}><View style={[styles.sideIcon, { backgroundColor: "#DDE8DA" }]}><IconSymbol name="cabinet.fill" size={19} color="#1E4D3A" /></View><View style={{ flex: 1 }}><Text style={styles.sideTitle}>Kiler radarı</Text><Text style={styles.sideText}>{urgentItems.length ? `${urgentItems.join(", ")} öncelikli` : `${pantry.length} malzeme hazır`}</Text></View></Pressable></View></View></MotionReveal>

    <MotionReveal delay={220}><Pressable onPress={() => router.push("/journal" as never)} style={({ pressed }) => [styles.coach, pressed && styles.pressed]}><View style={styles.coachIndex}><Text style={styles.coachIndexValue}>01</Text></View><View style={{ flex: 1 }}><Text style={styles.coachKicker}>KİŞİSEL MUTFAK KOÇU</Text><Text style={styles.coachTitle}>{coachCopy}</Text></View><View style={styles.coachArrow}><IconSymbol name="chevron.right" size={18} color="#1E4D3A" /></View></Pressable></MotionReveal>

    <MotionReveal delay={265}><View style={styles.section}><SectionTitle title={`${cuisine.region} için seçtik`} action={cuisine.ui.discover} onPress={() => router.push("/(tabs)/discover" as never)} /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.horizontalCards}>{localRecipes.slice(1).map((recipe) => <RecipeCard key={recipe.id} recipe={recipe} isFavorite={favorites.includes(recipe.id)} onToggleFavorite={() => toggleFavorite(recipe.id)} onPress={() => router.push(`/recipe/${recipe.id}` as never)} />)}</ScrollView></View></MotionReveal>
    <Pressable onPress={() => router.push("/(tabs)/plan" as never)} style={({ pressed }) => [styles.planLink, pressed && styles.pressed]}><View><Text style={styles.planKicker}>HAFTANIN GÖRÜNÜMÜ</Text><Text style={styles.planTitle}>Menünü akıllıca planla.</Text></View><View style={styles.planButton}><IconSymbol name="calendar" size={18} color="#FFFFFF" /></View></Pressable>
  </ScrollView></ScreenContainer>;
}

function Macro({ label, value, color }: { label: string; value: string; color: string }) { return <View style={[styles.macro, { backgroundColor: color }]}><Text style={styles.macroValue}>{value}</Text><Text style={styles.macroLabel}>{label}</Text></View>; }

const styles = StyleSheet.create({
  content: { padding: 20, paddingBottom: 38, gap: 18 }, header: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", paddingTop: 3 }, eyebrow: { color: "#6B756F", fontSize: 10, fontWeight: "900", letterSpacing: 1.55 }, greeting: { color: "#1E2521", fontSize: 33, lineHeight: 36, fontWeight: "800", letterSpacing: -1.3, marginTop: 8 }, avatar: { width: 46, height: 46, borderRadius: 23, backgroundColor: "#1E4D3A", alignItems: "center", justifyContent: "center", shadowColor: "#1E4D3A", shadowOpacity: 0.2, shadowRadius: 10, shadowOffset: { width: 0, height: 5 }, elevation: 2 }, avatarText: { color: "#FFFFFF", fontSize: 16, fontWeight: "900" }, avatarDot: { position: "absolute", right: 1, bottom: 2, width: 11, height: 11, borderRadius: 6, borderWidth: 2, borderColor: "#FBF8F2", backgroundColor: "#F4A261" },
  hero: { height: 330, overflow: "hidden", borderRadius: 32, position: "relative", justifyContent: "space-between", padding: 18, shadowColor: "#1E2521", shadowOpacity: 0.16, shadowRadius: 23, shadowOffset: { width: 0, height: 12 }, elevation: 5 }, heroImage: { ...StyleSheet.absoluteFillObject, width: undefined, height: undefined }, heroTopShade: { ...StyleSheet.absoluteFillObject, backgroundColor: "#0B2016", opacity: 0.2 }, heroBottomShade: { ...StyleSheet.absoluteFillObject, top: "35%", backgroundColor: "#0B2016", opacity: 0.64 }, heroTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, livePill: { flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 10, paddingVertical: 7, borderRadius: 13, backgroundColor: "rgba(251,248,242,0.94)" }, liveDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: "#E28142" }, liveText: { color: "#1E4D3A", fontSize: 9, fontWeight: "900", letterSpacing: 0.75 }, heroSave: { width: 33, height: 33, borderRadius: 12, backgroundColor: "rgba(251,248,242,0.93)", alignItems: "center", justifyContent: "center" }, heroCopy: { gap: 7 }, heroOverline: { color: "#DDE8DA", fontSize: 10, fontWeight: "900", letterSpacing: 1.1 }, heroTitle: { color: "#FFFFFF", fontSize: 30, fontWeight: "800", lineHeight: 35, letterSpacing: -1.05, maxWidth: "94%" }, heroFooter: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 3 }, heroMeta: { color: "#FFFFFF", fontSize: 13, fontWeight: "700" }, heroAction: { flexDirection: "row", alignItems: "center", gap: 4 }, heroActionText: { color: "#FFFFFF", fontSize: 11, fontWeight: "900" },
  fuelDeck: { backgroundColor: "#173E2F", borderRadius: 26, padding: 16, gap: 14 }, fuelHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, deckLabel: { color: "#9CC8AE", fontSize: 10, fontWeight: "900", letterSpacing: 1.1 }, deckTitle: { color: "#FFFFFF", fontSize: 25, fontWeight: "900", letterSpacing: -0.65, marginTop: 3 }, deckUnit: { color: "#C2D9C9", fontSize: 12, fontWeight: "700" }, progressBadge: { width: 47, height: 47, borderRadius: 16, alignItems: "center", justifyContent: "center", backgroundColor: "#285C47" }, progressValue: { color: "#FFFFFF", fontSize: 13, fontWeight: "900" }, progressLabel: { color: "#A9CDB6", fontSize: 8, fontWeight: "800", marginTop: 1 }, macroGrid: { flexDirection: "row", gap: 8 }, macro: { flex: 1, borderRadius: 14, padding: 10, gap: 2 }, macroValue: { color: "#1E2521", fontSize: 14, fontWeight: "900" }, macroLabel: { color: "#536057", fontSize: 9, fontWeight: "800" }, activityLine: { minHeight: 31, borderRadius: 11, paddingHorizontal: 9, gap: 6, flexDirection: "row", alignItems: "center", backgroundColor: "#EAF2E9" }, activityText: { flex: 1, color: "#1E4D3A", fontSize: 10, fontWeight: "800" },
  actionGrid: { flexDirection: "row", gap: 11 }, aiAction: { width: "49%", minHeight: 183, borderRadius: 25, padding: 15, backgroundColor: "#E5EEE2", justifyContent: "space-between" }, actionTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, aiIcon: { width: 36, height: 36, borderRadius: 13, backgroundColor: "#1E4D3A", alignItems: "center", justifyContent: "center" }, actionTag: { color: "#1E4D3A", fontSize: 9, fontWeight: "900", letterSpacing: 0.8 }, aiActionTitle: { color: "#1E2521", fontSize: 21, lineHeight: 24, fontWeight: "800", letterSpacing: -0.65, marginTop: 10 }, aiActionText: { color: "#597061", fontSize: 10, lineHeight: 15, marginTop: 5 }, actionArrow: { width: 33, height: 33, borderRadius: 12, alignItems: "center", justifyContent: "center", alignSelf: "flex-end", backgroundColor: "#1E4D3A" }, sideActions: { flex: 1, gap: 11 }, sideAction: { flex: 1, minHeight: 86, padding: 11, gap: 8, borderRadius: 21, justifyContent: "center", backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EAE7E0" }, sideIcon: { width: 33, height: 33, borderRadius: 11, alignItems: "center", justifyContent: "center" }, sideTitle: { color: "#1E2521", fontSize: 12, fontWeight: "900" }, sideText: { color: "#6B756F", fontSize: 9, lineHeight: 13, marginTop: 2 },
  coach: { flexDirection: "row", alignItems: "center", gap: 11, padding: 13, borderRadius: 20, backgroundColor: "#FCE6D2", borderWidth: 1, borderColor: "#F1D6C0" }, coachIndex: { width: 37, height: 37, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "#B7652E" }, coachIndexValue: { color: "#FFFFFF", fontSize: 11, fontWeight: "900" }, coachKicker: { color: "#A45F33", fontSize: 9, fontWeight: "900", letterSpacing: 0.9 }, coachTitle: { color: "#754626", fontSize: 12, lineHeight: 17, fontWeight: "800", marginTop: 2 }, coachArrow: { width: 30, height: 30, borderRadius: 11, alignItems: "center", justifyContent: "center", backgroundColor: "#FFF1E5" },
  section: { marginTop: 4 }, horizontalCards: { gap: 12, paddingRight: 20 }, planLink: { marginTop: 3, flexDirection: "row", alignItems: "center", justifyContent: "space-between", padding: 16, borderRadius: 22, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#D7E5D6" }, planKicker: { color: "#6B756F", fontSize: 9, fontWeight: "900", letterSpacing: 1.05 }, planTitle: { color: "#1E2521", fontSize: 17, fontWeight: "800", marginTop: 3, letterSpacing: -0.35 }, planButton: { width: 42, height: 42, borderRadius: 15, alignItems: "center", justifyContent: "center", backgroundColor: "#1E4D3A" }, pressed: { opacity: 0.86, transform: [{ scale: 0.985 }] },
});
