import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";

import { IconSymbol } from "@/components/ui/icon-symbol";
import { ScreenContainer } from "@/components/screen-container";
import { getRecipe } from "@/lib/lezzet-data";
import { useLezzet } from "@/lib/lezzet-context";
import { formatTry } from "@/lib/culinary-utils";

export default function PlanScreen() {
  const { weeklyPlan, createGroceryFromPlan, createPersonalWeeklyPlan, replaceWeeklyMeal, profile, pantry, pantryMeta, weeklyBudget, setWeeklyBudget, familyProfiles } = useLezzet();
  const days = ["Pzt", "Sal", "Çar", "Per", "Cum", "Cmt", "Paz"];
  const estimate = weeklyPlan.reduce((sum, item) => sum + getRecipe(item.recipeId).estimatedCost * (profile.people / 2), 0);
  const urgentPantry = pantry.filter((item) => (pantryMeta[item]?.expiresInDays ?? 7) <= 2);

  return <ScreenContainer className="flex-1" containerClassName="bg-background"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <View><Text style={styles.eyebrow}>HAFTANIN RİTMİ</Text><Text style={styles.title}>Yemek planın</Text></View>
    <View style={styles.dayStrip}>{days.map((day, index) => <View key={day} style={[styles.day, index === 0 && styles.dayActive]}><Text style={[styles.dayName, index === 0 && styles.dayNameActive]}>{day}</Text><Text style={[styles.dayNumber, index === 0 && styles.dayNumberActive]}>{18 + index}</Text></View>)}</View>
    <View style={styles.summary}><View style={styles.summaryIcon}><IconSymbol name="sparkles" size={22} color="#1E4D3A" /></View><View style={{ flex: 1 }}><Text style={styles.summaryTitle}>Haftan dengeli görünüyor</Text><Text style={styles.summaryText}>{profile.goal} hedefin, {pantry.filter((item) => pantryMeta[item]?.favorite).length} favori malzeme ve kiler önceliklerin dikkate alınabilir.</Text></View></View>
    <Pressable onPress={createPersonalWeeklyPlan} style={({ pressed }) => [styles.autoPlan, pressed && { opacity: 0.8, transform: [{ scale: 0.985 }] }]}><View style={styles.autoPlanIcon}><IconSymbol name="sparkles" size={20} color="#FFFFFF" /></View><View style={{ flex: 1 }}><Text style={styles.autoPlanTitle}>Haftamı otomatik planla</Text><Text style={styles.autoPlanText}>Favori malzemelerin, diyet hedefin ve kilerindeki önceliklerle 7 günlük menü oluştur.</Text></View><IconSymbol name="chevron.right" size={20} color="#1E4D3A" /></Pressable>
    <View style={styles.budgetCard}><View style={styles.budgetHead}><View><Text style={styles.budgetLabel}>HAFTALIK BÜTÇE</Text><Text style={styles.budgetValue}>{formatTry(estimate)} <Text style={styles.budgetLimit}>/ {formatTry(weeklyBudget)}</Text></Text></View><Text style={[styles.budgetStatus, estimate > weeklyBudget && { color: "#B54C40" }]}>{estimate > weeklyBudget ? "Limit aşıldı" : "Plan dahilinde"}</Text></View><View style={styles.budgetTrack}><View style={[styles.budgetFill, { width: `${Math.min(100, Math.round(estimate / weeklyBudget * 100))}%` }]} /></View><View style={styles.budgetControls}><Pressable onPress={() => setWeeklyBudget(Math.max(500, weeklyBudget - 100))} style={styles.budgetButton}><Text style={styles.budgetButtonText}>−100</Text></Pressable><Text style={styles.budgetHint}>Market bazlı fiyatlar için listeyi paylaşabilirsin.</Text><Pressable onPress={() => setWeeklyBudget(weeklyBudget + 100)} style={styles.budgetButton}><Text style={styles.budgetButtonText}>+100</Text></Pressable></View></View>
    <View style={styles.zeroWaste}><IconSymbol name="leaf.fill" size={19} color="#1E4D3A" /><View style={{ flex: 1 }}><Text style={styles.zeroWasteTitle}>Sıfır atık koçu</Text><Text style={styles.zeroWasteText}>{urgentPantry.length ? `${urgentPantry.join(", ")} yakında tüketilmeli. Bu hafta bu ürünleri kullanan tarifler önceliklendirildi.` : "Kilerindeki son kullanma tarihlerini güncel tut; planın israfı azaltacak şekilde yenilensin."}</Text></View></View>
    <View style={styles.familySummary}><IconSymbol name="person.2.fill" size={19} color="#1E4D3A" /><View style={{ flex: 1 }}><Text style={styles.familyTitle}>Aile planı</Text><Text style={styles.familyText}>{familyProfiles.length} profilin hedefleri ve alerjenleri menü kararlarında gözetiliyor.</Text></View></View>
    <View style={styles.timeline}>{weeklyPlan.map((item) => { const recipe = getRecipe(item.recipeId); return <View key={`${item.day}-${item.recipeId}`} style={styles.mealCard}><Pressable onPress={() => router.push(`/recipe/${recipe.id}` as never)} style={({ pressed }) => [styles.mealOpen, pressed && { opacity: 0.7 }]}><View style={styles.mealDate}><Text style={styles.mealDay}>{item.day}</Text><Text style={styles.mealType}>{item.meal}</Text></View><View style={styles.mealDivider} /><View style={{ flex: 1 }}><Text style={styles.mealTitle}>{recipe.title}</Text><Text style={styles.mealMeta}>{recipe.minutes} dk · {recipe.calories} kcal</Text></View><IconSymbol name="chevron.right" size={19} color="#1E4D3A" /></Pressable><Pressable onPress={() => replaceWeeklyMeal(item.day, item.recipeId)} style={({ pressed }) => [styles.refreshButton, pressed && { opacity: 0.68, transform: [{ scale: 0.96 }] }]}><IconSymbol name="arrow.clockwise" size={16} color="#1E4D3A" /><Text style={styles.refreshText}>Alternatif</Text></Pressable></View>; })}</View>
    <Pressable onPress={() => { createGroceryFromPlan(); router.push("/shopping-list" as never); }} style={({ pressed }) => [styles.shoppingCta, pressed && { opacity: 0.85, transform: [{ scale: 0.985 }] }]}><View style={styles.shoppingIcon}><IconSymbol name="cart.fill" size={22} color="#FFFFFF" /></View><View style={{ flex: 1 }}><Text style={styles.shoppingTitle}>Alışveriş listesini hazırla</Text><Text style={styles.shoppingText}>Planındaki tüm malzemeleri tek listede topla.</Text></View><IconSymbol name="chevron.right" size={20} color="#FFFFFF" /></Pressable>
  </ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({
  content: { padding: 20, paddingBottom: 32, gap: 20 }, eyebrow: { color: "#6B756F", fontSize: 11, fontWeight: "800", letterSpacing: 1.1 }, title: { color: "#1E2521", fontSize: 30, lineHeight: 36, fontWeight: "800", letterSpacing: -0.8, marginTop: 2 },
  dayStrip: { flexDirection: "row", justifyContent: "space-between", backgroundColor: "#FFFFFF", borderRadius: 20, padding: 8, borderWidth: 1, borderColor: "#EAE7E0" }, day: { flex: 1, alignItems: "center", gap: 4, paddingVertical: 8, borderRadius: 14 }, dayActive: { backgroundColor: "#1E4D3A" }, dayName: { fontSize: 10, color: "#6B756F", fontWeight: "800" }, dayNameActive: { color: "#DDE8DA" }, dayNumber: { color: "#1E2521", fontSize: 15, fontWeight: "800" }, dayNumberActive: { color: "#FFFFFF" },
  summary: { flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: "#DDE8DA", borderRadius: 20, padding: 15 }, summaryIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: "#FBF8F2", alignItems: "center", justifyContent: "center" }, summaryTitle: { color: "#1E2521", fontWeight: "800", fontSize: 15 }, summaryText: { color: "#52705E", fontSize: 12, lineHeight: 17, marginTop: 2 },
  autoPlan: { flexDirection: "row", alignItems: "center", gap: 11, padding: 14, borderRadius: 20, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#C9DCC4" }, autoPlanIcon: { width: 39, height: 39, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "#1E4D3A" }, autoPlanTitle: { color: "#1E2521", fontSize: 14, fontWeight: "800" }, autoPlanText: { color: "#6B756F", fontSize: 11, lineHeight: 16, marginTop: 2 },
  budgetCard: { gap: 10, padding: 14, borderRadius: 20, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EAE7E0" }, budgetHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, budgetLabel: { color: "#6B756F", fontSize: 10, fontWeight: "900", letterSpacing: 0.7 }, budgetValue: { color: "#1E2521", fontSize: 19, fontWeight: "900", marginTop: 3 }, budgetLimit: { color: "#6B756F", fontSize: 12 }, budgetStatus: { color: "#2D7A55", fontSize: 11, fontWeight: "800", paddingHorizontal: 8, paddingVertical: 5, borderRadius: 10, backgroundColor: "#DDE8DA" }, budgetTrack: { height: 7, borderRadius: 4, backgroundColor: "#E9EFE7", overflow: "hidden" }, budgetFill: { height: "100%", backgroundColor: "#1E4D3A", borderRadius: 4 }, budgetControls: { flexDirection: "row", alignItems: "center", gap: 7 }, budgetButton: { paddingHorizontal: 9, paddingVertical: 6, borderRadius: 9, backgroundColor: "#DDE8DA" }, budgetButtonText: { color: "#1E4D3A", fontSize: 10, fontWeight: "900" }, budgetHint: { flex: 1, color: "#6B756F", fontSize: 10, lineHeight: 14, textAlign: "center" }, zeroWaste: { flexDirection: "row", gap: 10, padding: 14, borderRadius: 19, backgroundColor: "#DDE8DA" }, zeroWasteTitle: { color: "#1E2521", fontSize: 13, fontWeight: "800" }, zeroWasteText: { color: "#52705E", fontSize: 11, lineHeight: 16, marginTop: 2 }, familySummary: { flexDirection: "row", gap: 10, padding: 14, borderRadius: 19, backgroundColor: "#F5F8F3", borderWidth: 1, borderColor: "#D5E3D3" }, familyTitle: { color: "#1E2521", fontSize: 13, fontWeight: "800" }, familyText: { color: "#6B756F", fontSize: 11, lineHeight: 16, marginTop: 2 },
  timeline: { gap: 10 }, mealCard: { backgroundColor: "#FFFFFF", borderRadius: 19, borderWidth: 1, borderColor: "#EAE7E0", padding: 12, gap: 9 }, mealOpen: { flexDirection: "row", alignItems: "center", gap: 12 }, mealDate: { width: 47, gap: 2 }, mealDay: { color: "#1E4D3A", fontSize: 13, fontWeight: "900" }, mealType: { color: "#6B756F", fontSize: 10, fontWeight: "700" }, mealDivider: { width: 1, height: 34, backgroundColor: "#EAE7E0" }, mealTitle: { color: "#1E2521", fontSize: 14, fontWeight: "800" }, mealMeta: { color: "#6B756F", fontSize: 11, marginTop: 3, fontWeight: "600" }, refreshButton: { minHeight: 32, paddingHorizontal: 10, borderRadius: 11, backgroundColor: "#DDE8DA", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6 }, refreshText: { color: "#1E4D3A", fontSize: 11, fontWeight: "800" },
  shoppingCta: { flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: "#1E4D3A", borderRadius: 22, padding: 16, marginTop: 4 }, shoppingIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: "#34684F", alignItems: "center", justifyContent: "center" }, shoppingTitle: { color: "#FFFFFF", fontSize: 15, fontWeight: "800" }, shoppingText: { color: "#DDE8DA", fontSize: 11, lineHeight: 16, marginTop: 2 },
});
