import { Pressable, ScrollView, Share, StyleSheet, View } from "react-native";
import { router } from "expo-router";

import { IconSymbol } from "@/components/ui/icon-symbol";
import { LocalizedText as Text } from "@/components/localized-text";
import { ScreenContainer } from "@/components/screen-container";
import { buildGroceryList, getRecipe } from "@/lib/lezzet-data";
import { buildWeeklyPlanShareMessage } from "@/lib/meal-planning";
import { useLezzet } from "@/lib/lezzet-context";
import { MotionReveal } from "@/components/motion-reveal";
import { getCuisineProfile } from "@/lib/cuisine-locale";
import { formatLocalCurrency, getCurrentSeason, getMarketCategoryKey, getSeasonName, getSeasonalPackage, toLocalMarketEstimate } from "@/lib/seasonal-market";

export default function PlanScreen() {
  const { weeklyPlan, createGroceryFromPlan, createPersonalWeeklyPlan, replaceWeeklyMeal, profile, pantry, pantryMeta, weeklyBudget, setWeeklyBudget, familyProfiles, marketPrices } = useLezzet();
  const cuisine = getCuisineProfile(profile.locale);
  const season = getCurrentSeason();
  const seasonalPackage = getSeasonalPackage(profile.locale, season);
  const days = cuisine.days;
  const estimate = buildGroceryList(weeklyPlan.map((item) => item.recipeId)).reduce((sum, item) => sum + marketPrices[profile.locale][getMarketCategoryKey(item.name)], 0);
  const urgentPantry = pantry.filter((item) => (pantryMeta[item]?.expiresInDays ?? 7) <= 2);
  const sharePlan = async () => {
    const items = weeklyPlan.map((item) => { const recipe = getRecipe(item.recipeId); return { day: item.day, meal: item.meal, title: recipe.title, minutes: recipe.minutes }; });
    await Share.share({ title: "LezzetAI haftalık yemek planı", message: buildWeeklyPlanShareMessage(items) });
  };

  return <ScreenContainer className="flex-1" containerClassName="bg-background"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <View style={styles.titleRow}><View style={{ flex: 1 }}><Text style={styles.eyebrow}>{cuisine.ui.planEyebrow}</Text><Text style={styles.title}>{cuisine.ui.planTitle}</Text></View><Pressable onPress={sharePlan} style={({ pressed }) => [styles.sharePlan, pressed && { opacity: 0.7 }]}><IconSymbol name="paperplane.fill" size={19} color="#1E4D3A" /><Text style={styles.sharePlanText}>Paylaş</Text></Pressable></View>
    <MotionReveal delay={45}><View style={styles.dayStrip}>{days.map((day, index) => <View key={day} style={[styles.day, index === 0 && styles.dayActive]}><Text style={[styles.dayName, index === 0 && styles.dayNameActive]}>{day}</Text><Text style={[styles.dayNumber, index === 0 && styles.dayNumberActive]}>{18 + index}</Text></View>)}</View></MotionReveal>
    <MotionReveal delay={85}><View style={styles.summary}><View style={styles.summaryIcon}><IconSymbol name="sparkles" size={22} color="#1E4D3A" /></View><View style={{ flex: 1 }}><Text style={styles.summaryTitle}>{cuisine.ui.regionalPlan} · {cuisine.region}</Text><Text style={styles.summaryText}>{cuisine.planNote} {profile.goal} hedefin ve kiler önceliklerin korunur.</Text></View></View></MotionReveal>
    <MotionReveal delay={95}><View style={styles.seasonCard}><View style={styles.seasonHead}><View><Text style={styles.seasonKicker}>{getSeasonName(profile.locale, season).toLocaleUpperCase(profile.locale)}</Text><Text style={styles.seasonTitle}>{seasonalPackage.title}</Text></View><IconSymbol name="leaf.fill" size={19} color="#1E4D3A" /></View><Text style={styles.seasonText}>{seasonalPackage.subtitle}</Text><Text style={styles.seasonIngredients}>{seasonalPackage.ingredients.join(" · ")}</Text></View></MotionReveal>
    <MotionReveal delay={105}><View style={styles.cuisineCard}><Text style={styles.cuisineLabel}>{cuisine.flag} {cuisine.region.toUpperCase()}</Text><Text style={styles.cuisineText}>Kiler odağı: {cuisine.pantryHighlights.join(" · ")}</Text><Text style={styles.cuisineTools}>Önerilen araçlar: {cuisine.recommendedTools.slice(0, 3).join(" · ")}</Text></View></MotionReveal>
    <MotionReveal delay={125}><Pressable onPress={createPersonalWeeklyPlan} style={({ pressed }) => [styles.autoPlan, pressed && { opacity: 0.8, transform: [{ scale: 0.985 }] }]}><View style={styles.autoPlanIcon}><IconSymbol name="sparkles" size={20} color="#FFFFFF" /></View><View style={{ flex: 1 }}><Text style={styles.autoPlanTitle}>{cuisine.ui.autoPlan}</Text><Text style={styles.autoPlanText}>{cuisine.ui.autoPlanText}</Text></View><IconSymbol name="chevron.right" size={20} color="#1E4D3A" /></Pressable></MotionReveal>
    <Pressable onPress={() => router.push("/pantry-weekly-ideas" as never)} style={({ pressed }) => [styles.pantryIdeas, pressed && { opacity: 0.75 }]}><View style={styles.pantryIdeasIcon}><IconSymbol name="cabinet.fill" size={19} color="#1E4D3A" /></View><View style={{ flex: 1 }}><Text style={styles.pantryIdeasTitle}>Kilerimden haftalık fikir al</Text><Text style={styles.pantryIdeasText}>Elindeki malzemeleri eşleştir; eksikleri görüp 7 günlük planına uygula.</Text></View><IconSymbol name="chevron.right" size={19} color="#1E4D3A" /></Pressable>
    <View style={styles.budgetCard}><View style={styles.budgetHead}><View><Text style={styles.budgetLabel}>HAFTALIK BÜTÇE</Text><Text style={styles.budgetValue}>{formatLocalCurrency(estimate, profile.locale)} <Text style={styles.budgetLimit}>/ {formatLocalCurrency(toLocalMarketEstimate(weeklyBudget, profile.locale), profile.locale)}</Text></Text></View><Text style={[styles.budgetStatus, estimate > toLocalMarketEstimate(weeklyBudget, profile.locale) && { color: "#B54C40" }]}>{estimate > toLocalMarketEstimate(weeklyBudget, profile.locale) ? "Limit aşıldı" : "Plan dahilinde"}</Text></View><View style={styles.budgetTrack}><View style={[styles.budgetFill, { width: `${Math.min(100, Math.round(estimate / toLocalMarketEstimate(weeklyBudget, profile.locale) * 100))}%` }]} /></View><View style={styles.budgetControls}><Pressable onPress={() => setWeeklyBudget(Math.max(500, weeklyBudget - 100))} style={styles.budgetButton}><Text style={styles.budgetButtonText}>−100</Text></Pressable><Text style={styles.budgetHint}>Market bazlı fiyatlar için listeyi paylaşabilirsin.</Text><Pressable onPress={() => setWeeklyBudget(weeklyBudget + 100)} style={styles.budgetButton}><Text style={styles.budgetButtonText}>+100</Text></Pressable></View></View>
    <View style={styles.zeroWaste}><IconSymbol name="leaf.fill" size={19} color="#1E4D3A" /><View style={{ flex: 1 }}><Text style={styles.zeroWasteTitle}>Sıfır atık koçu</Text><Text style={styles.zeroWasteText}>{urgentPantry.length ? `${urgentPantry.join(", ")} yakında tüketilmeli. Bu hafta bu ürünleri kullanan tarifler önceliklendirildi.` : "Kilerindeki son kullanma tarihlerini güncel tut; planın israfı azaltacak şekilde yenilensin."}</Text></View></View>
    <View style={styles.familySummary}><IconSymbol name="person.2.fill" size={19} color="#1E4D3A" /><View style={{ flex: 1 }}><Text style={styles.familyTitle}>Aile planı</Text><Text style={styles.familyText}>{familyProfiles.length} profilin hedefleri ve alerjenleri menü kararlarında gözetiliyor.</Text></View></View>
    <View style={styles.timeline}>{weeklyPlan.map((item) => { const recipe = getRecipe(item.recipeId); return <View key={`${item.day}-${item.recipeId}`} style={styles.mealCard}><Pressable onPress={() => router.push(`/recipe/${recipe.id}` as never)} style={({ pressed }) => [styles.mealOpen, pressed && { opacity: 0.7 }]}><View style={styles.mealDate}><Text style={styles.mealDay}>{item.day}</Text><Text style={styles.mealType}>{item.meal}</Text></View><View style={styles.mealDivider} /><View style={{ flex: 1 }}><Text style={styles.mealTitle}>{recipe.title}</Text><Text style={styles.mealMeta}>{recipe.minutes} dk · {recipe.calories} kcal</Text></View><IconSymbol name="chevron.right" size={19} color="#1E4D3A" /></Pressable><Pressable onPress={() => replaceWeeklyMeal(item.day, item.recipeId)} style={({ pressed }) => [styles.refreshButton, pressed && { opacity: 0.68, transform: [{ scale: 0.96 }] }]}><IconSymbol name="arrow.clockwise" size={16} color="#1E4D3A" /><Text style={styles.refreshText}>Alternatif</Text></Pressable></View>; })}</View>
    <Pressable onPress={() => { createGroceryFromPlan(); router.push("/shopping-list" as never); }} style={({ pressed }) => [styles.shoppingCta, pressed && { opacity: 0.85, transform: [{ scale: 0.985 }] }]}><View style={styles.shoppingIcon}><IconSymbol name="cart.fill" size={22} color="#FFFFFF" /></View><View style={{ flex: 1 }}><Text style={styles.shoppingTitle}>Alışveriş listesini hazırla</Text><Text style={styles.shoppingText}>Planındaki tüm malzemeleri tek listede topla.</Text></View><IconSymbol name="chevron.right" size={20} color="#FFFFFF" /></Pressable>
  </ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({
  content: { padding: 20, paddingBottom: 34, gap: 20 }, titleRow: { flexDirection: "row", alignItems: "center", gap: 10 }, eyebrow: { color: "#6B756F", fontSize: 10, fontWeight: "900", letterSpacing: 1.35 }, title: { color: "#1E2521", fontSize: 32, lineHeight: 38, fontWeight: "800", letterSpacing: -1, marginTop: 4 }, sharePlan: { minHeight: 38, paddingHorizontal: 10, borderRadius: 12, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 5, backgroundColor: "#DDE8DA" }, sharePlanText: { color: "#1E4D3A", fontSize: 10, fontWeight: "900" },
  dayStrip: { flexDirection: "row", justifyContent: "space-between", backgroundColor: "#FFFFFF", borderRadius: 22, padding: 8, borderWidth: 1, borderColor: "#EAE7E0", shadowColor: "#1E2521", shadowOpacity: 0.04, shadowRadius: 9, shadowOffset: { width: 0, height: 4 }, elevation: 1 }, day: { flex: 1, alignItems: "center", gap: 4, paddingVertical: 8, borderRadius: 15 }, dayActive: { backgroundColor: "#1E4D3A" }, dayName: { fontSize: 10, color: "#6B756F", fontWeight: "800" }, dayNameActive: { color: "#DDE8DA" }, dayNumber: { color: "#1E2521", fontSize: 15, fontWeight: "800" }, dayNumberActive: { color: "#FFFFFF" },
  summary: { flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: "#DDE8DA", borderRadius: 22, padding: 16, borderWidth: 1, borderColor: "#C9DCC4" }, summaryIcon: { width: 43, height: 43, borderRadius: 15, backgroundColor: "#FBF8F2", alignItems: "center", justifyContent: "center" }, summaryTitle: { color: "#1E2521", fontWeight: "800", fontSize: 15 }, summaryText: { color: "#52705E", fontSize: 12, lineHeight: 18, marginTop: 2 }, seasonCard: { gap: 5, padding: 14, borderRadius: 19, backgroundColor: "#EEF5EC", borderWidth: 1, borderColor: "#D2E4CF" }, seasonHead: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, seasonKicker: { color: "#52705E", fontSize: 9, fontWeight: "900", letterSpacing: 1 }, seasonTitle: { color: "#1E2521", fontSize: 15, fontWeight: "900", marginTop: 2 }, seasonText: { color: "#52705E", fontSize: 11, lineHeight: 16, fontWeight: "600" }, seasonIngredients: { color: "#1E4D3A", fontSize: 10, lineHeight: 15, fontWeight: "900" }, cuisineCard: { gap: 5, padding: 14, borderRadius: 18, backgroundColor: "#FFF4EA", borderWidth: 1, borderColor: "#F3D4BC" }, cuisineLabel: { color: "#9D4F20", fontSize: 10, fontWeight: "900", letterSpacing: 1 }, cuisineText: { color: "#784A28", fontSize: 12, fontWeight: "800" }, cuisineTools: { color: "#9C6B46", fontSize: 10, lineHeight: 14, fontWeight: "700" },
  autoPlan: { flexDirection: "row", alignItems: "center", gap: 11, padding: 15, borderRadius: 22, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#C9DCC4", shadowColor: "#1E4D3A", shadowOpacity: 0.06, shadowRadius: 12, shadowOffset: { width: 0, height: 5 }, elevation: 2 }, autoPlanIcon: { width: 40, height: 40, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: "#1E4D3A" }, autoPlanTitle: { color: "#1E2521", fontSize: 14, fontWeight: "800" }, autoPlanText: { color: "#6B756F", fontSize: 11, lineHeight: 16, marginTop: 2 },
  pantryIdeas: { minHeight: 67, flexDirection: "row", alignItems: "center", gap: 11, padding: 13, borderRadius: 20, backgroundColor: "#F5F8F3", borderWidth: 1, borderColor: "#C9DCC4" }, pantryIdeasIcon: { width: 39, height: 39, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "#DDE8DA" }, pantryIdeasTitle: { color: "#1E4D3A", fontSize: 13, fontWeight: "900" }, pantryIdeasText: { color: "#52705E", fontSize: 10, lineHeight: 15, marginTop: 2 },
  budgetCard: { gap: 10, padding: 14, borderRadius: 20, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EAE7E0" }, budgetHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, budgetLabel: { color: "#6B756F", fontSize: 10, fontWeight: "900", letterSpacing: 0.7 }, budgetValue: { color: "#1E2521", fontSize: 19, fontWeight: "900", marginTop: 3 }, budgetLimit: { color: "#6B756F", fontSize: 12 }, budgetStatus: { color: "#2D7A55", fontSize: 11, fontWeight: "800", paddingHorizontal: 8, paddingVertical: 5, borderRadius: 10, backgroundColor: "#DDE8DA" }, budgetTrack: { height: 7, borderRadius: 4, backgroundColor: "#E9EFE7", overflow: "hidden" }, budgetFill: { height: "100%", backgroundColor: "#1E4D3A", borderRadius: 4 }, budgetControls: { flexDirection: "row", alignItems: "center", gap: 7 }, budgetButton: { paddingHorizontal: 9, paddingVertical: 6, borderRadius: 9, backgroundColor: "#DDE8DA" }, budgetButtonText: { color: "#1E4D3A", fontSize: 10, fontWeight: "900" }, budgetHint: { flex: 1, color: "#6B756F", fontSize: 10, lineHeight: 14, textAlign: "center" }, zeroWaste: { flexDirection: "row", gap: 10, padding: 14, borderRadius: 19, backgroundColor: "#DDE8DA" }, zeroWasteTitle: { color: "#1E2521", fontSize: 13, fontWeight: "800" }, zeroWasteText: { color: "#52705E", fontSize: 11, lineHeight: 16, marginTop: 2 }, familySummary: { flexDirection: "row", gap: 10, padding: 14, borderRadius: 19, backgroundColor: "#F5F8F3", borderWidth: 1, borderColor: "#D5E3D3" }, familyTitle: { color: "#1E2521", fontSize: 13, fontWeight: "800" }, familyText: { color: "#6B756F", fontSize: 11, lineHeight: 16, marginTop: 2 },
  timeline: { gap: 10 }, mealCard: { backgroundColor: "#FFFFFF", borderRadius: 19, borderWidth: 1, borderColor: "#EAE7E0", padding: 12, gap: 9 }, mealOpen: { flexDirection: "row", alignItems: "center", gap: 12 }, mealDate: { width: 47, gap: 2 }, mealDay: { color: "#1E4D3A", fontSize: 13, fontWeight: "900" }, mealType: { color: "#6B756F", fontSize: 10, fontWeight: "700" }, mealDivider: { width: 1, height: 34, backgroundColor: "#EAE7E0" }, mealTitle: { color: "#1E2521", fontSize: 14, fontWeight: "800" }, mealMeta: { color: "#6B756F", fontSize: 11, marginTop: 3, fontWeight: "600" }, refreshButton: { minHeight: 32, paddingHorizontal: 10, borderRadius: 11, backgroundColor: "#DDE8DA", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6 }, refreshText: { color: "#1E4D3A", fontSize: 11, fontWeight: "800" },
  shoppingCta: { flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: "#1E4D3A", borderRadius: 22, padding: 16, marginTop: 4 }, shoppingIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: "#34684F", alignItems: "center", justifyContent: "center" }, shoppingTitle: { color: "#FFFFFF", fontSize: 15, fontWeight: "800" }, shoppingText: { color: "#DDE8DA", fontSize: 11, lineHeight: 16, marginTop: 2 },
});
