import { Alert, Pressable, ScrollView, StyleSheet, TextInput, View } from "react-native";
import { router } from "expo-router";
import { useState } from "react";

import { IconSymbol } from "@/components/ui/icon-symbol";
import { LocalizedText as Text } from "@/components/localized-text";
import { ScreenContainer } from "@/components/screen-container";
import { useLezzet } from "@/lib/lezzet-context";
import { getCuisineProfile } from "@/lib/cuisine-locale";
import { dietaryOptions } from "@/lib/seasonal-market";

export default function ProfileScreen() {
  const { favorites, pantry, profile, wearableActivity, kitchenTools, familyProfiles, addFamilyProfile, updateProfile, marketPrices, resetPantry, loadRegionalSamplePantry } = useLezzet();
  const cuisine = getCuisineProfile(profile.locale);
  const dietarySummary = profile.dietaryPreferences.length ? profile.dietaryPreferences.map((item) => dietaryOptions.find((option) => option.id === item)?.labels[profile.locale]).filter(Boolean).join(" · ") : "Tercih seç";
  const [familyName, setFamilyName] = useState("");
  const goals = ["Dengeli beslenme", "Kilo kontrolü", "Protein odağı"];
  const resetCurrentPantry = () => Alert.alert("Kileri sıfırla", "Kilerdeki tüm ürünler ve stok bilgileri silinecek. Alışveriş listen korunur.", [{ text: "Vazgeç", style: "cancel" }, { text: "Kileri sıfırla", style: "destructive", onPress: resetPantry }]);
  const reloadSamplePantry = () => Alert.alert("Örnek kileri yükle", `${cuisine.pantryHighlights.join(", ")} ürünleri kilerindeki mevcut ürünlerin yerine geçer. Bu ürünlere göre ilk hafta planın da yenilenir.`, [{ text: "Vazgeç", style: "cancel" }, { text: "Yükle", onPress: loadRegionalSamplePantry }]);
  return <ScreenContainer className="flex-1" containerClassName="bg-background"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <View style={styles.profileHead}><View style={styles.largeAvatar}><Text style={styles.largeAvatarText}>D</Text></View><View><Text style={styles.name}>Deniz Kaya</Text><Text style={styles.subtitle}>LezzetAI üyesi</Text></View></View>
    <View style={styles.stats}><View style={styles.stat}><Text style={styles.statNumber}>{favorites.length}</Text><Text style={styles.statLabel}>Kaydedilen</Text></View><View style={styles.statLine} /><View style={styles.stat}><Text style={styles.statNumber}>{profile.people}</Text><Text style={styles.statLabel}>Kişilik plan</Text></View><View style={styles.statLine} /><View style={styles.stat}><Text style={styles.statNumber}>{profile.calories}</Text><Text style={styles.statLabel}>kcal hedefi</Text></View></View>
    <View style={styles.section}><Text style={styles.sectionTitle}>Beslenme hedefin</Text><View style={styles.goalList}>{goals.map((goal) => <Pressable key={goal} onPress={() => updateProfile({ goal })} style={({ pressed }) => [styles.goal, profile.goal === goal && styles.goalActive, pressed && { opacity: 0.7 }]}><Text style={[styles.goalText, profile.goal === goal && styles.goalTextActive]}>{goal}</Text>{profile.goal === goal ? <IconSymbol name="checkmark.circle.fill" size={18} color="#FFFFFF" /> : null}</Pressable>)}</View></View>
    <View style={styles.section}><Text style={styles.sectionTitle}>Tercihlerin</Text><View style={styles.settings}><Setting icon="globe" label="Dil ve mutfak bölgesi" value={`${cuisine.language} · ${cuisine.region}`} onPress={() => router.push("/cuisine-region" as never)} /><Setting icon="leaf.fill" label="Beslenme filtreleri" value={dietarySummary} onPress={() => router.push("/diet-preferences" as never)} /><Setting icon="exclamationmark.triangle.fill" label="Alerjenler" value={profile.allergies.length ? profile.allergies.join(", ") : "Alerjen ekle"} onPress={() => router.push("/allergy-preferences" as never)} /><Setting icon="cart.fill" label="Yerel market fiyatları" value={`${cuisine.region} · ${Object.values(marketPrices[profile.locale]).length} reyon`} onPress={() => router.push("/market-prices" as never)} /><Setting icon="person.2.fill" label="Aile ortak alanı" value="Davetli ortak kiler ve liste" onPress={() => router.push("/family-pantry" as never)} /><Setting icon="chart.bar.fill" label="Fiş harcama analizi" value="Onaylı gerçek fiyatlar" onPress={() => router.push("/spending-insights" as never)} /><Setting icon="person.2.fill" label="Kişi sayısı" value={`${profile.people} kişi · 1–12`} onPress={() => updateProfile({ people: profile.people === 12 ? 1 : profile.people + 1 })} /><Setting icon="flame.fill" label="Günlük enerji hedefi" value={`${profile.calories} kcal`} onPress={() => updateProfile({ calories: profile.calories === 2250 ? 1650 : profile.calories + 200 })} /><Setting icon="sparkles" label="Aktivite senkronizasyonu" value={wearableActivity ? `${wearableActivity.source} · ${wearableActivity.steps.toLocaleString(profile.locale)} adım` : "Cihazını bağla"} onPress={() => router.push("/wearables" as never)} /><Setting icon="cabinet.fill" label="Mutfak ekipmanları" value={kitchenTools.length ? `${kitchenTools.length} araç seçili` : "Araçlarını seç"} onPress={() => router.push("/kitchen-tools" as never)} /><Setting icon="chart.bar.fill" label="Mutfak günlüğü" value="Pişirme deneyimlerin" onPress={() => router.push("/journal" as never)} /><Setting icon="safari" label="Şef koleksiyonları" value="Tematik tarif serileri" onPress={() => router.push("/collections" as never)} /><Setting icon="bell.fill" label="Hatırlatıcılar" value="Açık" /><Setting icon="lock.fill" label="Gizlilik ve veriler" value="Verilerini nasıl kullandığımız" onPress={() => router.push("/privacy" as never)} /></View></View>
    <View style={styles.section}><Text style={styles.sectionTitle}>Kiler yönetimi</Text><View style={styles.pantryTools}><Text style={styles.pantryToolText}>{pantry.length ? `${pantry.length} ürün kilerinde kayıtlı.` : "Kilerin şu an boş."}</Text><Pressable onPress={reloadSamplePantry} style={({ pressed }) => [styles.samplePantryButton, pressed && { opacity: 0.75 }]}><IconSymbol name="sparkles" size={18} color="#FFFFFF" /><View style={{ flex: 1 }}><Text style={styles.samplePantryTitle}>Bölgesel örnek kileri yükle</Text><Text style={styles.samplePantryHint}>Ürünleri ve ilk hafta planını yeniler.</Text></View></Pressable><Pressable onPress={resetCurrentPantry} style={({ pressed }) => [styles.resetPantryButton, pressed && { opacity: 0.7 }]}><IconSymbol name="cabinet.fill" size={18} color="#9D332A" /><View style={{ flex: 1 }}><Text style={styles.resetPantryTitle}>Kilerimi tamamen sıfırla</Text><Text style={styles.resetPantryHint}>Ürünleri ve stok bilgilerini kaldırır.</Text></View></Pressable></View></View>
    <View style={styles.section}><Text style={styles.sectionTitle}>Aile profilleri</Text><View style={styles.familyCard}><Text style={styles.familyText}>{familyProfiles.map((member) => member.name).join(", ")} · hedef ve alerjen tercihleri korunur.</Text><View style={styles.familyAdd}><TextInput value={familyName} onChangeText={setFamilyName} placeholder="Yeni aile üyesi" placeholderTextColor="#87918B" style={styles.familyInput} /><Pressable onPress={() => { if (familyName.trim()) { addFamilyProfile({ name: familyName.trim(), goal: "Dengeli beslenme", allergies: [] }); setFamilyName(""); } }} style={styles.familyButton}><Text style={styles.familyButtonText}>Ekle</Text></Pressable></View></View></View>
    <Text style={styles.privacy}>Tercihlerin yalnızca cihazında saklanır.</Text>
  </ScrollView></ScreenContainer>;
}

function Setting({ icon, label, value, onPress }: { icon: "globe" | "person.2.fill" | "flame.fill" | "sparkles" | "cabinet.fill" | "chart.bar.fill" | "safari" | "leaf.fill" | "bell.fill" | "lock.fill" | "cart.fill" | "exclamationmark.triangle.fill"; label: string; value: string; onPress?: () => void }) { return <Pressable onPress={onPress} disabled={!onPress} style={({ pressed }) => [styles.setting, pressed && onPress && { opacity: 0.65 }]}><View style={styles.settingIcon}><IconSymbol name={icon} size={19} color="#1E4D3A" /></View><View style={{ flex: 1 }}><Text style={styles.settingLabel}>{label}</Text><Text style={styles.settingValue}>{value}</Text></View><IconSymbol name="chevron.right" size={18} color="#6B756F" /></Pressable>; }

const styles = StyleSheet.create({
  content: { padding: 20, paddingBottom: 32, gap: 24 }, profileHead: { flexDirection: "row", alignItems: "center", gap: 14 }, largeAvatar: { width: 64, height: 64, borderRadius: 22, backgroundColor: "#1E4D3A", borderWidth: 4, borderColor: "#DDE8DA", alignItems: "center", justifyContent: "center" }, largeAvatarText: { color: "#FFFFFF", fontSize: 25, fontWeight: "800" }, name: { color: "#1E2521", fontSize: 23, fontWeight: "800", letterSpacing: -0.4 }, subtitle: { color: "#6B756F", fontSize: 13, marginTop: 3 },
  stats: { flexDirection: "row", backgroundColor: "#FFFFFF", borderRadius: 20, borderWidth: 1, borderColor: "#EAE7E0", paddingVertical: 16 }, stat: { flex: 1, alignItems: "center", gap: 3 }, statLine: { width: 1, backgroundColor: "#EAE7E0" }, statNumber: { color: "#1E4D3A", fontSize: 17, fontWeight: "900" }, statLabel: { color: "#6B756F", fontSize: 10, fontWeight: "700" },
  section: { gap: 12 }, sectionTitle: { color: "#1E2521", fontSize: 17, fontWeight: "800" }, goalList: { gap: 8 }, goal: { minHeight: 50, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 15, borderRadius: 16, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EAE7E0" }, goalActive: { backgroundColor: "#1E4D3A", borderColor: "#1E4D3A" }, goalText: { color: "#1E2521", fontSize: 14, fontWeight: "700" }, goalTextActive: { color: "#FFFFFF" },
  settings: { backgroundColor: "#FFFFFF", borderRadius: 20, borderWidth: 1, borderColor: "#EAE7E0", overflow: "hidden" }, setting: { minHeight: 70, flexDirection: "row", alignItems: "center", gap: 12, paddingHorizontal: 14, borderBottomWidth: 1, borderBottomColor: "#F0EEE9" }, settingIcon: { width: 38, height: 38, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: "#DDE8DA" }, settingLabel: { color: "#1E2521", fontSize: 14, fontWeight: "800" }, settingValue: { color: "#6B756F", fontSize: 12, marginTop: 2 }, pantryTools: { gap: 9, padding: 14, borderRadius: 19, backgroundColor: "#F5F8F3", borderWidth: 1, borderColor: "#D5E3D3" }, pantryToolText: { color: "#52705E", fontSize: 12, lineHeight: 17 }, samplePantryButton: { minHeight: 62, flexDirection: "row", alignItems: "center", gap: 10, padding: 11, borderRadius: 15, backgroundColor: "#1E4D3A" }, samplePantryTitle: { color: "#FFFFFF", fontSize: 12, fontWeight: "900" }, samplePantryHint: { color: "#DDE8DA", fontSize: 10, marginTop: 2 }, resetPantryButton: { minHeight: 62, flexDirection: "row", alignItems: "center", gap: 10, padding: 11, borderRadius: 15, backgroundColor: "#FFF1EE", borderWidth: 1, borderColor: "#F2C8C1" }, resetPantryTitle: { color: "#9D332A", fontSize: 12, fontWeight: "900" }, resetPantryHint: { color: "#B54C40", fontSize: 10, marginTop: 2 }, familyCard: { gap: 10, padding: 14, borderRadius: 19, backgroundColor: "#F5F8F3", borderWidth: 1, borderColor: "#D5E3D3" }, familyText: { color: "#52705E", fontSize: 12, lineHeight: 17 }, familyAdd: { flexDirection: "row", gap: 8 }, familyInput: { flex: 1, height: 40, borderRadius: 11, backgroundColor: "#FFFFFF", paddingHorizontal: 11, color: "#1E2521", fontSize: 12 }, familyButton: { alignItems: "center", justifyContent: "center", paddingHorizontal: 13, borderRadius: 11, backgroundColor: "#1E4D3A" }, familyButtonText: { color: "#FFFFFF", fontSize: 11, fontWeight: "800" }, privacy: { color: "#6B756F", textAlign: "center", fontSize: 11, fontWeight: "600" },
});
