import { Alert, Image, Pressable, ScrollView, StyleSheet, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { useState } from "react";

import { IconSymbol } from "@/components/ui/icon-symbol";
import { LocalizedText as Text } from "@/components/localized-text";
import { ScreenContainer } from "@/components/screen-container";
import { getEquipmentAdvice, getRecipe } from "@/lib/lezzet-data";
import { useLezzet } from "@/lib/lezzet-context";
import { formatTry, getRecipeEstimate, scaleIngredientList } from "@/lib/culinary-utils";
import { crossContactChecklist, formatLocalCurrency, getDirectAllergenMatches, toLocalMarketEstimate } from "@/lib/seasonal-market";

export default function RecipeDetailScreen() {
  const params = useLocalSearchParams<{ id?: string }>();
  const recipe = getRecipe(params.id);
  const { favorites, toggleFavorite, addRecipeToPlan, kitchenTools, profile, recipeFeedback, setRecipeFeedback, addJournalEntry } = useLezzet();
  const isFavorite = favorites.includes(recipe.id);
  const [portions, setPortions] = useState(profile.people);
  const equipmentAdvice = getEquipmentAdvice(recipe, kitchenTools);
  const feedback = recipeFeedback[recipe.id];
  const directAllergens = getDirectAllergenMatches(recipe.ingredients, profile.allergies);
  const saveToPlan = () => { addRecipeToPlan(recipe.id); Alert.alert("Planına eklendi", `${recipe.title} Cumartesi akşamına eklendi.`); };

  return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="flex-1" containerClassName="bg-background"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <View style={styles.media}><Image source={recipe.image} style={styles.image} resizeMode="cover" /><View style={styles.mediaShade} /><View style={styles.mediaActions}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.roundButton, pressed && { opacity: 0.65 }]}><IconSymbol name="chevron.left" size={24} color="#1E4D3A" /></Pressable><Pressable onPress={() => toggleFavorite(recipe.id)} style={({ pressed }) => [styles.roundButton, pressed && { opacity: 0.65 }]}><IconSymbol name={isFavorite ? "heart.fill" : "heart"} size={21} color={isFavorite ? "#D4553E" : "#1E4D3A"} /></Pressable></View><View style={styles.mediaTag}><Text style={styles.mediaTagText}>{recipe.category}</Text></View></View>
    <View style={styles.body}><Text style={styles.title}>{recipe.title}</Text><Text style={styles.subtitle}>{recipe.subtitle}</Text><View style={styles.metaRow}><Meta icon="clock" value={`${recipe.minutes} dk`} label="Hazırlık" /><Meta icon="flame.fill" value={`${recipe.calories}`} label="kcal" /><Meta icon="leaf.fill" value={`${recipe.protein} g`} label="protein" /><Meta icon="sparkles" value={recipe.difficulty} label="Seviye" /></View>
      <View style={[styles.allergenCard, directAllergens.length > 0 && styles.allergenCardCritical]}><View style={styles.allergenHead}><IconSymbol name={directAllergens.length > 0 ? "exclamationmark.triangle.fill" : "checkmark.circle.fill"} size={19} color={directAllergens.length > 0 ? "#A64532" : "#1E4D3A"} /><View style={{ flex: 1 }}><Text style={[styles.allergenTitle, directAllergens.length > 0 && styles.allergenTitleCritical]}>Alerjen ve çapraz temas kontrolü</Text><Text style={[styles.allergenSummary, directAllergens.length > 0 && styles.allergenSummaryCritical]}>{directAllergens.length > 0 ? `Profiline göre bu tarif şunları içerebilir: ${directAllergens.join(", ")}.` : profile.allergies.length ? "Profilindeki alerjenlerle doğrudan içerik eşleşmesi saptanmadı." : "Profilinde alerjen seçilmedi; pişirmeden önce malzemeleri yine kontrol et."}</Text></View></View><View style={styles.checklist}>{crossContactChecklist.map((item) => <View key={item} style={styles.checkItem}><View style={[styles.checkDot, directAllergens.length > 0 && styles.checkDotCritical]} /><Text style={[styles.checkText, directAllergens.length > 0 && styles.checkTextCritical]}>{item}</Text></View>)}</View><Text style={[styles.allergenFootnote, directAllergens.length > 0 && styles.allergenFootnoteCritical]}>Bu kontrol bilgi amaçlıdır; paket etiketini ve “içerebilir” uyarılarını mutlaka incele.</Text></View>
      <View style={[styles.equipmentAdvice, !equipmentAdvice.available && styles.equipmentAdviceFallback]}><View style={[styles.equipmentIcon, !equipmentAdvice.available && styles.equipmentIconFallback]}><IconSymbol name={equipmentAdvice.available ? "sparkles" : "cabinet.fill"} size={19} color={equipmentAdvice.available ? "#1E4D3A" : "#B7652E"} /></View><View style={{ flex: 1 }}><Text style={styles.equipmentTitle}>{equipmentAdvice.available ? `En hızlı ekipman: ${equipmentAdvice.tool}` : `Alternatif yöntem · ${equipmentAdvice.tool}`}</Text><Text style={styles.equipmentText}>{equipmentAdvice.text}</Text></View></View>
      <View style={styles.divider} />
      <View style={styles.portionRow}><View><Text style={styles.sectionTitle}>Malzemeler</Text><Text style={styles.portion}>{portions} kişilik · {formatLocalCurrency(toLocalMarketEstimate(getRecipeEstimate(recipe.estimatedCost, portions), profile.locale), profile.locale)} tahmini</Text></View><View style={styles.portionControls}><Pressable onPress={() => setPortions(Math.max(1, portions - 1))} style={styles.portionButton}><Text style={styles.portionButtonText}>−</Text></Pressable><Pressable onPress={() => setPortions(Math.min(8, portions + 1))} style={styles.portionButton}><Text style={styles.portionButtonText}>+</Text></Pressable></View></View><View style={styles.macroRow}><Text style={styles.macro}>P {Math.round(recipe.protein * portions / 2)}g</Text><Text style={styles.macro}>K {Math.round(recipe.carbs * portions / 2)}g</Text><Text style={styles.macro}>Y {Math.round(recipe.fat * portions / 2)}g</Text></View><View style={styles.ingredients}>{scaleIngredientList(recipe.ingredients, portions).map((item) => <View style={styles.ingredient} key={item}><View style={styles.bullet} /><Text style={styles.ingredientText}>{item}</Text></View>)}</View>
      <Text style={styles.sectionTitle}>Adım adım</Text><View style={styles.steps}>{recipe.steps.map((step, index) => <View style={styles.step} key={step}><View style={styles.stepNumber}><Text style={styles.stepNumberText}>{index + 1}</Text></View><Text style={styles.stepText}>{step}</Text></View>)}</View>
      <View style={styles.tip}><IconSymbol name="sparkles" size={18} color="#B7652E" /><View style={{ flex: 1 }}><Text style={styles.tipTitle}>AI Şefin notu</Text><Text style={styles.tipText}>Bu tarifi daha tok tutucu yapmak için yanına bir dilim tam tahıllı ekmek ekleyebilirsin.</Text></View></View>
      <View style={styles.feedback}><Text style={styles.feedbackTitle}>Bu öneri sana uygun mu?</Text><View style={styles.feedbackButtons}><Pressable onPress={() => setRecipeFeedback(recipe.id, { liked: true, difficulty: "Tam kararında" })} style={[styles.feedbackButton, feedback?.liked && styles.feedbackSelected]}><Text style={styles.feedbackText}>Beğendim</Text></Pressable><Pressable onPress={() => setRecipeFeedback(recipe.id, { liked: false })} style={[styles.feedbackButton, feedback?.liked === false && styles.feedbackSelectedWarm]}><Text style={styles.feedbackText}>Başka öner</Text></Pressable></View></View>
      <Pressable onPress={() => router.push(`/cook/${recipe.id}` as never)} style={({ pressed }) => [styles.cookButton, pressed && { opacity: 0.85, transform: [{ scale: 0.985 }] }]}><IconSymbol name="clock" size={19} color="#1E4D3A" /><Text style={styles.cookButtonText}>Canlı pişirme modunu başlat</Text><IconSymbol name="chevron.right" size={18} color="#1E4D3A" /></Pressable>
      <Pressable onPress={() => router.push({ pathname: "/journal-entry", params: { recipeId: recipe.id } } as never)} style={({ pressed }) => [styles.journalButton, pressed && { opacity: 0.72 }]}><Text style={styles.journalText}>Pişirdim, günlüğe ekle</Text></Pressable>
      <Pressable onPress={saveToPlan} style={({ pressed }) => [styles.planButton, pressed && { opacity: 0.85, transform: [{ scale: 0.985 }] }]}><Text style={styles.planButtonText}>Haftalık plana ekle</Text><IconSymbol name="calendar" size={19} color="#FFFFFF" /></Pressable>
    </View>
  </ScrollView></ScreenContainer>;
}

function Meta({ icon, value, label }: { icon: "clock" | "flame.fill" | "leaf.fill" | "sparkles"; value: string; label: string }) { return <View style={styles.meta}><IconSymbol name={icon} size={17} color="#1E4D3A" /><Text style={styles.metaValue}>{value}</Text><Text style={styles.metaLabel}>{label}</Text></View>; }

const styles = StyleSheet.create({
  content: { paddingBottom: 28 }, media: { height: 306, position: "relative", overflow: "hidden" }, image: { ...StyleSheet.absoluteFillObject, width: undefined, height: undefined }, mediaShade: { ...StyleSheet.absoluteFillObject, backgroundColor: "#0C251A", opacity: 0.12 }, mediaActions: { position: "absolute", top: 14, left: 16, right: 16, flexDirection: "row", justifyContent: "space-between" }, roundButton: { width: 43, height: 43, borderRadius: 15, backgroundColor: "#FBF8F2", alignItems: "center", justifyContent: "center", shadowColor: "#1E2521", shadowOpacity: 0.11, shadowRadius: 8, shadowOffset: { width: 0, height: 3 }, elevation: 2 }, mediaTag: { position: "absolute", bottom: 17, left: 18, borderRadius: 14, backgroundColor: "#FBF8F2", paddingHorizontal: 11, paddingVertical: 7 }, mediaTagText: { color: "#1E4D3A", fontSize: 11, fontWeight: "900", letterSpacing: 0.35, textTransform: "uppercase" },
  body: { padding: 20, gap: 12 }, title: { color: "#1E2521", fontSize: 28, lineHeight: 34, letterSpacing: -0.7, fontWeight: "800" }, subtitle: { color: "#6B756F", fontSize: 14, lineHeight: 20 }, metaRow: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 14, backgroundColor: "#F5F8F3", borderRadius: 18 }, meta: { flex: 1, alignItems: "center", gap: 3 }, metaValue: { color: "#1E2521", fontSize: 12, fontWeight: "900" }, metaLabel: { color: "#6B756F", fontSize: 9, fontWeight: "700" }, divider: { height: 1, backgroundColor: "#EAE7E0", marginVertical: 5 }, sectionTitle: { color: "#1E2521", fontSize: 18, fontWeight: "800", marginTop: 5 }, portion: { color: "#6B756F", fontSize: 12, marginTop: -7 },
  allergenCard: { gap: 10, padding: 14, borderRadius: 18, backgroundColor: "#EEF5EC", borderWidth: 1, borderColor: "#C9DCC4" }, allergenCardCritical: { backgroundColor: "#FCE8E3", borderColor: "#E7B4A8" }, allergenHead: { flexDirection: "row", alignItems: "flex-start", gap: 9 }, allergenTitle: { color: "#1E4D3A", fontSize: 13, fontWeight: "900" }, allergenTitleCritical: { color: "#8D392D" }, allergenSummary: { color: "#52705E", fontSize: 11, lineHeight: 16, marginTop: 2, fontWeight: "600" }, allergenSummaryCritical: { color: "#8D392D" }, checklist: { gap: 5 }, checkItem: { flexDirection: "row", gap: 7, alignItems: "flex-start" }, checkDot: { width: 5, height: 5, borderRadius: 3, marginTop: 6, backgroundColor: "#2D7A55" }, checkDotCritical: { backgroundColor: "#C84D40" }, checkText: { flex: 1, color: "#52705E", fontSize: 10, lineHeight: 15, fontWeight: "600" }, checkTextCritical: { color: "#8D392D" }, allergenFootnote: { color: "#6B756F", fontSize: 9, lineHeight: 13, fontWeight: "700" }, allergenFootnoteCritical: { color: "#9D4F45" }, equipmentAdvice: { flexDirection: "row", alignItems: "center", gap: 10, backgroundColor: "#DDE8DA", borderRadius: 18, padding: 13 }, equipmentAdviceFallback: { backgroundColor: "#FCE6D2" }, equipmentIcon: { width: 38, height: 38, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "#FFFFFF" }, equipmentIconFallback: { backgroundColor: "#FFFFFF" }, equipmentTitle: { color: "#1E2521", fontSize: 13, fontWeight: "800" }, equipmentText: { color: "#52705E", fontSize: 11, lineHeight: 16, marginTop: 2 },
  portionRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, portionControls: { flexDirection: "row", gap: 7 }, portionButton: { width: 32, height: 32, borderRadius: 11, backgroundColor: "#DDE8DA", alignItems: "center", justifyContent: "center" }, portionButtonText: { color: "#1E4D3A", fontSize: 18, fontWeight: "800" }, macroRow: { flexDirection: "row", gap: 7, marginTop: -5 }, macro: { color: "#52705E", fontSize: 10, fontWeight: "800", backgroundColor: "#DDE8DA", paddingHorizontal: 8, paddingVertical: 5, borderRadius: 9 }, ingredients: { gap: 10, marginTop: 3 }, ingredient: { flexDirection: "row", gap: 10, alignItems: "center" }, bullet: { width: 7, height: 7, borderRadius: 4, backgroundColor: "#F4A261" }, ingredientText: { flex: 1, color: "#49554D", fontSize: 14, lineHeight: 19 }, steps: { gap: 13, marginTop: 4 }, step: { flexDirection: "row", gap: 12 }, stepNumber: { width: 27, height: 27, borderRadius: 14, backgroundColor: "#1E4D3A", alignItems: "center", justifyContent: "center" }, stepNumberText: { color: "#FFFFFF", fontSize: 12, fontWeight: "900" }, stepText: { flex: 1, color: "#49554D", fontSize: 14, lineHeight: 20, paddingTop: 2 },
  tip: { flexDirection: "row", gap: 10, backgroundColor: "#FCE6D2", borderRadius: 18, padding: 13, marginTop: 8 }, tipTitle: { color: "#754626", fontSize: 13, fontWeight: "800" }, tipText: { color: "#9A6138", fontSize: 12, lineHeight: 17, marginTop: 2 }, feedback: { gap: 9, padding: 13, borderRadius: 18, backgroundColor: "#F5F8F3" }, feedbackTitle: { color: "#1E2521", fontSize: 13, fontWeight: "800" }, feedbackButtons: { flexDirection: "row", gap: 8 }, feedbackButton: { flex: 1, minHeight: 37, alignItems: "center", justifyContent: "center", borderRadius: 11, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#D5E3D3" }, feedbackSelected: { backgroundColor: "#DDE8DA", borderColor: "#1E4D3A" }, feedbackSelectedWarm: { backgroundColor: "#FCE6D2", borderColor: "#B7652E" }, feedbackText: { color: "#1E4D3A", fontSize: 11, fontWeight: "800" }, cookButton: { minHeight: 50, borderRadius: 16, backgroundColor: "#DDE8DA", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 }, cookButtonText: { flex: 1, color: "#1E4D3A", fontSize: 14, fontWeight: "800" }, journalButton: { minHeight: 41, alignItems: "center", justifyContent: "center" }, journalText: { color: "#1E4D3A", fontSize: 12, fontWeight: "800" }, planButton: { minHeight: 52, marginTop: 1, borderRadius: 16, backgroundColor: "#1E4D3A", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 9 }, planButtonText: { color: "#FFFFFF", fontSize: 15, fontWeight: "800" },
});
