import { Alert, Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";

import { IconSymbol } from "@/components/ui/icon-symbol";
import { ScreenContainer } from "@/components/screen-container";
import { getEquipmentAdvice, getRecipe } from "@/lib/lezzet-data";
import { useLezzet } from "@/lib/lezzet-context";

export default function RecipeDetailScreen() {
  const params = useLocalSearchParams<{ id?: string }>();
  const recipe = getRecipe(params.id);
  const { favorites, toggleFavorite, addRecipeToPlan, kitchenTools } = useLezzet();
  const isFavorite = favorites.includes(recipe.id);
  const equipmentAdvice = getEquipmentAdvice(recipe, kitchenTools);
  const saveToPlan = () => { addRecipeToPlan(recipe.id); Alert.alert("Planına eklendi", `${recipe.title} Cumartesi akşamına eklendi.`); };

  return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="flex-1" containerClassName="bg-background"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <View style={styles.media}><Image source={recipe.image} style={styles.image} resizeMode="cover" /><View style={styles.mediaShade} /><View style={styles.mediaActions}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.roundButton, pressed && { opacity: 0.65 }]}><IconSymbol name="chevron.left" size={24} color="#1E4D3A" /></Pressable><Pressable onPress={() => toggleFavorite(recipe.id)} style={({ pressed }) => [styles.roundButton, pressed && { opacity: 0.65 }]}><IconSymbol name={isFavorite ? "heart.fill" : "heart"} size={21} color={isFavorite ? "#D4553E" : "#1E4D3A"} /></Pressable></View><View style={styles.mediaTag}><Text style={styles.mediaTagText}>{recipe.category}</Text></View></View>
    <View style={styles.body}><Text style={styles.title}>{recipe.title}</Text><Text style={styles.subtitle}>{recipe.subtitle}</Text><View style={styles.metaRow}><Meta icon="clock" value={`${recipe.minutes} dk`} label="Hazırlık" /><Meta icon="flame.fill" value={`${recipe.calories}`} label="kcal" /><Meta icon="leaf.fill" value={`${recipe.protein} g`} label="protein" /><Meta icon="sparkles" value={recipe.difficulty} label="Seviye" /></View>
      <View style={[styles.equipmentAdvice, !equipmentAdvice.available && styles.equipmentAdviceFallback]}><View style={[styles.equipmentIcon, !equipmentAdvice.available && styles.equipmentIconFallback]}><IconSymbol name={equipmentAdvice.available ? "sparkles" : "cabinet.fill"} size={19} color={equipmentAdvice.available ? "#1E4D3A" : "#B7652E"} /></View><View style={{ flex: 1 }}><Text style={styles.equipmentTitle}>{equipmentAdvice.available ? `En hızlı ekipman: ${equipmentAdvice.tool}` : `Alternatif yöntem · ${equipmentAdvice.tool}`}</Text><Text style={styles.equipmentText}>{equipmentAdvice.text}</Text></View></View>
      <View style={styles.divider} />
      <Text style={styles.sectionTitle}>Malzemeler</Text><Text style={styles.portion}>2 kişilik</Text><View style={styles.ingredients}>{recipe.ingredients.map((item) => <View style={styles.ingredient} key={item}><View style={styles.bullet} /><Text style={styles.ingredientText}>{item}</Text></View>)}</View>
      <Text style={styles.sectionTitle}>Adım adım</Text><View style={styles.steps}>{recipe.steps.map((step, index) => <View style={styles.step} key={step}><View style={styles.stepNumber}><Text style={styles.stepNumberText}>{index + 1}</Text></View><Text style={styles.stepText}>{step}</Text></View>)}</View>
      <View style={styles.tip}><IconSymbol name="sparkles" size={18} color="#B7652E" /><View style={{ flex: 1 }}><Text style={styles.tipTitle}>AI Şefin notu</Text><Text style={styles.tipText}>Bu tarifi daha tok tutucu yapmak için yanına bir dilim tam tahıllı ekmek ekleyebilirsin.</Text></View></View>
      <Pressable onPress={saveToPlan} style={({ pressed }) => [styles.planButton, pressed && { opacity: 0.85, transform: [{ scale: 0.985 }] }]}><Text style={styles.planButtonText}>Haftalık plana ekle</Text><IconSymbol name="calendar" size={19} color="#FFFFFF" /></Pressable>
    </View>
  </ScrollView></ScreenContainer>;
}

function Meta({ icon, value, label }: { icon: "clock" | "flame.fill" | "leaf.fill" | "sparkles"; value: string; label: string }) { return <View style={styles.meta}><IconSymbol name={icon} size={17} color="#1E4D3A" /><Text style={styles.metaValue}>{value}</Text><Text style={styles.metaLabel}>{label}</Text></View>; }

const styles = StyleSheet.create({
  content: { paddingBottom: 28 }, media: { height: 306, position: "relative", overflow: "hidden" }, image: { ...StyleSheet.absoluteFillObject, width: undefined, height: undefined }, mediaShade: { ...StyleSheet.absoluteFillObject, backgroundColor: "#0C251A", opacity: 0.12 }, mediaActions: { position: "absolute", top: 14, left: 16, right: 16, flexDirection: "row", justifyContent: "space-between" }, roundButton: { width: 43, height: 43, borderRadius: 15, backgroundColor: "#FBF8F2", alignItems: "center", justifyContent: "center", shadowColor: "#1E2521", shadowOpacity: 0.11, shadowRadius: 8, shadowOffset: { width: 0, height: 3 }, elevation: 2 }, mediaTag: { position: "absolute", bottom: 17, left: 18, borderRadius: 14, backgroundColor: "#FBF8F2", paddingHorizontal: 11, paddingVertical: 7 }, mediaTagText: { color: "#1E4D3A", fontSize: 11, fontWeight: "900", letterSpacing: 0.35, textTransform: "uppercase" },
  body: { padding: 20, gap: 12 }, title: { color: "#1E2521", fontSize: 28, lineHeight: 34, letterSpacing: -0.7, fontWeight: "800" }, subtitle: { color: "#6B756F", fontSize: 14, lineHeight: 20 }, metaRow: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 14, backgroundColor: "#F5F8F3", borderRadius: 18 }, meta: { flex: 1, alignItems: "center", gap: 3 }, metaValue: { color: "#1E2521", fontSize: 12, fontWeight: "900" }, metaLabel: { color: "#6B756F", fontSize: 9, fontWeight: "700" }, divider: { height: 1, backgroundColor: "#EAE7E0", marginVertical: 5 }, sectionTitle: { color: "#1E2521", fontSize: 18, fontWeight: "800", marginTop: 5 }, portion: { color: "#6B756F", fontSize: 12, marginTop: -7 },
  equipmentAdvice: { flexDirection: "row", alignItems: "center", gap: 10, backgroundColor: "#DDE8DA", borderRadius: 18, padding: 13 }, equipmentAdviceFallback: { backgroundColor: "#FCE6D2" }, equipmentIcon: { width: 38, height: 38, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "#FFFFFF" }, equipmentIconFallback: { backgroundColor: "#FFFFFF" }, equipmentTitle: { color: "#1E2521", fontSize: 13, fontWeight: "800" }, equipmentText: { color: "#52705E", fontSize: 11, lineHeight: 16, marginTop: 2 },
  ingredients: { gap: 10, marginTop: 3 }, ingredient: { flexDirection: "row", gap: 10, alignItems: "center" }, bullet: { width: 7, height: 7, borderRadius: 4, backgroundColor: "#F4A261" }, ingredientText: { flex: 1, color: "#49554D", fontSize: 14, lineHeight: 19 }, steps: { gap: 13, marginTop: 4 }, step: { flexDirection: "row", gap: 12 }, stepNumber: { width: 27, height: 27, borderRadius: 14, backgroundColor: "#1E4D3A", alignItems: "center", justifyContent: "center" }, stepNumberText: { color: "#FFFFFF", fontSize: 12, fontWeight: "900" }, stepText: { flex: 1, color: "#49554D", fontSize: 14, lineHeight: 20, paddingTop: 2 },
  tip: { flexDirection: "row", gap: 10, backgroundColor: "#FCE6D2", borderRadius: 18, padding: 13, marginTop: 8 }, tipTitle: { color: "#754626", fontSize: 13, fontWeight: "800" }, tipText: { color: "#9A6138", fontSize: 12, lineHeight: 17, marginTop: 2 }, planButton: { minHeight: 52, marginTop: 7, borderRadius: 16, backgroundColor: "#1E4D3A", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 9 }, planButtonText: { color: "#FFFFFF", fontSize: 15, fontWeight: "800" },
});
